Fix Quoting of arguments from Jetty `start.jar --dry-run`
eclipse/jetty.project pull request #10100
Opened 2023-07-12 20:02 UTC by joakime

This addresses the concerns brought up by Issue #10055 with a minimal fix.

2023-07-12 20:03 UTC, joakime commented
This is DRAFT, as more work on `jetty.sh` is being done to avoid re-evaluating the `RUN_ARGS` once they are set, to avoid double-expansion of arguments by the shell.

2023-07-12 20:04 UTC, joakime commented on jetty-home/src/main/resources/bin/jetty.sh
> +        echo ${RUN_ARGS[*]} | xargs ${JAVA} & # TODO: don't check in this version only used for cli debugging
This is temporary.

2023-07-12 22:45 UTC, joakime commented
After a conversation with @sbordet and @lorban to show them what we are dealing with, it might be possible to write unit tests that actually execute `jetty.sh` in a safe way.

Stay tuned, going to write up a few examples Thursday.

2023-07-13 04:31 UTC, gregw requested changes
Why has this forked my branch and lost recent work? There is no need to do things like lookup tables, as this does not need to be super fast, plus it is only used at startup, so likely more time spent building lookup table than using it.

If there is an issue with jetty.sh, then I would prefer that work was done in #10099 and it is fixed, rather than redoing the work on quoting.

2023-07-14 16:38 UTC, joakime commented
Closing in favor of #10099

2023-07-14 16:38 UTC, closed without merging