rename JAVAX_API to JAKARTA_API in ee9 and ee10 Source
eclipse/jetty.project pull request #10165
Opened 2023-07-28 05:14 UTC by lachlan-roberts

2023-07-28 12:08 UTC, joakime requested changes
Some javadoc you missed.

Also, what about the JAVAX references in jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/ReflectUtils.java ?

2023-07-28 12:08 UTC, joakime commented on jetty-ee10/jetty-ee10-annotations/src/test/java/org/eclipse/jetty/ee10/annotations/TestAnnotationIntrospector.java
>              //a JAVAX API sourced servlet can be introspected
```suggestion
            //a JAKARTA API sourced servlet can be introspected
```

2023-07-28 12:08 UTC, joakime commented on jetty-ee9/jetty-ee9-annotations/src/test/java/org/eclipse/jetty/ee9/annotations/TestAnnotationIntrospector.java
>              //a JAVAX API sourced servlet can be introspected
```suggestion
            //a JAKARTA API sourced servlet can be introspected
```

2023-07-31 02:19 UTC, lachlan-roberts commented
@joakime the `ReflectUtils` is used for both Javax and Jakarta websocket implementations. So I think it needs both.

2023-07-31 06:31 UTC, olamy approved these changes

2023-07-31 16:12 UTC, joakime approved these changes

2023-08-01 01:22 UTC, merged