Fixes #10160 - Verify PROXY_AUTHENTICATION is sent to forward proxies
eclipse/jetty.project pull request #10162
Opened 2023-07-27 10:34 UTC by sbordet

Now TunnelRequest.getURI() does not return null, so normalizeRequest() can properly apply the authentication headers.

2023-07-27 12:19 UTC, lorban commented
All tests in `ForwardProxyTLSServerTest` fail with HTTP 500.

2023-07-28 23:15 UTC, sbordet commented
@lorban should be fixed now.

2023-07-31 13:18 UTC, lorban requested changes
I just found one questionable change.

2023-07-31 13:18 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java
> +        return "h2".equalsIgnoreCase(protocol) || "h2c".equalsIgnoreCase(protocol);
With this implementation, if `serverOrigin` only supports `h2c` and `HttpProxy` only supports `h2` there will be a match. Is that expected?

2023-07-31 15:14 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java
> +        return "h2".equalsIgnoreCase(protocol) || "h2c".equalsIgnoreCase(protocol);
Yes, it's expected.

The reason is that if server and proxy speak the same protocol, there is no need to wrap the server protocol into a CONNECT.
`h2` is just `h2c` over TLS, so the protocol is the same.

2023-07-31 15:18 UTC, lorban approved these changes

2023-07-31 16:15 UTC, gregw reviewed
I'll just comment a small niggle rather than a review.   Happy for it to be as-is, or with niggle fixed.

2023-07-31 16:15 UTC, gregw commented on jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
> +                    newRequest.path(request.getPath());
I have a slight preference for something like
```suggestion
                Request newRequest = (HttpMethod.CONNECT.is(request.getMethod()))
                    ? client.copyRequest(request, request.getPath());
                    : client.copyRequest(request, request.getURI());
```

Or if the right copyRequest semantic can't be easily provided, then at least below would be a little clearer to me:

```suggestion
                Request newRequest = client.copyRequest(request, request.getURI());
                if (HttpMethod.CONNECT.is(request.getMethod()))
                    newRequest.path(request.getPath());
```

2023-07-31 16:32 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
> +                    newRequest.path(request.getPath());
The first proposed change is not correct.

The second proposed change just replaces the variable `newRequest` with `request`, which I don't see how it is clearer?

2023-07-31 16:39 UTC, merged

2023-07-31 17:19 UTC, gregw commented on jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java
> +                    newRequest.path(request.getPath());
@sbordet the first proposal is pseudo code: check the method of the original request first and then build the new request appropriately.

The second proposal is clearer to me, as I don't have to do the double take of thinking: oh it is conditional on its own method... oh what is its method, oh it copied it from the original request, ah so it is just the method of the original request.   It is clearer just to make it conditional on the method of the original request.