Issue #10312 Remove cyclic dependencies between jetty-home and jetty-documentation. Add new module jetty-documentation
eclipse/jetty.project pull request #10348
Opened 2023-08-21 03:43 UTC by olamy

- Issue #10312 Remove cyclic dependencies between jetty-home and jetty-documentation
- cleanup jetty home build extracting jetty-documentation
- add jetty-documentation module

2023-08-21 03:49 UTC, olamy commented
this displays the documentation as http://localhost:8080/jetty-documentation/10.0.16-SNAPSHOT/
the path is really weird, but I'm not sure how to fix that as the jetty-documemtation-html.zip have the version as root path

2023-08-21 08:47 UTC, olamy commented
I wonder if we shouldn't have jetty-javadoc module as well with the full javadoc?

2023-08-23 21:49 UTC, joakime commented
Can we just get rid of jetty-home-with-docs archives entirely?

2023-08-23 21:49 UTC, olamy commented
> Can we just get rid of jetty-home-with-docs archives entirely?

+1

2023-08-23 21:49 UTC, joakime commented
Proposal.

* drop jetty-home-with-docs artifacts
* drop documentation module
* don't create a javadoc module

2023-08-24 15:18 UTC, joakime submitted a review, later dismissed

2023-08-24 17:04 UTC, sbordet requested changes

2023-08-24 17:04 UTC, sbordet commented on documentation/jetty-documentation/pom.xml
> +            <id>unpack-documentation</id>
This should be named `unpack-jetty-home`.

2023-08-24 17:04 UTC, sbordet commented on documentation/jetty-documentation/pom.xml
> +      <optional>true</optional>
Why optional? This is mandatory.

2023-08-24 17:04 UTC, sbordet commented on jetty-home/src/main/resources/etc/jetty-documentation.xml
> +</Configure>
No, remove this file.

2023-08-24 17:04 UTC, sbordet commented on jetty-home/src/main/resources/modules/jetty-documentation.mod
> +maven://org.eclipse.jetty.documentation/jetty-documentation/${jetty.version}/zip/html|lib/jetty-documentation/jetty-documentation.war
No, remove this file.

2023-08-24 17:28 UTC, sbordet approved these changes

2023-08-24 17:41 UTC, merged