Fix #10411 default environment
eclipse/jetty.project pull request #10415
Opened 2023-08-27 07:19 UTC by gregw

Implemented a simpler default environment algorithm where an application that does not specify an environment is always attempted in the default.

2023-08-28 22:37 UTC, joakime approved these changes
Seems simpler. +1

2023-08-28 22:44 UTC, gregw commented
As this is ready, I have moved it back for consideration in 12.0.1

2023-08-29 08:06 UTC, lorban requested changes
Either that's a typo, or we need a comment explaining the -11.

2023-08-29 08:06 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Deployable.java
> +            return -11;
Does this one _really_ has to go to 11?

2023-08-29 08:20 UTC, sbordet requested changes
Please go do file `deploy-jetty-adoc` line 40 and modify the sentence from:

`The Jetty content XML file must be accompanied...`

to 

`The Jetty content XML file may be accompanied...`

Also, modify `DistributionTests.testXmlDeployWarNotInWebapps()` so that it has 1 more boolean parameter, namely whether to write the `demo.properties` file or not.
In this way, we are testing that your fixes work as intended even in the case the `*.war` is not inside `$JETTY_HOME/webapps/`.

If you wan to go the extra mile, I would not mind in `DistributionTests` to add a test with 2 XML files and different environments that also verifies that one of them must have the `*.properties` file to be deployed correctly.

2023-08-29 08:20 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Deployable.java
> +            return -11;
Should be -1?

2023-08-29 13:16 UTC, lorban approved these changes

2023-08-29 16:34 UTC, merged