Accurate implementation of FCGI `Request.beginNanoTime()`
eclipse/jetty.project pull request #10425
Opened 2023-08-28 13:51 UTC by lorban

The implementation is similar to H1: take a nano timestamp at the time the very first byte is read, then use that timestamp to create the `MetaData.Request`.

2023-08-28 15:51 UTC, sbordet requested changes

2023-08-28 15:51 UTC, sbordet commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
Remove TODO at EOL.

2023-08-28 15:51 UTC, sbordet commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        ServerFCGIConnection serverFCGIConnection = (ServerFCGIConnection)getHttpChannel().getConnectionMetaData().getConnection();
Uh? Use `_connection` instead.

2023-08-29 08:02 UTC, lorban commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
Duh! Done.

2023-08-29 08:02 UTC, lorban commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        ServerFCGIConnection serverFCGIConnection = (ServerFCGIConnection)getHttpChannel().getConnectionMetaData().getConnection();
Duh! Done.

2023-08-29 08:26 UTC, sbordet approved these changes

2023-08-29 14:40 UTC, joakime approved these changes
Pretty straight forward.

2023-08-29 15:11 UTC, merged

2023-09-20 11:13 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
Kun7310201214

2023-09-20 11:14 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
> Remove TODO at EOL.

2023-09-20 11:14 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
> Remove TODO at EOL.

2023-09-20 11:14 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
> Duh! Done.

2023-09-20 11:15 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
> Remove TODO at EOL.

Kun7310201214

2023-09-20 11:16 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        MetaData.Request request = new MetaData.Request(serverFCGIConnection.getBeginNanoTime(), _method, scheme.asString(), hostPort, pathQuery, HttpVersion.fromString(_version), _headers, -1); // T
Kun731020

2023-09-20 11:20 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        ServerFCGIConnection serverFCGIConnection = (ServerFCGIConnection)getHttpChannel().getConnectionMetaData().getConnection();
Kun731020

2023-09-20 11:21 UTC, mail731212 commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/HttpStreamOverFCGI.java
> +        ServerFCGIConnection serverFCGIConnection = (ServerFCGIConnection)getHttpChannel().getConnectionMetaData().getConnection();
> Kun731020