Fix server HTTP buffer leak in `consumeAvailable()`
eclipse/jetty.project pull request #10428
Opened 2023-08-29 09:19 UTC by lorban

When `consumeAvailable()` is called, the connection may hold onto a buffer that must be released.

2023-08-29 09:21 UTC, sbordet approved these changes

2023-08-29 14:44 UTC, joakime approved these changes

2023-08-29 15:33 UTC, lorban commented
This requires more investigation as `consumeAvailable` should release any pending buffers. And #9169 might be related.

2023-08-30 07:59 UTC, lorban commented
`HttpStream.consumeAvailable()` is designed such that it does not necessarily release all buffers but returns non-null when such a case occurs. This is the trigger condition to indicate that the buffer can be released.

2023-09-08 14:05 UTC, sbordet requested changes
Let's try to find the root cause of why the buffers are leaked.

2023-09-08 14:17 UTC, sbordet requested changes

2023-09-08 14:17 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
> +            _server.setConnectors(new Connector[]{});
Remove these 2 lines, not necessary.

2023-09-08 14:17 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
> +            Awaitility.await().atMost(3, TimeUnit.SECONDS).until(() -> _bufferPool.getLeaks().size(), Matchers.is(0));
Make it 5 seconds like everywhere else.

2023-09-08 14:19 UTC, lorban commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
> +            _server.setConnectors(new Connector[]{});
Done.

2023-09-08 14:19 UTC, lorban commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpServerTestFixture.java
> +            Awaitility.await().atMost(3, TimeUnit.SECONDS).until(() -> _bufferPool.getLeaks().size(), Matchers.is(0));
Done.

2023-09-08 14:51 UTC, sbordet approved these changes

2023-09-11 09:47 UTC, merged