Changed default implementation of Session.Listener.onNewStream() and …
eclipse/jetty.project pull request #10672
Opened 2023-10-05 13:16 UTC by sbordet

…Stream.Listener.onDataAvailable() to auto-discard DATA frames.

For normal cases, these methods are overridden and the application is in full control. For test cases, these methods may not be overridden and the default implementation conveniently avoids buffer leaks.

Fixed flaky test RawHTTP2ProxyTest.testRawHTTP2Proxy() due to the bad assumption that the first DATA frame ends the stream (so an aggregator is needed), and a copy/paste error in ServerToProxyToClient while processing DATA frames.

2023-10-05 15:10 UTC, lorban requested changes

2023-10-05 15:10 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java
> +            stream.demand();
In `HTTP2Stream.setListener()` there is a `if (listener == null) demand();` block.

Can't you replace it with `if (listener == null || listener == AUTO_DISCARD) demand();` so that returning null would have the exact same effect as returning AUTO_DISCARD, hence rendering this `demand()` call useless?

2023-10-05 15:10 UTC, lorban commented on jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferAggregator.java
> +            throw new IllegalArgumentException("maxSize (" + maxSize + ") must be > startSize (" + startSize + ")");
This change is wrong; the error message used to be correct.

2023-10-05 15:36 UTC, sbordet commented on jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java
> +            stream.demand();
It'll work only for `onPush()`, because a PUSH_PROMISE has implicitly `endStream=false`.

In `Session.Listener.onNewStream()` the check to demand looks at the `endStream` flag and only demands if it is `false`, a check that cannot be done in `setListener()`.

I'd prefer this way, unless other evidence.

2023-10-05 16:55 UTC, lorban approved these changes

2023-10-06 10:58 UTC, gregw approved these changes
I'm good with it as is... but I think there could be a refinement around combining the cases of a null listener and an AUTO_DISCARD one.

2023-10-06 10:58 UTC, gregw commented on jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java
> +            stream.demand();
Would another way of doing this be to have `AUTO_DISCARD#onNewStream`  do the demand? .... it is almost like the default listener should be `AUTO_DISCARD` unless another is set?

2023-10-06 12:18 UTC, merged