Issue #10696 - Addressing start-stop-daemon behaviors in jetty.sh
eclipse/jetty.project pull request #10700
Opened 2023-10-10 16:14 UTC by joakime

* moving the `touch <file>` tests to only execute if the `JETTY_USER` is unspecified. (ie: no user id change)
* moving the `--module=pid` out from `jetty.conf` into the flows that do not use `start-stop-daemon`
* re-introducing the `USE_START_STOP_DAEMON=1` to the `jetty.sh` to allow disabling its based on configuration.

2023-10-10 17:57 UTC, joakime commented
@olamy i'd like to use testcontainers and add a set of docker testing for jetty.sh

I've been doing it manually with the docker images i have at https://github.com/joakime/jettysh-tests
But I think we should bring this into regular jetty unit/integration testing.
Got any pointers?

Ideally we would build a Docker image from our own committed Dockerfiles, and we can test via shell script or direct bash commands?

2023-10-10 19:50 UTC, joakime commented
I don't think we can use the testcontainers / docker to test the linux service startup techniques (init.d or systemd).

2023-10-10 21:21 UTC, joakime commented
Note: this change is for `jetty-10.0.x` (and `jetty-11.0.x`),  This `jetty.sh` isn't 100% compatible with `jetty-12.0.x`.

The only difference in the `jetty.sh` script between `jetty-10.0.x` and `jetty-12.0.x` is the addition of the `env` option on `--dry-run` on `jetty-12.0.x`.
Users of Jetty 12 will have to wait for the merge of this change up to `jetty-12.0.x` before they can use this fixed `jetty.sh`

2023-10-11 02:36 UTC, gregw requested changes

2023-10-11 02:36 UTC, gregw commented on jetty-home/src/main/resources/bin/jetty.sh
> +      echo ${RUN_ARGS[@]} | xargs start-stop-daemon \
I'm thinking that the whole ${RUN_ARGS[@]} thing just doesn't work.  We abandonned that approach in the docker shell and instead use files and a dot command.  However, here I think we could perhaps just do:
```suggestion
      { echo jetty.state=$JETTY_STATE;  echo jetty.pid=$JETTY_PID;  echo  $JETTY_SYS_PROPS; "$JAVA" -jar "$JETTY_START" --dry-run=opts,path,main,args ;  } | xargs start-stop-daemon \
```

2023-10-11 02:38 UTC, gregw commented on jetty-home/src/main/resources/bin/jetty.sh
> +      echo ${RUN_ARGS[@]} | xargs start-stop-daemon \
OK I'm missing some complexities with JETTY_ARGS and JETTY_CONF here, but the point is the same: using xargs appears to be a workable way of assembling a command line that correctly preserves quoting.

2023-10-11 02:39 UTC, gregw commented on jetty-home/src/main/resources/bin/jetty.sh
> +      echo ${RUN_ARGS[@]} | xargs start-stop-daemon \
or build a file that we can run with .

2023-10-12 02:40 UTC, gregw commented on jetty-home/src/main/resources/bin/jetty.sh
> +      echo ${RUN_ARGS[@]} | xargs start-stop-daemon \
Actually I think the `echo ${RUN_ARGS[@]} | xargs start-stop-daemon ` mechanism works/

2023-10-13 19:45 UTC, joakime commented
@gregw i'm happy with this version, it's been testing well in various virtual machines (so I can test service start/stop behaviors), and also basic docker setups (not our image), and even command line.

2023-10-15 21:22 UTC, gregw requested changes
This still fails the test I described in #10696 :
```
[1011] ../jetty-home/bin/jetty.sh start
ERROR : Unrecognized argument: "dir" in <command-line>

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
Starting Jetty: .Unrecognized option: --start-log-file=/home/gregw/src/jetty-10.0.x/jetty-home/target/base/jetty/jetty-start.log
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
...
``` 

This diff fix I posted there still applies, but no longer fixes that test.

2023-10-15 21:23 UTC, gregw commented
@joakime  I'm reposting this comment I made in the issue here.  This is still failing with your latest version.

I've found and "fixed" another pathological test case (that we should include).     I created a base dir like:
```
[1205] tree .
.
├── dir one
│   └── test1.xml
├── dir two
│   └── test2.xml
├── etc
│   └── jetty.conf
├── jetty
├── modules
│   └── test.mod
├── resources
│   └── jetty-logging.properties
└── start.d
    ├── server.ini
    └── test.ini
```

modules/test.mod is
```
[exec]
-showversion
-XX:+PrintCommandLineFlags
-Xlog:gc*:file=/tmp/logs/gc.log:time,level,tags
-XX:ErrorFile=/tmp/logs/jvm_crash_pid_%p.log
```

etc/jetty.conf is
```
# test configurations with spaces
dir one/test1.xml
dir two
```

The xml files are both just:
```xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">
</Configure>
```

This died in numerous ways.  The "fix" I have is
```sh
diff --git a/jetty-home/src/main/resources/bin/jetty.sh b/jetty-home/src/main/resources/bin/jetty.sh
index 9fd13d0281..c6882a543d 100755
--- a/jetty-home/src/main/resources/bin/jetty.sh
+++ b/jetty-home/src/main/resources/bin/jetty.sh
@@ -471,14 +471,14 @@ then
       do
         if [ -r "$XMLFILE" ] && [ -f "$XMLFILE" ]
         then
-          JETTY_ARGS=(${JETTY_ARGS[*]} "$XMLFILE")
+          JETTY_ARGS=(${JETTY_ARGS[*]} "'$XMLFILE'")
         else
           echo "** WARNING: Cannot read '$XMLFILE' specified in '$JETTY_CONF'"
         fi
       done
     else
       # assume it's a command line parameter (let start.jar deal with its validity)
-      JETTY_ARGS=(${JETTY_ARGS[*]} "$CONF")
+      JETTY_ARGS=(${JETTY_ARGS[*]} "'$CONF'")
     fi
   done < "$JETTY_CONF"
 fi
@@ -566,7 +566,7 @@ then
 fi
 
 # Collect the dry-run (of opts,path,main,args) from the jetty.base configuration
-JETTY_DRY_RUN=$("$JAVA" -jar "$JETTY_START" --dry-run=opts,path,main,args ${JETTY_ARGS[*]} ${JAVA_OPTIONS[*]})
+JETTY_DRY_RUN=$({ echo -jar "$JETTY_START" --dry-run=opts,path,main,args ; echo ${JETTY_ARGS[*]} ${JAVA_OPTIONS[*]} ; } | xargs "$JAVA" )
 RUN_ARGS=($JETTY_SYS_PROPS ${JETTY_DRY_RUN[@]})
 
 if (( DEBUG ))
```

Specifically I am adding single quotes around what I know are single arguments.
Then I'm using the xargs technique for running the dry-run command as well.

Edit: I applied this fix to the latest version and it no longer fixes it.  So more work is needed.

2023-10-16 19:02 UTC, joakime commented
That's a great testcase / scenario / usecase @gregw 

I really need to get these into a set of docker tests (with the important configurations), i'll prioritize this over the next 2 days.

2023-10-25 14:31 UTC, joakime commented
Closing in favor of PR #10753

2023-10-25 14:31 UTC, closed without merging