Allow POSTing with a URL not ending with '/' to jax-ws endpoints
eclipse/jetty.project pull request #10710
Opened 2023-10-11 16:40 UTC by lorban

Since the default JAX-WS web server allows POSTing to URLs not ending with `/`, Jetty has to allow that too so it can be used as a compatible drop-in replacement.

Fixes #10699

2023-10-11 18:19 UTC, joakime commented
Got some build / test issues to resolve in this PR.

```
class org.eclipse.jetty.http.spi.JaxWsEndpointTest (in module org.eclipse.jetty.http.spi) cannot access class org.eclipse.jetty.logging.StacklessLogging (in module org.eclipse.jetty.logging) because module org.eclipse.jetty.http.spi does not read module org.eclipse.jetty.logging
```

and a flaky test showing a buffer leak.

2023-10-13 09:05 UTC, sbordet requested changes

2023-10-13 09:05 UTC, sbordet commented on jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/JaxWsEndpointTest.java
> +    private static HttpClient CLIENT;
Not `static` please.

2023-10-16 08:00 UTC, sbordet approved these changes

2023-10-16 15:23 UTC, joakime approved these changes

2023-10-17 12:18 UTC, merged