Fix  EE10 removeAttributes
eclipse/jetty.project pull request #10727
Opened 2023-10-12 11:15 UTC by gregw

Fixes #10714
Allow all attributes, including synthetic ones, to be removed.

2023-10-12 19:40 UTC, joakime approved these changes, later dismissed

2023-10-12 23:43 UTC, janbartel requested changes

2023-10-12 23:43 UTC, janbartel commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
> +    private static final Object NULL_VALUE = new Object();
Move to top of file in field declaration section.

2023-10-16 03:55 UTC, gregw commented
I'm 99% certain the CI tests are unrelated.   @olamy any thoughts why CI is failing?

2023-10-16 04:02 UTC, olamy commented
> I'm 99% certain the CI tests are unrelated. @olamy any thoughts why CI is failing?

the tests  org.eclipse.jetty.tests.distribution.DistributionTests.testWebAppWithProxyAndJPMS(String) are proxying requests to https://eclipse.dev/jetty/javadoc/jetty-12/index.html?overview-summary.html
which looks to have an expired certificate...  (expiration date 16Th October 2023 :) )
you can wait Eclipse fix it, apply similar changes as here (https://github.com/jetty/jetty.project/pull/10686) tagging the test as requiring some external resources, or merge as it as we know the reason

2023-10-16 06:29 UTC, janbartel approved these changes

2023-10-16 10:24 UTC, merged