Jetty 12 merge from 11
eclipse/jetty.project pull request #10733
Opened 2023-10-13 12:47 UTC by lorban

Merge from 11 the fix for #10705

2023-10-13 22:35 UTC, olamy approved these changes

2023-10-15 21:26 UTC, sbordet approved these changes

2023-10-15 21:27 UTC, sbordet requested changes
Where is the test case written for 10?

2023-10-16 10:16 UTC, lorban commented
Merged through another channel.

2023-10-16 10:16 UTC, closed without merging