WebSocketUpgradeHandler should not require ContextHandler
eclipse/jetty.project pull request #10768
Opened 2023-10-23 04:20 UTC by lachlan-roberts

`WebSocketUpgradeHandler` should not be required to be wrapped inside a `ContextHandler`

2023-10-23 13:14 UTC, sbordet commented
@lachlan-roberts can you explain why you need this? I'm not against it, just curious about why.
Please add the project this PR belongs to (and an issue if any).

2023-10-24 00:27 UTC, lachlan-roberts commented
I don't specifically need this and I did not create an issue for it. I just saw these tests and didn't think the `WebSocketUpgradeHandler` should be forced to be under a `ContextHandler`. 

We don't require a `ContextHandler` for the websocket-core upgrade handler.

2023-10-24 08:50 UTC, sbordet requested changes

2023-10-24 08:50 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketServerComponents.java
> +        return ensureWebSocketComponents(server, server, server);
For symmetry, 2nd parameter shouldn't be `server.getContext()`?

2023-10-24 08:50 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketServerComponents.java
> +        WebSocketComponents components = (WebSocketComponents)server.getAttribute(WEBSOCKET_COMPONENTS_ATTRIBUTE);
Refactor both methods to call a private method that takes `Attributes` as parameter?

2023-10-24 08:50 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/ServerWebSocketContainer.java
> +
I'd remove this, I prefer to keep instantiation through static methods.

2023-10-24 08:50 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeHandler.java
> +
I'd remove this too, prefer the static methods.

2023-11-20 09:45 UTC, sbordet approved these changes, later dismissed
@lachlan-roberts I have updated WebSocketUpgradeHandler to expose the ServerWebSocketContainer as attribute also when created with only the Server.
LGTM now.

2023-11-20 18:29 UTC, sbordet approved these changes

2023-11-20 18:30 UTC, merged