Issue #10687 - WebSocket remembers mappings on restart
eclipse/jetty.project pull request #10773
Opened 2023-10-24 00:05 UTC by lachlan-roberts

## Fixes #10687

- Ensure the `WebSocketMappings` is cleared on restart of the server.
- Make the configurator on the `WebSocketUpgradeHandler` run in `doStart()` so configuration is reapplied when starting.

2023-10-24 09:42 UTC, sbordet requested changes
As discussed, let's add the `Consumer<ServerWebSocketContainer>` as a parameter to a new static method, like ee10.

2023-11-09 03:58 UTC, gregw approved these changes, later dismissed
Just some javadoc, otherwise good.

2023-11-09 03:58 UTC, gregw commented on jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketUpgradeHandler.java
> +    public WebSocketUpgradeHandler(WebSocketComponents components, Consumer<WebSocketUpgradeHandler> configurator)
Need javadoc to clearly say when the configurator is called.

2023-11-09 03:58 UTC, gregw commented on jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketUpgradeHandler.java
> +    private final WebSocketMappings _mappings;
luv your underscore work!

2023-11-09 03:58 UTC, gregw commented on jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeHandler.java
> +     * be configured during the starting phase of the {@link WebSocketUpgradeHandler}.
```suggestion
     * @param configurator a {@link Consumer} that is called to configure the {@link ServerWebSocketContainer}
     * during the starting phase of the {@link WebSocketUpgradeHandler}.   Mappings should be added to the container
     * in the confugurator on each start of the handler as they will not be preserved on any subsequent starts.
```

2023-11-20 16:08 UTC, sbordet approved these changes

2023-11-20 16:08 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/WebSocketUpgradeHandler.java
> +    public ServerWebSocketContainer getContainer()
Rename to `getServerWebSocketContainer()`.

2023-11-20 16:09 UTC, merged