Fixes #10806 - Introduce RequestLogWrapper to address SocketAddress concerns
eclipse/jetty.project pull request #10861
Opened 2023-11-06 20:36 UTC by joakime

Alternate approach from PR #10815 

Uses a `RequestLogWrapper` to address requestlog concerns, instead of modifying the low level IO layer.

Fixes #10806

2023-11-07 16:05 UTC, sbordet approved these changes
LGTM beside the nit about Awaitility.
Much simpler solution than the other PR.

2023-11-07 16:05 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java
> +                        Awaitility.await().atMost(Duration.ofSeconds(5)).until(() -> !endPoint.isOpen());
Please `static import Awaitility.await` like we do with other testing facilities.

2023-11-08 21:02 UTC, gregw requested changes
I think I like the other approach more.  I don't like putting on another wrapper just to remember address data that might go away.

I prefer the approach that an end point has local/remote address regardless of it's open/close state.   In this case we have been caught by the request log, but I can imagine other situations (specially debugging) that we are racing with a close to get the addresses.

Far better to make the the addresses on an endpoint immutable rather than always wrap them in case they are not.

2023-11-08 22:27 UTC, gregw commented
@sbordet @joakime I now agree that #10815 is wrong to fix the remote/local address in the EndPoint, as that is intrinsically dynamic.

This PR is correct in that the solution is to make the addresses immutable for the duration of a request cycle.    But it is doing that wrong,  as it is replacing a probably immutable ConnectionMetaData with a definitely immutable one.  So it is often wasted effort.

I think the correct solution is that ConnectionMetaData should always be immutable.  I.E any Connection that provides a ConnectionMetaData for a request cycle should provide a non-dynamic instance - so it will ask the endpoint at request init time what the addresses are.   That ConnectionMetaData will then never change.   The Connection can then decide if it reuses it for subsequent requests or creates a new one for every request.

2023-11-08 23:38 UTC, gregw commented
Note that the ConnectionMetaData is passed to the constructor of the HttpChannel, so that any connection type that does support changing addresses for remote/local will need to recreate the HttpChannel instance.
So the change here is that h3 will need to remake the ConnectionMetaData and HttpChannel's whenever it detects an address has changed (or maybe on every request cycle, but that could be slow).

@sbordet are h2/h3 recycling HttpChannel instances at the moment?   

@lorban at some stage we need to evaluate if recycling HttpChannels is worth it.... we can probably test that easily in HTTP/1, which does reuse, by making a version that does not.

2023-11-09 06:12 UTC, gregw commented
@joakime I've implemented my suggested approach, of making the addresses immutable within the `ConnectionMetaData`, which in practise for h1, h2 & FCGI is in the `Connection`, but for h3 is a new `ConnectionMetaData` in each `onRequest` call.

Note that this also revealed that only h2 was correctly respecting `HttpConfiguration.getLocalAddress()`.  I have now implemented for h1, h2, h3 & FCGI.

2023-11-09 21:56 UTC, joakime commented
Dropping in favor of #10867

2023-11-09 21:56 UTC, closed without merging