Jetty 12.0.x refactor jndi
eclipse/jetty.project pull request #10897
Opened 2023-11-15 10:24 UTC by janbartel

* extract all common classes from jetty-8/9/10 `plus` and `jndi` modules and move to `jetty-core/jetty-plus` and `jetty-core/jetty-jndi`
* remove direct dependency from ee8/9/10 `plus` on `jetty-jndi` implementation.
* add some more tests

2023-11-28 23:26 UTC, gregw requested changes
Mostly looks good... but....

2023-11-28 23:26 UTC, gregw commented on jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java
> +public class Transaction extends NamingEntry
Would `TransactionEntry` be a better name?

2023-11-28 23:26 UTC, gregw commented on jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/jndi/Transaction.java
I expected this `Transaction` to extend the core  `Transaction`?  why not?

2023-11-29 01:26 UTC, janbartel commented on jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/jndi/Transaction.java
Because there is no suitable constructor in `jetty-core` `Transaction.java`. The one in core binds into JNDI a `Reference/ObjectFactory` that when looked up produces an instance of `UserTransaction`. The one in `ee10` binds directly a `UserTransaction` instance.

2023-11-29 01:28 UTC, gregw commented on jetty-ee10/jetty-ee10-plus/src/main/java/org/eclipse/jetty/ee10/plus/jndi/Transaction.java
Then can we have a generic/templated one in core so that we have:
```java
    public class Transaction extends org.eclipse.jetty.jndi.Transaction<UserTransaction>
```

2023-11-29 20:54 UTC, gregw approved these changes, later dismissed

2023-12-04 06:04 UTC, gregw submitted a review, later dismissed

2023-12-04 06:20 UTC, olamy requested changes

2023-12-04 06:20 UTC, olamy commented on jetty-ee10/jetty-ee10-annotations/pom.xml
> +    <!-- dependency>
remove it instead of leaving a commented dependency

2023-12-05 01:46 UTC, olamy approved these changes

2023-12-05 22:48 UTC, merged