Issue #10926 - add support for CombinedResource in AttributeNormalizer
eclipse/jetty.project pull request #10927
Opened 2023-11-27 10:37 UTC by lachlan-roberts

allow `AttributeNormalizer` to support `CombinedResource`

2023-11-27 15:27 UTC, sbordet approved these changes, later dismissed
Not pretty to cast to `CombinedResource`, but it is what it is.
We can change the implementation later, as long as there is a test for the feature.

2023-11-27 16:19 UTC, lorban submitted a review, later dismissed

2023-11-27 19:35 UTC, joakime commented on jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java
> +        return ResourceFactory.root().newResource(asTargetPath(title, subpath));
Be careful to not let things (eg: mounts) linger in the root ResourceFactory

2023-11-27 21:49 UTC, gregw commented
See #8921

2023-11-27 22:07 UTC, gregw requested changes
I don't like the implementation, but it does appear to work.

Can we hangout and chat about alternatives?

2023-11-27 22:07 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java
> +        if (baseResource instanceof CombinedResource combinedResource)
You don't need to do this instanceof check.  Just always iterate over the Resource and you'll get a singleton iteration in the case of a non-combined resource.

2023-11-27 22:07 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java
> +                String expanded = normalizer.normalizePath(path);
This feels inside-out

I don't think we should be trying to normalize on each of the combined resources in turn as it might match multiple and we will need to duplicate whatever logic is inside CombinedResource here.

We need some way to ask a combined resource for which base resource was used and then just normalize against that.

2023-11-27 22:07 UTC, gregw commented on jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java
> +        // Uses the appropriate resource if the target exists.
Can you add tests for overlayed directories which might be found in multiple bases

2023-11-28 22:16 UTC, lachlan-roberts reviewed
LGTM

Not sure the weights are optimal but don't think it matters too much.
Probably the first resource should be weighted the most because its the most likely to be used.

2023-11-29 14:08 UTC, lorban approved these changes

2023-11-29 21:49 UTC, joakime approved these changes

2023-11-30 19:02 UTC, merged