Issue #11014 - Improve Relative Redirect Handling in Jetty 10/11
eclipse/jetty.project pull request #11018
Opened 2023-12-04 04:41 UTC by gregw

#11014
+ Common relative redirect method.
+ Use the relative redirect method from redirection rules.

2023-12-05 21:55 UTC, sbordet requested changes

2023-12-05 21:55 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +    public static String toRedirectURL(final HttpServletRequest request, String location)
Rename to `toRedirectURI()`, as RFC and Jetty 12 use "URI", not "URL".

Drop `final` for the first parameter.

Also, should clarify whether the `location` is already encoded or not?
E.g. `location: newPath?p=/oldPath` should the `/` be already encoded?

Perhaps it's just enough to change the variable name to `encodedLocation` to make it clear, but callers need to know.

2023-12-06 12:24 UTC, lorban approved these changes

2023-12-06 14:46 UTC, sbordet approved these changes
Just a nit on the use of `final`.

2023-12-06 14:46 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +    public static String toRedirectURI(final HttpServletRequest request, String location)
Drop `final`.

2023-12-06 14:51 UTC, joakime approved these changes

2023-12-06 20:11 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +    public static String toRedirectURI(final HttpServletRequest request, String location)
Ooops forgot.   It was there in the original method and gone in 12.  I'll keep here to not lose the green ticks.

2023-12-06 20:12 UTC, merged