Do not use HttpStream.Wrapper in SizeLimitHandler
eclipse/jetty.project pull request #11051
Opened 2023-12-13 00:44 UTC by lachlan-roberts

Using an HttpStream.wrapper will bypass the `GzipHandler` which wraps the request and response.
So we should also wrap the request and response in `SizeLimitHandler`.

This also fixes a bug where the read/write counts are not reset for each request.

2023-12-13 04:36 UTC, gregw approved these changes, later dismissed

2023-12-13 19:22 UTC, sbordet requested changes
Looks good, but:
* Please fix the class javadocs, as there are many typos.
* Please add documentation about this Handler in `server-http-handler-use.adoc`. You can find sections that talk about other utility handlers Jetty provides (such as GzipHandler, etc.), and you can take one of those sections as example for the `SizeLimitHandler`. At least add in the docs what's in the class javadocs.

2023-12-13 20:51 UTC, gregw submitted a review, later dismissed

2023-12-14 16:51 UTC, sbordet commented
@lachlan-roberts I have updated documentation and javadocs.

2023-12-14 16:52 UTC, sbordet approved these changes

2023-12-15 14:11 UTC, merged