Implemented proper handling of RST_STREAM(NO_ERROR) in HTTP/2.
eclipse/jetty.project pull request #11054
Opened 2023-12-13 13:09 UTC by sbordet

HTTP/3 could have the same handling, but apparently there is no way to receive a RESET_STREAM or STOP_SENDING frame in Quiche.

Now when receiving a RST_STREAM(NO_ERROR), it is not treated as a failure.

2023-12-13 20:47 UTC, gregw reviewed
just some initial comments/questions at this stage.

2023-12-13 20:47 UTC, gregw commented on jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
> +    public boolean dispose()
javadoc please.
Does it need to be public?

2023-12-13 20:47 UTC, gregw commented on jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java
> +            stream.reset(HTTP3ErrorCode.NO_ERROR.code(), new IOException("unconsumed content"));
why not use `CONTENT_NOT_CONSUMED`?

2023-12-15 00:49 UTC, gregw requested changes
Server side looks OK... but some questions.
Will need to work out why it is hanging in CI

2023-12-15 04:40 UTC, gregw commented
@sbordet how about in this release cycle we only change the server side to send the reset(NO_ERROR) and leave the client side as is.
We can then think a bit more about the client side changes in the next cycle?

2023-12-15 10:25 UTC, sbordet commented
> @sbordet how about in this release cycle we only change the server side to send the reset(NO_ERROR) and leave the client side as is. We can then think a bit more about the client side changes in the next cycle?

Agreed, see #11069.

2024-10-23 21:53 UTC, joakime commented
rebase against 12.1.x

2025-04-07 23:05 UTC, gregw commented
@sbordet Can we kill this or resuscitate

2025-04-08 18:03 UTC, sbordet commented
I'd say kill, we can revisit if necessary in the future.

2025-04-08 18:03 UTC, closed without merging