Fixes #11230  Problem with parsing of form parameters without values.
eclipse/jetty.project pull request #11255
Opened 2024-01-08 23:21 UTC by sbordet

Fixed parsing of form parameters in FormFields.parse(). 
Added more tests for valid edge cases, and invalid cases.

2024-01-09 13:16 UTC, joakime requested changes
Needs a few more test cases, and some test cases moved to the invalid side.

2024-01-09 13:16 UTC, joakime commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/FormFieldsTest.java
> +            Arguments.of(List.of("n=v&X=Y"), UTF_8, -1, 3, IllegalStateException.class),
Why are these 2 invalid?
Also, they look identical on this review, but the maxFields / maxLength is different?

2024-01-09 13:16 UTC, joakime commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/FormFieldsTest.java
> +        );
Some new test cases ...

* `"n=v%0A"` what happens if a value has a control character?
* `"n%0D=v"` what happens if a name has a control character?
* `"n%00=v"` what happens if a name has a null character?

2024-01-09 13:16 UTC, joakime commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/FormFieldsTest.java
> +            Arguments.of(List.of("%A"), UTF_8, -1, -1, Map.of("%A", "")),
single character pct-encoding?
This seems like a bug, and something we shouldn't support.

2024-01-09 14:46 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/FormFieldsTest.java
> +            Arguments.of(List.of("n=v&X=Y"), UTF_8, -1, 3, IllegalStateException.class),
maxFields=1 for the first, maxLength=3 for the second.

2024-01-09 15:17 UTC, joakime approved these changes

2024-01-09 15:17 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/FormFieldsTest.java
> +        );
Apparently control chars are allowed.

2024-01-11 13:51 UTC, lorban approved these changes

2024-01-12 10:22 UTC, merged