drop buildnumber creation already done by jetty-util
eclipse/jetty.project pull request #11360
Opened 2024-02-01 04:31 UTC by hboutemy

re-running buildnumber-maven-plugin a second time creates a new timestamp property value, which breaks Reproducible Builds https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/eclipse/jetty/jetty-project/README.md

AFAIK, the second run is not really necessary, just some cleanup forgotten that until now was not identified as causing any harm

2024-02-01 08:05 UTC, olamy commented
Thanks for this.
But this might break a bit jetty start. because of this code https://github.com/jetty/jetty.project/blob/2584eb0429c3de1b05722337f3787859c9551eff/jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java#L83

maybe we could repackage the `builld.properties` file generated by `jetty-util` (as `jetty-util` artifact is already expand here in `jetty-start` build)

2024-02-01 11:45 UTC, joakime requested changes
jetty-start's build.properties and jetty-util's build.properties are different.

jetty-start is for the bootstrap, which is loosely tied to a jetty version.
that jetty version is only use for defaulting the jetty-home/jetty-base version.
it can be overridden to be a different version at bootstrap (some folks do this!).

jetty-util build.properties is for runtime.  

completely eliminating the build.properties in jetty-start is a no-go, it's necessary and required, but for different reasons than the jetty-util build.properties.

just deleting it from jetty-start like this is not appropriate.
finding a way to copy the jetty-util version to jetty-start i would be ok with.

2024-02-02 06:34 UTC, hboutemy commented
sorry, the goal documentation was not clear it was generating the file in addition to calculating new property values

given the properties have already been generated, perhaps just injecting them into a filtered resource may give expected results from both ends: the file is still done, but reusing properties from first run

2024-02-14 00:48 UTC, hboutemy commented
@olamy what about loading the jetty-util one instead of copying it?

```
Props buildProps = Props.load(classLoader, "org/eclipse/jetty/version/build.properties");
```

2024-02-14 04:46 UTC, olamy commented
@hboutemy nah this will not work. look at the code I pointed in a previous comment.
we can avoid running again buildnumber plugin BUT we need to reuse the build.properties from jetty-util.
After build with your PR see the content of 
```
olamy@pop-os:~/dev/sources/jetty/jetty.project$ cat jetty-core/jetty-start/target/classes/org/eclipse/jetty/start/build.properties 
buildNumber=${buildNumber}
timestamp=${timestamp}
version=12.0.7-SNAPSHOT
```
compared to 
```
olamy@pop-os:~/dev/sources/jetty/jetty.project$ cat jetty-core/jetty-start/target/jetty-util/org/eclipse/jetty/version/build.properties 
buildNumber=671cab97b6ba01295f2e1caf062f4952273b53c3
timestamp=1706767565042
version=12.0.7-SNAPSHOT

```
so we need to include the second one in the jetty-start jar and read it. (can be moved as resource in the path `org/eclipse/jetty/start/build.properties` to keep backward compact (but I don't really think something else than jetty-start read it with such path) or change StartArgs class to read somewhere else (another path) in the classloader

2024-02-14 10:21 UTC, joakime commented
@hboutemy don't forget that jetty-start has a normal artifact, and a shaded artifact.
Both show up on maven central, and different groups of people use each.
We use the shaded artifact in `jetty-home/start.jar` (to avoid the requirement for a classpath).

```
[joakim@hyperion jetty-home-12.0.6]$ jar -tvf start.jar | grep -E "(util|properties)"
   172 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/build.properties
    64 Mon Jun 05 23:12:48 CDT 2023 META-INF/maven/org.eclipse.jetty/jetty-start/pom.properties
     0 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/
  7335 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/FileID.class
  2312 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/JavaVersion.class
  3635 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/ManifestUtils.class
  1371 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/TopologicalSort$CyclicException.class
  2364 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/TopologicalSort$InitialOrderComparator.class
  4987 Mon Jun 05 23:12:48 CDT 2023 org/eclipse/jetty/start/shaded/util/TopologicalSort.class
```

That means we should copy the jetty-util build.properties, not just reference it.
That would satisfy both artifact usages.

2024-02-14 17:02 UTC, hboutemy commented
> @hboutemy nah this will not work. look at the code I pointed in a previous comment. we can avoid running again buildnumber plugin BUT we need to reuse the build.properties from jetty-util. After build with your PR see the content of
> 
> ```
> olamy@pop-os:~/dev/sources/jetty/jetty.project$ cat jetty-core/jetty-start/target/classes/org/eclipse/jetty/start/build.properties 
> buildNumber=${buildNumber}
> timestamp=${timestamp}
> version=12.0.7-SNAPSHOT
> ```

uh, I did not get that the property defined by the first run of the goal was not available in other modules: good catch

2024-02-14 17:33 UTC, hboutemy commented
@olamy @joakime copy of `build.properties` from `jetty-util` to proper location done and tested in cb02948bc07e62638d35bedbcca41b93df629aa7

sorry for not checking sufficiently well previously

2024-02-14 17:58 UTC, joakime commented on jetty-core/jetty-start/pom.xml
> +                    <fileMapper implementation="org.codehaus.plexus.components.io.filemappers.FlattenFileMapper"></fileMapper>
Neat.  I didn't know this fileMapper existed.

2024-02-14 17:58 UTC, joakime approved these changes
I'm good with this.

2024-02-14 18:05 UTC, hboutemy commented on jetty-core/jetty-start/pom.xml
> +                    <fileMapper implementation="org.codehaus.plexus.components.io.filemappers.FlattenFileMapper"></fileMapper>
yes, not so easy to find from the plugin documentation: I need to improve it
https://codehaus-plexus.github.io/plexus-io/filemappers.html

2024-02-15 01:51 UTC, olamy approved these changes

2024-02-15 01:52 UTC, merged

2024-03-10 17:58 UTC, hboutemy commented
good news, with this PR merged, Jetty 12.0.7 is now confirmed reproducible https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/eclipse/jetty/jetty-project/README.md
(I just ignored html documentation)