Issue #11414 - use HttpURI for spec behaviors on scheme and port
eclipse/jetty.project pull request #11415
Opened 2024-02-16 12:28 UTC by joakime

Using HttpURI instead of URIUtil to have a single point of spec behavior.

Fixes #11414

2024-02-16 12:30 UTC, joakime commented
This PR is draft, as I haven't audited the other scheme / port usages across the codebase yet.
Just the ones that use URIUtil.

2024-02-16 13:20 UTC, gregw commented
@joakime this is certainly much better approach than #11390.    But doesn't it also leave the URIUtil normalization incorrect?

2024-02-16 13:29 UTC, joakime commented
> @joakime this is certainly much better approach than #11390. But doesn't it also leave the URIUtil normalization incorrect?

Yes, that's correct.
With this PR, nothing in our own Jetty code is using those now deprecated URIUtil methods.
The deprecated URIUtil methods in this PR work fine, but are not 100% compliant to the spec.

If you want this down in URIUtil then there is bound to be a fair amount of duplicated code, something you didn't like in #11390.

2024-02-16 13:40 UTC, gregw commented
> > @joakime this is certainly much better approach than #11390. But doesn't it also leave the URIUtil normalization incorrect?
> If you want this down in URIUtil then there is bound to be a fair amount of duplicated code, something you didn't like in #11390.

This PR still has URI normalization methods in URIUtil that are deprecated and do not normalize ports correctly.    So that's the duplication I don't like.

Now with this PR, we are creating a mutable `HttpURI` only to `toString` it, when the `URI` might not even be `HTTP`.

Can't we just fix the `URIUtil` methods to act correctly and they can be used when we are working with possibly non HTTP URIs in string form.      If we know we have a HTTP URI, then we can use `HttpURI`, which should also normalize correctly, but leaves the result as a structured object rather than as a string.

2024-02-16 14:15 UTC, gregw commented
@joakime I think we should add the following methods to `URIUtil`:
```java

    private static final Index<Integer> defaultPortForScheme = new Index.Builder<Integer>()
        .caseSensitive(false)
        .with("ftp", 21)
        .with("ssh", 22)
        .with("telnet", 23)
        .with("smtp", 25)
        .with("http", 80)
        .with("ws", 80)
        .with("https", 443)
        .with("wss", 443)
        .build();

    public static int defaultPortForScheme(String scheme)
    {
        Integer port = defaultPortForScheme.get(scheme);
        return port == null ? -1 : port;
    }

    public static String normalizeScheme(String scheme)
    {
        return StringUtil.asciiToLowerCase(scheme);
    }
```

Then we can modify `HttpScheme` to use them:
```java

public enum HttpScheme
{
    HTTP("http"),
    HTTPS("https"),
    WS("ws"),
    WSS("wss");
    
    // ...

    HttpScheme(String s)
    {
        _string = s;
        _buffer = BufferUtil.toBuffer(s);
        _defaultPort = URIUtil.defaultPortForScheme(s);
    }
```

We should keep the `HttpURI` fixes from this PR (perhaps using `URIUtil.normalizeScheme(String)` rather than directly calling toLowerCase.

Finally we should fix the other methods in URIUtil to normalize to scheme and port.

2024-02-16 14:16 UTC, gregw requested changes

2024-02-16 14:16 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
> +        return new Mutable(scheme, host, port, path, query, fragment).asImmutable();
Since there is no parsing happening on any of the components, we can probably bypass creating the Mutable and just go directly to a new constructor on Immutable.  (This may apply to some other from methods as well).

2024-02-16 14:16 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
> +                    out.append(':').append(normalizedPort);
Good!

2024-02-16 14:16 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
> -                port = 0;
Good!

2024-02-16 14:19 UTC, joakime commented
> This PR still has URI normalization methods in URIUtil that are deprecated and do not normalize ports correctly. So that's the duplication I don't like.
> 
> Now with this PR, we are creating a mutable `HttpURI` only to `toString` it, when the `URI` might not even be `HTTP`.

That can be solved with a HttpURI.toString(scheme,host,port,path,query,fragment) methods instead.

> Can't we just fix the `URIUtil` methods to act correctly and they can be used when we are working with possibly non HTTP URIs in string form. If we know we have a HTTP URI, then we can use `HttpURI`, which should also normalize correctly, but leaves the result as a structured object rather than as a string.

I've done an audit of our scheme behaviors this morning.

Excluding test cases, here's our usage of the various methods that are scheme related across our codebase.

Usage Count | Method
----- | -----
6 usages of | `URIUtil.newURI(String scheme, String server, int port, String path, String query)`
3 usages of | `URIUtil.newURIBuilder(String scheme, String server, int port)`
6 usages of | `URIUtil.appendSchemeHostPort(StringBuilder url, String scheme, String server, int port)`
5 usages of | `URIUtil.appendSchemeHostPort(StringBuffer url, String scheme, String server, int port)`
1 usage of | `HttpURI.from(String scheme, HostPort hostPort, String pathQuery)`
2 usages of | `HttpURI.from(String scheme, String host, int port, String pathQuery)`
14 usages of | `HttpURI.scheme(String scheme)`
2 usages of | `HttpURI.scheme(HttpScheme scheme)`
0 usages of | (client) `Request.scheme(String scheme)`
11 usages of | `HttpScheme.getDefaultPort(String scheme)`
1 usage of | `HttpScheme.normalizePort(String scheme, int port)`
9 usages of | `HttpScheme.isSecure(String scheme)`

Usage count per class:

* URIUtil - 20
* HttpURI - 19
* HttpScheme - 21

2024-02-16 14:34 UTC, joakime commented on jetty-ee9/jetty-ee9-openid/src/main/java/org/eclipse/jetty/ee9/security/openid/OpenIdAuthenticator.java
> +                    URIUtil.addPaths(baseRequest.getContextPath(), _logoutRedirectPath)
Not using addPaths() was a minor bug discovered during this PR.

2024-02-17 12:35 UTC, joakime commented
Closing in favor of #11416 which further expands the concepts here.

2024-02-17 12:35 UTC, closed without merging