Fixes #11370 - IllegalStateException when last write fails.
eclipse/jetty.project pull request #11439
Opened 2024-02-22 18:34 UTC by sbordet

Removed the call to `ServletChannel.abort()` from the write callback.

As the write was issued from `ServletChannel.handle()` case COMPLETE, it was eventually calling `ServletChannelState.completed(Throwable)`, which is expecting the requestState to be COMPLETING. However, calling `abort()` would set the requestState to COMPLETED, causing the IllegalStateException.

There should be no need to call `abort()` from the callback of failed writes, since failing the various callbacks should be enough, eventually failing the `HttpStream`, which would take care of tearing down the connection (HTTP/1) or the stream (HTTP/2+).

2024-02-23 12:56 UTC, gregw requested changes

2024-02-23 12:56 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SizeLimitHandler.java
> +                    String message = "Response body is too large: %d > %d".formatted(_written + content.remaining(), _responseLimit);
You put spaces around the > sign.  You need to fix the test to match

2024-02-23 14:32 UTC, sbordet commented
@gregw I reverted the renaming "aborted" -> "failed" because there are few public methods that are named abort* so felt weird to rename some (the private ones) but not others, so I kept "abort".

2024-02-26 14:50 UTC, gregw approved these changes

2024-02-26 16:27 UTC, merged