Issue #11361 - UriCompliance.checkUriCompliance improvements
eclipse/jetty.project pull request #11444
Opened 2024-02-23 16:20 UTC by joakime

Fixes: #11361

2024-02-26 14:40 UTC, gregw requested changes
Slight improvement in loop, but otherwise OK

2024-02-26 14:40 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +                if (uri.hasViolation(violation) && (compliance == null || !compliance.allows(violation)))
```suggestion
            for (UriCompliance.Violation violation : uri.getViolations())
            {
                if (compliance == null || !compliance.allows(violation))
```

2024-02-26 15:45 UTC, joakime commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +                if (uri.hasViolation(violation) && (compliance == null || !compliance.allows(violation)))
Done.

2024-02-27 12:31 UTC, gregw approved these changes

2024-02-27 12:32 UTC, merged