Allow resolve to return non-existent resources
eclipse/jetty.project pull request #11476
Opened 2024-03-01 09:29 UTC by gregw

Fix #11411 by allowing non-existent resources to be returned from resolve

2024-03-01 12:33 UTC, joakime commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java
> +     * @return an existing Resource representing the requested subUriPath, which may not {@link #exists() exist},
```suggestion
     * @return a Resource representing the requested subUriPath, which may not {@link #exists() exist},
```

2024-03-01 12:37 UTC, joakime commented
Are we going to need to reintroduce a bad resource impl? something like EmptyResource? or InvalidResource? that specific ResourceFactory implementations can use when it's known that the requested resource (be it from `newResource()` or `.resolve()`) can never be valid? (eg from URL Resource, specific PathResource schemes, mounted Resources, etc)

2024-03-01 14:43 UTC, gregw commented
> Are we going to need to reintroduce a bad resource impl? something like EmptyResource?

I'd prefer not.

There vaste bulk of calls use Resources method to check the return, so null first impossible and non exists for possible is ok.

I'll try to make this work this way.

2024-03-10 13:18 UTC, gregw commented
@janbartel

2024-03-11 17:33 UTC, gregw commented
@lorban @joakime nudge

2024-03-13 10:09 UTC, lorban commented
If my understanding is correct, this change would fix an API oddity:

`ResourceFactory.newResource("file:/this-directory-exists/this-file-does-not-exist")` returns a `PathResource` while `ResourceFactory.newResource("file:/this-directory-exists").resolve("this-file-does-not-exist")` returns null.

I think this is a good change, but that should be thoroughly reflected in our test suite as I'm sure methods like `Resource.copyTo(Path)` assume the resource exists.

(As a slightly unrelated note mostly to myself, `Resource` has many implementations expecting a `Path` that should probably be moved to `PathResource`, and I'm starting to think that `Resource.getPath()` was a mistake and should have been added only to `PathResource` and we should have used casts to `PathResource` where we know we can expect a `Resource` to be backed by a `Path`.)

2024-03-20 11:21 UTC, gregw commented
@lorban I think the test suite is pretty good for resources.  I have also walked through all the calls to resolve and checked that they are using something like `Resources.missing(r)` or equivalent.  There are still a few null checks, but they are mostly in servlet land, where we do convert non existent resources into null.

Do you have anything specific you want tested?

@joakime nudge

2024-03-20 13:25 UTC, lorban commented
@gregw `Resource.copyTo()` is poorly covered and has different behavior depending if the resource is backed by a path or not. Here is what I found so far:

 - If the resource is backed by a `Path` and is a regular file, `copyTo()` throws `UnsupportedOperationException: Unsupported copy option: ATOMIC_MOVE`.
 - If the resource is backed by a `Path` but does not exist, `copyTo()` trips on `assert isDirectory()`.
 - If the resource is a regular file:
   - If it is backed by a `Path`, `copyTo(directory)` creates or overwrites the file into the destination directory.
   - If it is NOT backed by a `Path`, `copyTo(file)` throws `FileSystemException: <target path>: Is a directory`.

I've already created https://github.com/jetty/jetty.project/pull/11493 regarding the 1st item, so maybe these extra tests and fixes should be taken care of in that PR too?

2024-03-20 14:15 UTC, gregw commented
@lorban How are these `copyTo` issues related to this PR about `resolve` ?  Can't they all be addressed in #11493

2024-03-20 14:24 UTC, lorban commented
That's not very related to this PR, so yeah, let's tackle those bugs in https://github.com/jetty/jetty.project/pull/11493

2024-03-20 14:25 UTC, lorban approved these changes

2024-03-20 15:07 UTC, gregw commented
@joakime I'd really like to get this merged soon, so it is not merged just before the next release.

2024-03-20 15:21 UTC, lorban requested changes
This needs to be fixed: if the resource is backed by a Path but does not exist, copyTo() trips on `assert isDirectory()`.

2024-03-20 17:24 UTC, joakime commented
> This needs to be fixed: if the resource is backed by a Path but does not exist, copyTo() trips on `assert isDirectory()`.

Looks like you have that covered in the new testing in PR #11493
Wouldn't that fix be enough?

2024-03-20 17:47 UTC, lorban commented
@joakime AFAICT it is not possible to create a `Resource` that does not exist without the changes of this PR, so this problem can only be triggered because of these changes. Or did I overlook something?

2024-03-20 17:55 UTC, joakime commented
> @joakime AFAICT it is not possible to create a `Resource` that does not exist without the changes of this PR, so this problem can only be triggered because of these changes. Or did I overlook something?

This PR introduce the ability to create a `Resource` that doesn't yet exist.
You got it right.

2024-03-20 18:14 UTC, lorban commented
@joakime thanks for the confirmation.
I pushed a fix for that bug as well as a new test for making sure all methods work on non-existent resources.

2024-03-21 05:38 UTC, gregw commented
@lorban I think you used the wrong checkstyle setup as it still fails.  I have fixed.

2024-03-21 11:02 UTC, lorban approved these changes

2024-03-21 12:49 UTC, merged