Replace ThreadLocal cache with ThreadIdCache
eclipse/jetty.project pull request #11504
Opened 2024-03-11 14:04 UTC by gregw

Use a cache class that will work better with virtual threads

2024-03-11 17:04 UTC, gregw commented
@lorban @sbordet I have now also replaced usages of `ThreadLocalRandom` with `ThreadIdCache.Random`, so we will not leak `Random` instances when using virtual threads.

For non-cache usages of `ThreadLocal`, we should look at changing the frequent pattern:
```java
    Object oldValue = threadLocal.get();
    try
    {
        threadLocal.set(newValue);
        // ...
    } 
    finally
    {
        threadLocal.set(oldValue);
    }
```

to be replaced with the pattern (probably with help of a utility method):
```java
    Object oldValue = threadLocal.get();
    try
    {
        threadLocal.set(newValue);
        // ...
    } 
    finally
    {
        if (oldValue == null)
            threadLocal.remove();
       else
            threadLocal.set(oldValue);
    }
```

or maybe even (@lorban is this worth the extra if?)

```java
    Object oldValue = threadLocal.get();
    try
    {
        threadLocal.set(newValue);
        // ...
    } 
    finally
    {
        if (oldValue == null && VirtualThreads.isVirtualThread())
            threadLocal.remove();
       else
            threadLocal.set(oldValue);
    }
```


thoughts?

2024-03-12 15:27 UTC, sbordet requested changes

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +        return 2 * ProcessorUtils.availableProcessors();
Prooooobably just the number of cores is right!

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +        if (capacity >= 0)
`capacity` cannot be 0.

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +    public int give(E e)
Rename to offer().

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +            if (_items.get(i) != null)
Consider using `getPlain()` or `getOpaque()` instead of get() that has volatile semantic.

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
> +        ReservedThread reserved = _threads.take();;
Double semi at EOL.

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +    public boolean take(E e, int index)
Rename to remove().

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +    public List<E> takeAll()
Rename to removeAll()

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +    public E get(Supplier<E> supplier)
Rename to takeOrElse().

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +public class ThreadIdCache<E> implements Dumpable
Rename to ThreadIdPool -- as every entry can be used only exclusively.

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +    public static class Random implements RandomGenerator
Remove, `ThreadLocalRandom` from JDK is enough.

2024-03-12 15:27 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ThreadIdCache.java
> +    public <A, R> R useWith(Supplier<E> supplier, BiFunction<E, A, R> function, A argument)
Rename to `apply()`, also above.

2024-03-12 16:24 UTC, merged

2024-03-12 16:25 UTC, gregw commented
I have merged this to #11498, where is can be further reviewed.