Allows to suppress "caused by" in error message, not only the stacks
eclipse/jetty.project pull request #11552
Opened 2024-03-22 07:44 UTC by dhs3000

Currently the error handler allows to suppress stack traces in the generated output. However, to easier circumvent [owasp | Improper Error Handling](https://owasp.org/www-community/Improper_Error_Handling) issues, I think it would be good to also suppress the "caused by" that includes the full exception class name.

(Currently I need to overwrite `ErrorHandler#generateResponse` and pass `null` for the `cause` parameter to achieve this.)

2024-03-26 08:13 UTC, gregw approved these changes, later dismissed
LGTM.  Just rebuilding to see if the CI failure was a flake

2024-03-26 08:20 UTC, dhs3000 commented
Forgot to send my comment earlier: As the default for `showStacks` is switched to `false` now, potentially the same should be done for the new `showCauses`?

2024-03-26 15:02 UTC, sbordet requested changes

2024-03-26 15:02 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
> +    boolean _showCauses = true;
Please make it default to `false`.

2024-03-27 07:23 UTC, dhs3000 commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
> +    boolean _showCauses = true;
I switched the default to false

2024-03-27 07:24 UTC, dhs3000 commented
@gregw @sbordet I updated the PR switching the default to false (going along the default for `showStacks`)

2024-03-27 07:33 UTC, gregw commented
You have a checkstyle failure:
```
[INFO] Starting audit...

[WARN] /home/jenkins/agent/workspace/jetty.project_PR-11552/jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java:523:5: 'METHOD_DEF' has more than 1 empty lines before. [EmptyLineSeparator]

Audit done.

[WARNING] src/test/java/org/eclipse/jetty/server/ErrorHandlerTest.java:[523,5] (whitespace) EmptyLineSeparator: 'METHOD_DEF' has more than 1 empty lines before.
```

2024-03-27 15:22 UTC, joakime commented
@dhs3000 you still have checkstyle issues.

Do this ...

```
mvn clean install -DskipTests -Pci 
```

This is a full build, without testing, using the same rules as CI.
It will show you the checkstyle issues on your command line.

2024-03-27 18:28 UTC, sbordet commented
I think we agree that the contribution is good and accepted, but there are test failures that check for the `ErrorHandler` output that is now suppressed by default.

If you don't mind, I'll take over as I think this is now on our court, rather than @dhs3000, who already provided a good PR.

2024-03-28 07:40 UTC, dhs3000 commented
I ran `mvn clean install -Dmaven.build.cache.enabled=false -DskipTests -Pci ` in `/jetty-core/jetty-server` (where I did changes)
```
[INFO] --- checkstyle:3.3.1:check (checkstyle-check) @ jetty-server ---
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
```

2024-03-28 07:43 UTC, dhs3000 commented
Thank you @sbordet. (`Allow edits by maintainers` is enabled on the PR, if that helps.)

2024-03-28 09:52 UTC, sbordet commented
See #11587.

2024-03-28 15:43 UTC, joakime commented
Replaced by PR #11587

2024-03-28 15:43 UTC, closed without merging