Issue #11579 - Reject Target in Request Path
eclipse/jetty.project pull request #11580
Opened 2024-03-27 14:44 UTC by joakime

Initial implementation of rejecting a URI Target in the Request Path.

2024-04-22 00:55 UTC, gregw commented
@joakime status?

2024-04-22 01:49 UTC, joakime commented
I haven't look at this in a while, since we moved it here from PR #11496
I'll update this PR this week.

2024-06-20 01:16 UTC, gregw requested changes
This is a placeholder review waiting for progress on this.  Please request re-review when it is ready.

2024-10-23 21:52 UTC, joakime commented
rebase against 12.1.x

2024-11-08 04:30 UTC, gregw requested changes
Let me have a go at this from the compliance end of things...

2024-11-08 04:30 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java
> +
I don't think we should not parse past the fragment etc.  We should parse to the end, but record a violation if there is a fragment.

2024-11-11 13:47 UTC, joakime commented
Closing in favor of PR #12504

2024-11-11 13:47 UTC, closed without merging