Customizable error page buffer size
eclipse/jetty.project pull request #11654
Opened 2024-04-15 23:59 UTC by dkaukov

Ability to increase buffer size past 8k in the custom `ErrorHandler`

2024-04-16 14:13 UTC, joakime commented
The HttpConfiguration is how you control the output buffer size.

What is the use case for this?

2024-04-16 22:14 UTC, dkaukov commented
True, but
```
    bufferSize = Math.min(8192, bufferSize); // TODO ?
```
limiting it to the 8k. We need a way to increase  the limit.

2024-04-17 12:05 UTC, joakime commented
> limiting it to the 8k. We need a way to increase the limit.

I understand that you want to increase the buffer size limit, but why?
What's the use case for a larger buffer size? (I ask, as there's probably several different ways to accomplish your use case without increasing this specific buffer size)

2024-04-18 07:03 UTC, dkaukov commented
Hi, In the 
```
@Override
protected void writeErrorHtml(Request request, Writer writer, Charset charset, int code, String message, Throwable cause, boolean showStacks) throws IOException {
  ....
}
```
we are generating custom error page using Writer. Something like:
```
  themeLeafTemplate.execute(writer, errorInfo);
```
If error page is bigger than buffer size it is just trimmed.

2024-04-18 10:35 UTC, joakime commented
Need to dig into why we are doing this via a static sized buffer.

I would like to see if this need can be accomplished via a Writer created with the Content.Sink features instead. (will try this in a different branch soon)

2024-05-20 22:48 UTC, dkaukov commented
Hi @joakime , maybe we can merge this one in a meantime?

2024-05-21 00:31 UTC, gregw commented
> Need to dig into why we are doing this via a static sized buffer.

I believe the reasoning is that we  don't want to get into complex responses when generating error pages, as if we are in an error state, we want simplicity.... otherwise we can get errors within errors within errors.....

I'll review this PR for merging now...

2024-05-21 00:36 UTC, gregw requested changes
This is OK.... but I think I'd prefer a simple `setBufferSize` method, with a -1 meaning that a heuristic will be used (e.g. min(8K, httpConfig.bufferSize)).  Default value will be -1 and `public int getBufferSize()` would return -1 (or the set value).  Then have a `protect int computeBufferSize(Request request)` that would check for -1 and do the min(8k, config.bufferSize) thang.

2024-05-21 00:36 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
> +        bufferSize = Math.min(8192, bufferSize); // TODO ?
Let's remove the TODO from the code

2024-05-21 00:36 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
> +    protected int getBufferSize(Request request)
We need a bit of javadoc to say that this is getting the buffer size for the entire error response (any larger responses will be truncated).   Then say that default implementation imposes an 8K limit on the standard buffer size, but that implementations may override the method to provide some other size.

2024-05-21 00:37 UTC, gregw commented
> This is OK.... but I think I'd prefer a simple `setBufferSize` method, with a -1 meaning that a heuristic will be used (e.g. min(8K, httpConfig.bufferSize)). Default value will be -1 and `public int getBufferSize()` would return -1 (or the set value). Then have a `protect int computeBufferSize(Request request)` that would check for -1 and do the min(8k, config.bufferSize) thang.

Note the reason I prefer a setter, is that it can be used from XML.

2024-05-23 03:50 UTC, dkaukov commented
@gregw Could you please take a  look now.

2024-05-23 07:15 UTC, gregw approved these changes, later dismissed
This looks good to me!

2024-05-23 07:15 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java
> +    int _bufferSize = -1;
Hmmm why are these fields not private?   Not a problem for this PR, but strange....

2024-05-23 07:16 UTC, gregw commented
CI failure is a flake.  rerunning

2024-07-31 01:05 UTC, janbartel commented
Re-running CI test again.

2024-08-29 22:32 UTC, gregw approved these changes

2024-08-29 22:32 UTC, gregw commented
Known CI flake

2024-08-29 22:33 UTC, merged

2024-08-29 22:43 UTC, gregw commented
@dkaukov thanks