Issue #11659 - Properly ignore OWS before `Content-Length` value.
eclipse/jetty.project pull request #11661
Opened 2024-04-17 16:37 UTC by joakime

Update `long convertContentLength(String valueString)` to properly ignore OWS and reject non-DIGIT characters.

2024-04-17 23:31 UTC, gregw requested changes
I think this is the wrong fix.  The parser itself is meant to skip OWS, so the convertContentLength method should never see any such characters.

We need to investigate why the state machine in parseFields is not working correctly rather than cover up the problem afterwards

2024-04-17 23:38 UTC, gregw commented
> I think this is the wrong fix. The parser itself is meant to skip OWS, so the convertContentLength method should never see any such characters.
> 
> We need to investigate why the state machine in parseFields is not working correctly rather than cover up the problem afterwards

The problem looks to be an issue with the handling of a cached header look ahead. investigating....

2024-04-17 23:43 UTC, gregw commented
It was broken by #10308...

2024-04-18 10:16 UTC, sbordet commented
@gregw `HttpField` null values were treated inconsistently, meaning that in 95% of the places they were assumed to be non-null and used without a null guard, possibly leading to NPEs.

Since it was the majority of the cases, and HTTP really does not have any meaning for a null value (it can only be the empty string), the change was made.

I think it would be better to change `HttpParser` as it is more of a private class (`HttpField` is exposed to applications, and we don't really want users to create an `HttpField` with a `null` value).

2024-04-18 12:28 UTC, gregw commented
@joakime perhaps it would be best to create the cache with a special sentinel value for the header only cases so that value not set can be distinguished from a empty string value.

2024-04-18 15:04 UTC, joakime commented
@gregw @sbordet this is updated per your reviews.

* reverted the changes to `convertContentLength`
* implemented changes to CACHE and parseFields to handle OWS properly for all UNMATCHED_VALUE headers.
* added 3 new OWS test cases (that fail in `12.0.x` HEAD btw) to handle this OWS case.

2024-04-18 21:22 UTC, gregw approved these changes

2024-04-19 01:33 UTC, merged