Addendum to #11566.
eclipse/jetty.project pull request #11722
Opened 2024-04-30 15:35 UTC by sbordet

Restored methods that were removed in WebAppClassLoader.Context.

Fixed method signatures for deprecated method -- they must take the deprecated ClassMatcher, not the newly introduced one.

2024-04-30 16:56 UTC, joakime commented
Test failures, all in ee8 layer

2024-05-01 02:04 UTC, gregw requested changes
I like the work in core/EE10,  but I think we should leave EE8/EE9 as much as possible with the old naming in the APIs and just use the new names in the implementation.

2024-05-01 02:04 UTC, gregw commented on jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-proxy-webapp/src/test/java/org/eclipse/jetty/ee9/demos/ProxyWebAppTest.java
The intention was to not do the public API renaming in EE8/EE9 APIs. i.e. leave as system/server rather than change to protected/hidden.    The new vocab will appear to some extent in ClassMatchers returned from the APIs, but there is no need to add it to the EE8/EE9 APIs if they were not already there.

2024-05-01 18:24 UTC, sbordet commented on jetty-ee9/jetty-ee9-demos/jetty-ee9-demo-proxy-webapp/src/test/java/org/eclipse/jetty/ee9/demos/ProxyWebAppTest.java
Done.
I have un-deprecated ee9's `ClassMatcher` because it is used in every non-deprecated APIs (since ee9 does not have the new APIs, the old APIs cannot be deprecated, and so ee9's `ClassMatcher` should also not deprecated).

2024-05-01 23:35 UTC, gregw approved these changes
LGTM.
Re-running CI to see if the failures are flakes.

2024-05-02 15:40 UTC, merged

2024-05-02 15:46 UTC, joakime commented
This is still broken.

```
2024-05-02 11:43:37.351:WARN :oejx.XmlConfiguration:main: Config error java.lang.IllegalStateException: No Method: <Call name="addServerClassMatcher"><Arg>|      <New class="org.eclipse.jetty.util.ClassMatcher"><Arg>|         <Array type="java.lang.String"><Item>-org.eclipse.jetty.util.Decorator</Item><Item>-org.eclipse.jetty.util.DecoratedObjectFactory</Item><Item>-org.eclipse.jetty.server.handler.ContextHandler.</Item><Item>-org.eclipse.jetty.server.handler.ContextHandler</Item><Item>-org.eclipse.jetty.ee10.servlet.ServletContextHandler</Item></Array>|        </Arg></New>|    </Arg></Call> on class org.eclipse.jetty.ee10.maven.plugin.MavenWebAppContext at <Call name="addServerClassMatcher"><Arg>|      <New class="org.eclipse.jetty.util.ClassMatcher"><Arg>|         <Array type="java.lang.String"><Item>-org.eclipse.jetty.util.Decorator</Item><Item>-org.eclipse.jetty.util.DecoratedObjectFactory</Item><Item>-org.eclipse.jetty.server.handler.ContextHandler.</Item><Item>-org.eclipse.jetty.server.handler.ContextHandler</Item><Item>-org.eclipse.jetty.ee10.servlet.ServletContextHandler</Item></Array>|        </Arg></New>|    </Arg></Call> in file:///home/joakim/code/jetty/12.0.x/jetty-ee10/jetty-ee10-maven-plugin/target/it/jetty-cdi-start-forked/src/main/jetty/jetty-context.xml
Exception in thread "main" java.lang.IllegalStateException: No Method: <Call name="addServerClassMatcher"><Arg>
      <New class="org.eclipse.jetty.util.ClassMatcher"><Arg>
         <Array type="java.lang.String"><Item>-org.eclipse.jetty.util.Decorator</Item><Item>-org.eclipse.jetty.util.DecoratedObjectFactory</Item><Item>-org.eclipse.jetty.server.handler.ContextHandler.</Item><Item>-org.eclipse.jetty.server.handler.ContextHandler</Item><Item>-org.eclipse.jetty.ee10.servlet.ServletContextHandler</Item></Array>
        </Arg></New>
    </Arg></Call> on class org.eclipse.jetty.ee10.maven.plugin.MavenWebAppContext
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:979)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:529)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:445)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:368)
	at org.eclipse.jetty.ee10.maven.plugin.WebAppPropertyConverter.fromProperties(WebAppPropertyConverter.java:301)
	at org.eclipse.jetty.ee10.maven.plugin.JettyEmbedder.applyWebAppProperties(JettyEmbedder.java:101)
	at org.eclipse.jetty.ee10.maven.plugin.JettyEmbedder.configureWebApp(JettyEmbedder.java:83)
	at org.eclipse.jetty.maven.AbstractJettyEmbedder.configure(AbstractJettyEmbedder.java:231)
	at org.eclipse.jetty.maven.AbstractJettyEmbedder.doStart(AbstractJettyEmbedder.java:204)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.maven.AbstractForkedChild.doStart(AbstractForkedChild.java:193)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.ee10.maven.plugin.JettyForkedChild.main(JettyForkedChild.java:69)
Caused by: java.lang.NoSuchMethodException: addServerClassMatcher
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:1014)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:971)
	... 12 more
```

2024-05-02 15:58 UTC, sbordet commented
Thanks, on it.