Moved BaseHolder and Source to core ee
eclipse/jetty.project pull request #11744
Opened 2024-05-03 03:20 UTC by gregw

This was a lot of work just to move 2 small classes to core.
We have to evaluate if the reduced duplication is worth the complexity of the split.

2024-05-03 04:25 UTC, janbartel requested changes
I'm in 2 minds about this: one the one hand it is nice to reduce code duplication, plus a lot of the changes are just mechanical and not substantive; but on the other hand it is a  PITA.

2024-05-03 04:25 UTC, janbartel commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHolder.java
> +public abstract class ServletContextHolder<T> extends BaseHolder<T>
I think this name is misleading: it is not holding a `ServletContext`. Not sure of what a better name might be? `ServletContextScopedHolder`?

2024-05-03 04:25 UTC, janbartel commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHolder.java
> +    @ManagedAttribute(value = "Display Name", readonly = true)
Can't all the methods from here on down be pushed down into `BaseHolder`? They're independent of the servlet spec version, and I don't think its important if they are not used by some of the derived classes.

2024-05-03 08:07 UTC, lorban reviewed
My feeling is -1 on this change.

IMHO the cost of this rather small code deduplication isn't worth the complexity of this change.

2024-05-08 23:41 UTC, gregw commented
I'll close this soon, but I'll first look through for any worthwhile cleanups in the PR.

2024-05-19 21:43 UTC, closed without merging