Fix Deprecated ClassMatcher #11767
eclipse/jetty.project pull request #11769
Opened 2024-05-08 23:34 UTC by gregw

Fix #11767 by making deprecated ClassMatcher class wrap the util ClassMatcher

2024-05-08 23:35 UTC, gregw commented
The constructor function is a little clumsy, but perhaps better than exposing the internals.

2024-05-09 13:46 UTC, joakime submitted a review, later dismissed
Looks good.  I also added some missing ee9 tests which are showing as green too.

2024-05-09 15:43 UTC, sbordet requested changes

2024-05-09 15:43 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ClassMatcher.java
> +    protected interface Constructor<T extends ClassMatcher>
I would deprecate already this interface.
When we remove the `eeN` versions of `ClassMatcher`, we want to remove this interface also, as it won't be necessary anymore.

2024-05-09 15:43 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ClassMatcher.java
> +    protected static <T extends ClassMatcher> T wrap(ClassMatcher matcher, Constructor<T> constructor)
Ditto re deprecation.

2024-05-09 15:43 UTC, sbordet commented on jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/ClassMatcher.java
> +    public static ClassMatcher wrap(org.eclipse.jetty.util.ClassMatcher matcher)
Can be package-private (just remove `public`).

2024-05-20 16:32 UTC, sbordet approved these changes

2024-05-21 00:42 UTC, merged