Fixes #11763 - Race condition in QoSHandler.
eclipse/jetty.project pull request #11772
Opened 2024-05-09 09:01 UTC by sbordet

Now using a read-write lock to atomically execute expire(). 
This guarantees that there are no races with resume().

The concurrency between handle() and resume(), which should be the most common case, is handled by concurrent data structures.

2024-05-09 14:02 UTC, lorban approved these changes, later dismissed

2024-05-13 07:18 UTC, gregw requested changes
I've found that if one synchronization mechanism doesn't prevent a race, then it is rarely fixed by adding yet another.     The use of read/write lock and an atomic is strange and a bit confusing.    I think I understand what it is doing, but at the very least it needs a lot more javadoc explaining the race and how this fixes it.

2024-05-13 07:18 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java
> +            int permits = state.decrementAndGet();
Mixing locks and atomics is pretty much an anti-pattern.  Would be good to just have an `int` here, but then you are modifying it within a read lock?

So at the very least, I'm confused by this code and it needs a lot more javadoc.  But ideally I'd like to see only a single synchronization mechanism, not two.

2024-05-13 07:30 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java
> +            int permits = state.decrementAndGet();
> Mixing locks and atomics is pretty much an anti-pattern.

Why? We have concurrent readers so we need atomics.

If we go with a full lock, then it's going to be more contended.

2024-05-13 10:09 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java
> +            int permits = state.decrementAndGet();
> Mixing locks and atomics is pretty much an anti-pattern.

Generally, yes. In this particular case, I think not. As a reminder, `ConcurrentPool` also mixes atomics and locks with a fast path/slow path pattern much like this proposed change.

2024-05-13 10:10 UTC, lorban approved these changes

2024-05-14 00:16 UTC, gregw approved these changes

2024-05-14 08:37 UTC, merged