Issue #11791 fix suffix mapping for non default DefaultServlet usage.
eclipse/jetty.project pull request #11799
Opened 2024-05-16 03:59 UTC by janbartel

Closes #11791

2024-05-16 06:50 UTC, gregw requested changes

2024-05-16 06:50 UTC, gregw commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
> +            return encodePath(path);
```suggestion
            String path = req.getPathInfo();
            if (StringUtil.isEmpty(path) && 
                MappingMatch.EXTENSION.equals(req.getHttpServletMapping().getMappingMatch()))
                path = req.getServletPath();
          
            return encodePath(path);
```

2024-05-17 08:27 UTC, lorban approved these changes

2024-05-19 22:35 UTC, gregw approved these changes

2024-05-22 08:44 UTC, Emilyserap commented
when this pull request will merge ?

2024-05-23 01:34 UTC, merged

2024-05-26 18:04 UTC, Emilyserap commented
Thanks for fixing this issue, but I want to know why when I refresh the dependencies, I don't see the new modification in the class DefaultServlet.java

2024-05-27 01:20 UTC, lachlan-roberts commented
@Emilyserap this is assigned to the `12.0.10` project, so you will need to wait for the release (which should be later this week), or you can build from the current `12.0.x` branch yourself.