Jetty 12.0.x xmlconfig prefers interfaces
eclipse/jetty.project pull request #11901
Opened 2024-06-11 01:07 UTC by janbartel

Fixes #11895.

Tentative fix to improve ordering of method matches so that:

* methods with fewer args are preferred
* methods with primitive args are preferred
* methods with non-varargs are preferred
* methods with class args (that are not the Object.class) are preferred
* methods with interface args or class args preference the most derived type

2024-10-23 21:52 UTC, joakime commented
@janbartel rebase against jetty-12.1.x

2024-10-24 05:06 UTC, gregw commented
I think this is a good change for 12.1,  I'm not so worried by this now (cue disaster!)

2024-10-29 20:22 UTC, gregw commented
@janbartel can you rebase this to 12.1, I think it is a good change to make.

2024-10-30 00:45 UTC, janbartel commented
Rebase done.

2024-10-30 02:35 UTC, gregw requested changes

2024-10-30 02:35 UTC, gregw commented on jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
> +    public static int compare(Class<?> t1, Class<?> t2)
private?

2024-10-30 02:35 UTC, gregw commented on jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
> +                    System.err.println("Invoking: " + method);
remove

2024-10-30 02:35 UTC, gregw commented on jetty-core/jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java
> +            "public int org.eclipse.jetty.xml.XmlConfigurationTest$FooObj.foo(java.lang.String)", //favour classes over interfaces
Can you add a `foo(CharSequence)` to the example, as `CharSequence` is an interface implemented by `String`

2024-10-31 02:28 UTC, gregw approved these changes
LGTM

2024-10-31 04:59 UTC, merged