Issue #12000 - use URIUtil::toURI instead of URI::create in MavenWebAppContext
eclipse/jetty.project pull request #12001
Opened 2024-07-03 19:23 UTC by joakime

Restore `URIUtil.toURI(String)`, properly javadoc it, and use it where end-user provided Strings are given.
Include maven-plugin IT test that replicates reported issue.

Fixes #12000

2024-07-03 20:25 UTC, gregw requested changes
I'm not in favour of resurrecting this method.  Use a ResourceFactory.  If that is difficult, then improve ResourceFactory.   Having a resource-factory-lite method handling user input is asking for trouble.    What if they give us a jar:file resource?

2024-07-03 20:25 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
> +     * <p>Convert a String into a URI in a sane way.</p>
you need to say it better than "in a sane way". what does that mean?

2024-07-03 20:25 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
> +     *     This exits to take an end user provided String and make a usable URI out of it.
No indent.
s/exits/exists/

2024-07-03 20:25 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java
> +     *     relative paths, absolute paths, and much more.
This still feels like a job of a `ResourceFactory`.  Why is this needed?

2024-07-03 20:25 UTC, gregw commented on jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/MavenWebAppContext.java
> +                .map(URIUtil::toURI)
ResourceFactory is the class we should be using to convert user provided strings. Especially as what we want is a CompositeResource at the end.

2024-07-04 07:14 UTC, janbartel commented
@joakime I made PR #12003 to fix the problem with the jetty maven plugin.

2024-07-05 00:57 UTC, janbartel commented
@joakime oops, when I committed my PR #12003 I think it closed the associated issue.

2024-07-09 00:51 UTC, janbartel commented
@joakime I think we've addressed the issue with PR #12003 so I'll close this PR. If there's still work to do, we need a new issue for it.

2024-07-09 00:51 UTC, closed without merging