Fix NPE when GzipHandler is writing and an exception is thrown by the wrapping's Response.write()
eclipse/jetty.project pull request #12025
Opened 2024-07-10 10:16 UTC by lorban

`GzipBufferCB` does not set the `GZState` to `FINISHED` when it fails, which leaves the code trying to finish up gzipping while everything has already been cleaned up.

Fixes #12022

2024-07-10 17:04 UTC, sbordet requested changes

2024-07-10 17:04 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
> +                _state.set(GZState.FINISHED);
Not needed, the caller is calling `cleanup()` when the state is already FINISHED.

2024-07-10 17:04 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
> +                _state.set(GZState.FINISHED);
cleanup() and onCompleteFailure() are remarkably similar, but why onCompleteFailure() is not releasing `_buffer`?

Can at least the code about `_deflaterEntry` be factored out between the 2 methods?

Also please move field `_buffer` to `GzipBufferCB` where it belongs.

2024-07-10 17:04 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/gzip/GzipHandlerTest.java
> +    public static class StacklessException extends RuntimeException
Can you use `StacklessLogging` instead?

2024-07-10 20:48 UTC, gregw submitted a review, later dismissed

2024-07-10 20:48 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
> +                _state.set(GZState.FINISHED);
it feels like this method should be call from onComplete.... method(s) rather than from processing

2024-07-11 16:25 UTC, lorban commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/gzip/GzipHandlerTest.java
> +    public static class StacklessException extends RuntimeException
Done.

2024-07-11 16:29 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
> +                _state.set(GZState.FINISHED);
Done.

2024-07-11 16:30 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java
> +                _state.set(GZState.FINISHED);
I moved the `cleanup()` call to `onCompleteSuccess()`, so its only called by `onCompleteSuccess()` and `onCompleteFailure()`, which is indeed a bit cleaner.

2024-07-12 00:03 UTC, gregw commented
@lorban something looks broken in this now.

2024-07-12 08:02 UTC, sbordet approved these changes, later dismissed

2024-07-12 09:16 UTC, lorban commented
I've reverted most of the suggested cleanups because they break the logic in subtle ways: `cleanup` cannot be called from `onCompleteSuccess` and the RBB cannot be scoped at the `GzipBufferCB` level because the data in the buffer's lifecycle is longer than the callback's lifecycle.

2024-07-16 07:29 UTC, sbordet approved these changes

2024-07-16 13:38 UTC, merged