Remove usage of a SecurityManager from EE11
eclipse/jetty.project pull request #12032
Opened 2024-07-11 23:58 UTC by gregw

Remove usage of a SecurityManager from EE11 
and disable by default all other usages.

2024-07-12 00:46 UTC, janbartel requested changes
Do we need to deprecate or otherwise get rid of `PrivilegedThreadFactory`?

2024-07-12 00:46 UTC, janbartel commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java
> +    @Deprecated(forRemoval = true, since = "12.0.0")
Not really 12.0.0? More like 12.0.12?

2024-07-12 00:46 UTC, janbartel commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java
> +    @Deprecated(forRemoval = true, since = "12.0.0")
See above

2024-07-12 00:58 UTC, gregw commented
> Do we need to deprecate or otherwise get rid of `PrivilegedThreadFactory`?

It is kind of internal, so we can get rid of it once there are no more JVMs with SecurityManagers without deprecation I think

2024-07-14 23:25 UTC, janbartel approved these changes

2024-07-15 03:32 UTC, merged