Improved handling of 100 Continue
eclipse/jetty.project pull request #12113
Opened 2024-07-31 13:23 UTC by sbordet

* Now `HttpClient` removed the `Expect` header if there is no request content.
* Changed AbstractProxyServlet and ProxyHandler check for request content: now the Content-Type header is not taken into consideration.
* Now the server avoids sending the 100 Continue response if there is no request content.

2024-07-31 21:06 UTC, gregw requested changes, later dismissed

2024-07-31 21:06 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                    if (_request.getLength() == 0)
This is not a sufficient test to check if a request has content.  Need to also check content-encoding at least.  See https://datatracker.ietf.org/doc/html/rfc9112#name-message-body-length.   Like `hasContent` in `AbstractProxyServlet`

Also would it not be better to not set `_expects100Continue` to `true` if there is no content?

2024-08-01 07:11 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                    if (_request.getLength() == 0)
@sbordet Perhaps to the check for a body in org.eclipse.jetty.http.MetaData.Request#is100ContinueExpected or org.eclipse.jetty.server.internal.HttpChannelState#onRequest?

2024-08-01 12:18 UTC, joakime commented
Is the work here going to help the old 100-Continue issue with AsyncMiddleManServlet?

* #9758

2024-08-02 05:48 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                    if (_request.getLength() == 0)
Oh I think this is OK now because it is the inverse!

2024-08-02 06:02 UTC, gregw approved these changes, later dismissed
OK, but a couple of niggles.

2024-08-02 06:02 UTC, gregw commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java
> +        if (path.trim().isEmpty())
```suggestion
        if (StringUtil.isBlank(path))
```

2024-08-02 06:02 UTC, gregw commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java
> +            request.headers(h -> h.remove(HttpHeader.EXPECT));
technically you should just remove the 100-continue value from the Expect header, but as there are currently no other defined values, this is probably OK.

2024-08-02 06:02 UTC, gregw commented on jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/AbstractProxyServlet.java
> +    protected Runnable onContinue(HttpServletRequest clientRequest, Request proxyRequest)
A little javadoc explaining the return would be good, specifically that null makes it optional

2024-08-02 14:02 UTC, sbordet commented
@gregw I fixed the niggles in #12111. Not a big fan of `StringUtil` when I can use JDK methods.

@joakime the work here does not address #9758, which I will look at separately.

2024-08-02 18:28 UTC, firoj0 reviewed
Git

2024-08-02 18:29 UTC, firoj0 approved these changes

2024-08-02 21:41 UTC, gregw commented
> @gregw I fixed the niggles in #12111. Not a big fan of `StringUtil` when I can use JDK methods.
> 

In this case, the StringUtil method avoids an allocation and is much clearer to read

2024-08-07 17:56 UTC, lorban approved these changes, later dismissed

2024-08-12 12:14 UTC, garydgregory commented
Hi All,

Would you please set expectations as to next steps? Are we waiting on a review from @gregw ?

TY!

2024-08-13 09:17 UTC, sbordet commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java
> +            request.headers(h -> h.remove(HttpHeader.EXPECT));
Correct. And we don't have an easy API in `HttpFields` to remove a single value.

2024-08-13 10:22 UTC, lorban requested changes

2024-08-13 10:22 UTC, lorban commented on jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServletTest.java
Shouldn't these tests be ported to ee9 too?

2024-08-13 10:30 UTC, sbordet commented
@garydgregory this PR is almost ready to be merged in, we won't wait for @gregw (currently in vacation).

It will be in the next Jetty 12 release, due end of month.

2024-08-13 10:30 UTC, sbordet commented on jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ProxyServletTest.java
Done.

2024-08-13 11:10 UTC, lorban approved these changes

2024-08-13 13:06 UTC, merged