Fixes #12122 - NPE in HttpReceiver.responseContentAvailable().
eclipse/jetty.project pull request #12123
Opened 2024-08-01 14:51 UTC by sbordet

Now also the HttpReceiver.responseContentAvailable() is serialized, so that the access to `this.contentSource` is serialized with failure, and protected by a call to `exchange.isResponseCompleteOrTerminated()`.

Before, it was possible that a thread failed the response, nulling out `this.contentSource`, while another thread was just about to call `responseContentAvailable()` -- this was the case for HTTP/2 in particular, where content is notified asynchronously, rather than being created by a call to `ContentSource.read()`.

2024-08-01 18:07 UTC, wendigo commented
@sbordet can you stage artifacts for me to test?

2024-08-01 18:43 UTC, firoj0 reviewed
qureshifiroj88@gmail.com

2024-08-01 18:43 UTC, firoj0 commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
>       */
All India Truck

2024-08-01 18:43 UTC, firoj0 commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
>      {
All India Truck}

2024-08-01 18:43 UTC, firoj0 commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
>                  LOG.debug("onDataAvailable on {}", this);
- [ ] qureshifiroj88@gmail.com

2024-08-01 18:43 UTC, firoj0 commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
> +                LOG.debug("Invoking demand callback {} on {}", demandCallback, this);
qureshifiroj88@gmail.com

2024-08-01 18:48 UTC, firoj0 commented
Firoj07

2024-08-03 18:50 UTC, wendigo commented
I can confirm that this change fixes the issue that we've seen in our benchmarks while running with HTTP/2

2024-08-06 09:12 UTC, lorban requested changes

2024-08-06 09:12 UTC, lorban commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
> +    protected void responseContentAvailable()
Shouldn't this method be private?

2024-08-07 07:26 UTC, sbordet commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
> +    protected void responseContentAvailable()
No, it is called from other places when it's known that there is no need to serialize.

2024-08-07 08:34 UTC, lorban approved these changes, later dismissed

2024-08-07 08:41 UTC, lorban approved these changes

2024-08-07 16:30 UTC, merged