Fixes #12154 - Limit concurrent virtual threads.
eclipse/jetty.project pull request #12155
Opened 2024-08-10 14:32 UTC by sbordet

Updated VirtualThreadPool to limit the number of concurrent virtual threads using a Semaphore.

Updated modules and documentation.

2024-08-10 22:20 UTC, gregw commented
@sbordet can we make this do if anybody configures the limit to less than 10000 it does "warning: just use normal threads. The emperor is indeed naked!"

2024-08-10 22:41 UTC, sbordet commented
@gregw sure, but I think you meant "less than a million" 🤣

2024-08-18 23:42 UTC, gregw requested changes

2024-08-18 23:42 UTC, gregw commented on jetty-core/jetty-server/src/main/config/modules/threadpool-all-virtual.mod
> +## Maximum number of concurrent virtual threads.
I don't think "concurrent" is correct or necessary here.  It makes it sound like there could be a lot more virtual threads, but only a limited number concurrently executing (which is a factor of cores and/or native threads).
```suggestion
## Maximum number of live virtual threads.
```

2024-08-18 23:42 UTC, gregw commented on jetty-core/jetty-server/src/main/config/modules/threadpool-all-virtual.mod
> +#jetty.threadPool.maxThreads=200
200?!?!?!?  aren't you missing a few orders of magnitude here?   Nobody should be using virtual threads (and risking all sorts of bad behaviour) at 200 threads... maybe 2,000, but better 20,000
```suggestion
#jetty.threadPool.maxThreads=20000
```

2024-08-18 23:42 UTC, gregw commented on jetty-core/jetty-server/src/main/config/modules/threadpool-virtual.mod
> +#jetty.threadPool.virtual.maxThreads=200
```suggestion
#jetty.threadPool.virtual.maxThreads=20000
```

2024-08-18 23:42 UTC, gregw commented on jetty-core/jetty-server/src/main/config/modules/threadpool-virtual.mod
> +#jetty.threadPool.virtual.maxThreads=200
Why is this `jetty.threadPool.virtual.maxThreads` here and `jetty.threadPool.maxThreads` in `threadpool-all-virtual.mod`

2024-08-20 08:39 UTC, gregw submitted a review, later dismissed

2024-08-21 08:44 UTC, merged