fix npe when onCompleteFailure happens after reset
eclipse/jetty.project pull request #12199
Opened 2024-08-26 12:18 UTC by lorban

Potential fix for https://github.com/jetty/jetty.project/issues/11841#issuecomment-2305847563

2024-08-26 16:39 UTC, sbordet approved these changes, later dismissed

2024-08-27 15:30 UTC, garydgregory commented
Hello @lorban,

Thank you for working on this! 
Could the TLS failures be false positives?

2024-08-27 15:43 UTC, sbordet requested changes

2024-08-27 15:43 UTC, sbordet commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java
> +            contentSender = new ContentSender();
Don't think this is necessary... Why was it changed?

2024-08-27 15:47 UTC, sbordet commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpSender.java
> +            contentSender = new ContentSender();
Ah, because of the changes to reset().

2024-08-27 15:48 UTC, sbordet approved these changes, later dismissed

2024-08-28 09:28 UTC, lorban commented
@garydgregory unfortunately, they're not. As we cannot reproduce the NPE you reported, this is progressing very slowly as we have to be super careful while working on assumptions.

2024-08-28 12:09 UTC, garydgregory commented
> @garydgregory unfortunately, they're not. As we cannot reproduce the NPE you reported, this is progressing very slowly as we have to be super careful while working on assumptions.

@lorban 
TY for the update, I wish I had a better reproducer for you than my initial report in https://github.com/jetty/jetty.project/pull/11891! It seems "random".

2024-08-28 15:33 UTC, sbordet approved these changes

2024-08-28 17:43 UTC, merged

2024-08-28 18:15 UTC, garydgregory commented
TY @lorban !

I'll pull, build, and start using it locally.

2024-08-28 21:15 UTC, garydgregory commented
Hello @lorban 

Using git `commit ed1cadc449bfd711e7fb5d4d409e4eb57be9321b (HEAD -> jetty-12.0.x, origin/jetty-12.0.x, origin/HEAD)`, I just saw:
```java
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.client.transport.HttpExchange.getRequest()" because "exchange" is null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:707)
	at com.rs.seagull.httpmonitor.JettyHttpClientTests.testHttpMethod(JettyHttpClientTests.java:183)
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.client.transport.HttpExchange.getRequest()" because "exchange" is null
	at org.eclipse.jetty.client.transport.HttpSender$ContentSender.process(HttpSender.java:511)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:262)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:243)
	at org.eclipse.jetty.client.transport.HttpSender.send(HttpSender.java:85)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:86)
	at org.eclipse.jetty.client.transport.HttpChannel.send(HttpChannel.java:142)
	at org.eclipse.jetty.client.transport.HttpConnection.send(HttpConnection.java:112)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:379)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:168)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:444)
	at org.eclipse.jetty.client.transport.HttpDestination.process(HttpDestination.java:420)
	at org.eclipse.jetty.client.transport.HttpDestination.process(HttpDestination.java:375)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:358)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:352)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:329)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:308)
	at org.eclipse.jetty.client.transport.HttpRequest.sendAsync(HttpRequest.java:751)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:303)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:744)
	at org.eclipse.jetty.client.CompletableResponseListener.send(CompletableResponseListener.java:79)
	... 20 more
```

2024-08-29 14:24 UTC, lorban commented
@garydgregory could we please follow up this conversation on https://github.com/jetty/jetty.project/pull/12210?

2024-08-29 14:39 UTC, garydgregory commented
> @garydgregory could we please follow up this conversation on #12210?

👍