Fixes HttpClient Content.Source reads from arbitrary threads
eclipse/jetty.project pull request #12203
Opened 2024-08-26 17:06 UTC by sbordet

2024-08-27 10:46 UTC, lorban commented
Is that an alternative for the fix in #12143?

2024-08-27 10:48 UTC, lorban requested changes
I don't mind this change, as long as the `SerializedInvoker` assertions added in #12143 don't trip. So I think they should be added as part of this PR too.

2024-08-28 11:54 UTC, lorban requested changes
This is much cleaner than https://github.com/jetty/jetty.project/pull/12143. After modifying FCGI too, I can't insist enough that the `SerializedInvoker` assertions should be added too.

2024-08-28 11:54 UTC, lorban commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java
This class should have the `SerializedInvoker` assertions of https://github.com/jetty/jetty.project/pull/12143

2024-08-28 18:12 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        if (LOG.isDebugEnabled())
`else if` on the same line.

2024-08-28 18:12 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        if (LOG.isDebugEnabled())
Ditto.

2024-08-28 18:12 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        public NamedRunnable(Runnable delegate)
private

2024-08-28 18:12 UTC, sbordet commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        protected String deriveTaskName(Runnable task, Throwable stack)
private

2024-08-28 21:30 UTC, lorban commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        if (LOG.isDebugEnabled())
done.

2024-08-28 21:30 UTC, lorban commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        if (LOG.isDebugEnabled())
done.

2024-08-28 21:30 UTC, lorban commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        public NamedRunnable(Runnable delegate)
done.

2024-08-28 21:31 UTC, lorban commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/SerializedInvoker.java
> +        protected String deriveTaskName(Runnable task, Throwable stack)
done.

2024-08-29 13:56 UTC, lorban commented
@sbordet nudge

2024-08-30 09:58 UTC, lorban approved these changes

2024-08-30 10:01 UTC, merged