Fixes #12227 - Improve HttpConnection buffer recycling.
eclipse/jetty.project pull request #12237
Opened 2024-09-04 19:30 UTC by sbordet

Alternative to #12228.

In this PR, the responsibility to release the buffers is in 2 methods: onFillable() (called when network data is available, and to process the next request) and parseAndFillForContent() (called from Request.read()).

2024-09-04 21:00 UTC, gregw requested changes
I agree with the approach taken....  just now play whack-a-bug until it works

2024-09-04 21:00 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
> +                    releaseRequestBuffer();
I don't think you can release here, as we will loose bytes that would be transferred in a later `doUpgradeFrom`

2024-09-04 21:00 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
> +                        releaseRequestBuffer();
again, if the buffer is not empty, we need to hold until a later `doUpgradeFrom`

2024-09-04 21:00 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java
> +                    releaseRequestBuffer();
Add an assert to make it clear we know the buffer is empty here because parsing is fully consuming.
```suggestion
                    assert isRequestBufferEmpty();
                    releaseRequestBuffer();
```

2024-09-05 00:08 UTC, gregw commented
@sbordet I've been playing whack-a-bug with this, but getting closer....

2024-09-05 06:06 UTC, gregw commented
@sbordet `org.eclipse.jetty.test.client.transport.HttpClientIdleTimeoutTest#testRequestIdleTimeout` is currently failing because when it idle times out, `consumeAvailable` is called, which calls `parseAndFillForContent`, which makes the assumption that if it gets to content end state, then something will call `onFillable` to do the release.  But that is not the case because we are already in the failure mechanism and that is why `consumeAvailable` has been called.   So nothing releases the request buffer.

If I try to add a release in `consumeAvailable` or `parseAndFillForContent` then I get NPEs for the cases that think they do need to release the request buffer, but it has already been released.

2024-09-05 10:44 UTC, sbordet commented
@gregw I think the current handling is correct.

It is the test that does not complete the `Handler` callback, and the check for leaks is performed before the server stops.

I pushed a fix to the tests to complete the callback, and the tests locally pass for me.

2024-09-05 11:59 UTC, gregw requested changes

2024-09-05 11:59 UTC, gregw commented on jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java
> +        callback.failed(new TimeoutException());
I'm OK with changing this test to not break.....   but then we need to add a test that explicitly stops the server in all the possible states to check that we do not leak.

If we allow leaks when we stop, then all leak checking is pointless, as we only check leaks after stopping.

2024-09-05 12:31 UTC, gregw commented on jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java
> +        callback.failed(new TimeoutException());
I'm now convinced.  It is OK to "leak" if the contract for completing the callback.  It is not OK to leak if the server is stopped.

2024-09-05 12:31 UTC, gregw approved these changes

2024-09-06 04:11 UTC, merged