Fixes #12266 - InvocationType improvements and cleanups.
eclipse/jetty.project pull request #12299
Opened 2024-09-23 16:17 UTC by sbordet

* Removed usages of `AbstractConnection.getInvocationType()`.
* Changed HTTP server-side Connection implementations to use `AbstractConnection.fillInterested(Callback)` with a callback that specifies the `InvocationType`, derived from the `Server`, which derives it from the `Handler` chain.
* Changed client-side receivers to use `AbstractConnection.fillInterested(Callback)` with a callback that specifies the `InvocationType`, derived from the `HttpClientTransport`.
* Introduced `HttpClientTransport.getInvocationType(Connection)`, so that client applications can specify whether they block or not.
* Made sure client-side HTTP/2 and HTTP/3 return tasks with the proper `InvocationType` to be run by the `ExecutionStrategy` when calling application code.
* HTTP3StreamConnection now uses an `EITHER` fillable callback to possibly process streams in parallel.
* `QuicStreamEndPoint` now uses a task to invoke `FillInterest.fillable()`, rather than invoking it directly, therefore honoring the `InvocationType` of callback set by the `Connection` associated with the `QuicStreamEndPoint`.

2024-09-24 08:29 UTC, lorban requested changes

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpConnectionOverHTTP.java
> +        public InvocationType getInvocationType()
Shouldn't the `InvocationType` be precomputed in the constructor?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpConnectionOverFCGI.java
> +            return getHttpDestination().getHttpClient().getTransport().getInvocationType(delegate);
Shouldn't the `InvocationType` be precomputed in the constructor?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java
> +            return getConnector().getServer().getInvocationType();
Shouldn't the `InvocationType` be precomputed in the constructor?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpReceiverOverFCGI.java
> +    private void fillInterested(HttpConnectionOverFCGI httpConnection)
I find this helper confusing, inlining it would be clearer IMHO.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpConnectionOverHTTP.java
> +    void setFillInterest()
Now there is both `fillInterested()` and `setFillInterest()` methods, with no real explanation about which should be used when.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClientTransport.java
> +    public default Invocable.InvocationType getInvocationType(Connection connection)
Why is this flexibility needed?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpChannelOverHTTP2.java
> +            if (stream == null)
I'm wondering when would the stream be null here.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java
> +        return getHttpClient().getTransport().getInvocationType(this);
What is this delegation bringing?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java
> +        return getHttpChannel().getHttpConnection().getInvocationType();
This should probably be precomputed.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java
> +        session.dataConsumed(this, flowControlLength);
Why changing the ordering of when data is considered consumed? Especially since this change was not applied in `onPush()`.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/InterleavingTest.java
> +                logger.info("onDataAvailable {}", data);
This should be logged at debug level.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/TrailersTest.java
> +                System.err.println("SIMON: frame = " + frame);
Debug log?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/TrailersTest.java
> +                System.err.println("SIMON: data = " + data);
Debug log?

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java
> +        fillInterested(_readCallback);
I'm growing a feeling that this method should be removed and be replaced by `fillInterested(Callback callback)`.

2024-09-24 08:29 UTC, lorban commented on jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/VirtualThreadsTest.java
> +                Thread.sleep(500);
You could await that `queue` contains `"*-headers"` instead.

2024-09-24 08:30 UTC, lorban commented
It seems `org.eclipse.jetty.server.ServerConnectorHttpServerTest.testNonBlockingInvocationType()` is failing because of these changes.

2024-11-08 04:22 UTC, gregw commented
@sbordet status of this?

2024-11-08 10:09 UTC, sbordet commented
@gregw need to resume working on it, but necessary.

Should be re-thought after #12395.

2024-11-08 21:25 UTC, gregw requested changes
changes necessary as per comments above

2025-01-15 21:55 UTC, sbordet commented
Closing as replaced by #12551 and #12596.

2025-01-15 21:55 UTC, closed without merging