Issue #9980 - add additional codes for CustomRequestLog
eclipse/jetty.project pull request #12322
Opened 2024-09-27 06:59 UTC by lachlan-roberts

Adds the following options to the CustomRequestLog

```
%A                    - the Request authority (which might differ from the Host header).
%h                    - the Request scheme
%uri                  -  the entire Request HttpURI (including query)
%{q}uri               - the entire Request HttpURI (excluding query)
%{attributeName}attr  - a request attribute
```

Let me know if you can think of better codes for these.

closes #9980

2024-10-02 16:12 UTC, joakime commented
Can request scheme be `%S` instead?

2024-10-02 16:31 UTC, sbordet commented
I agree with @joakime as long as we have also `%{host}uri` and `%{port}uri`.

2024-10-09 11:07 UTC, lachlan-roberts commented
I have added the changes requested.

Note that there are now some duplicate codes:
```
%h - %{scheme}uri
%A - %{authority}uri
%U - %{path}uri
%q - %{query}uri
```

2024-10-11 15:09 UTC, joakime approved these changes, later dismissed

2024-10-14 16:22 UTC, sbordet requested changes
Just minor nits on the javadocs.

2024-10-14 16:22 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
> + * <dd>The authority of the request URI.</dd>
Please add also the format for `{host}uri` and `{port}uri`, as this javadoc ends up in the documentation as well.

2024-10-14 16:22 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
> + * <p>A request attribute.</p>
```suggestion
 * <p>The value of the request attribute with the given name.</p>
```

2024-10-15 08:13 UTC, sbordet approved these changes

2024-10-15 08:16 UTC, sbordet requested changes

2024-10-15 08:16 UTC, sbordet commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
> +        assertThat(log, is("8080"));
Cannot be `8080`, the server starts on a random port.

2024-10-15 11:51 UTC, lachlan-roberts commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java
> +        assertThat(log, is("8080"));
oops should have run locally first... fixed

2024-10-15 15:55 UTC, sbordet approved these changes

2024-10-21 10:08 UTC, merged