Issue #11358 - Add API to handle timeouts in WebSocket
eclipse/jetty.project pull request #12359
Opened 2024-10-09 12:43 UTC by lachlan-roberts

closes #11358

2024-10-10 12:25 UTC, lorban approved these changes
LGTM

2024-10-14 16:05 UTC, sbordet requested changes

2024-10-14 16:05 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java
> +        return closeConnection;
There is no need to override `onReadTimeout()` because overriding `onIdleTimeout()` is enough.
Overriding also `onReadTimeout()` would cause the new idle timeout listeners to be called twice.

2024-10-14 16:05 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/CoreSession.java
> +    void addTimeoutListener(Predicate<WebSocketTimeoutException> onTimeout);
Rename to `addIdleTimeoutListener()` to be consistent with other parts of the code.

2024-10-14 16:05 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java
> +    public boolean onTimeout(WebSocketTimeoutException timeoutException)
Make it package-private. Rename to `onIdleTimeout()`.

2024-10-14 16:05 UTC, sbordet commented on jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/Session.java
> +    void addTimeoutListener(Predicate<WebSocketTimeoutException> onTimeout);
Rename to `onIdleTimeoutListener()`.

2024-10-15 08:10 UTC, sbordet approved these changes

2024-10-15 11:52 UTC, merged