Allow headers size extend to maxRequestHeadersSize in http client
eclipse/jetty.project pull request #12439
Opened 2024-10-29 20:34 UTC by shaoxt

Fixes #12438 

Allow headers size extend to maxRequestHeadersSize in http client

2024-11-05 18:07 UTC, sbordet requested changes
Can you please:

1. Apply the review comments.
1. Rebase these changes against branch `jetty-12.1.x`, and squash them in just 1 commit.
2. Move the tests to `HttpClientTest` and actually call `setMaxRequestHeadersSize()` in the test so that we will test it is working.

I am probably make your changes part of a larger set of changes that improve the behavior of the current implementation.

Thanks!

2024-11-05 18:07 UTC, sbordet commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
> +    private int maxRequestHeadersSize = 32 * 1024;
This configuration is HTTP/1.1 specific.
Please move it to `HttpClientTransportOverHTTP`.

2024-11-05 18:07 UTC, sbordet commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
> +    public int getMaxRequestHeadersSize()
After moving this method to `HttpClientTransportOverHTTP`, please annotate it with:

```
    @ManagedAttribute("The maximum allowed size in bytes for the HTTP request headers")
    public int getMaxRequestHeadersSize()
```

2024-11-07 17:26 UTC, shaoxt commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
> +    private int maxRequestHeadersSize = 32 * 1024;
Thanks, moved.

2024-11-07 17:27 UTC, shaoxt commented on jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
> +    public int getMaxRequestHeadersSize()
Thanks, moved.

2024-11-07 18:11 UTC, shaoxt commented
Thanks for reviewing the PR.    Created a new PR for required changes 
https://github.com/jetty/jetty.project/pull/12499
For some reasons, the last commits I tried to squash them in 1 commit. but git said the commits from two different parents.

> Can you please:
> 
> 1. Apply the review comments.
> 2. Rebase these changes against branch `jetty-12.1.x`, and squash them in just 1 commit.
> 3. Move the tests to `HttpClientTest` and actually call `setMaxRequestHeadersSize()` in the test so that we will test it is working.
> 
> I am probably make your changes part of a larger set of changes that improve the behavior of the current implementation.
> 
> Thanks!

2024-11-07 18:11 UTC, closed without merging