Improve disabled test in ExternalFastCGIServerTest
eclipse/jetty.project pull request #12487
Opened 2024-11-06 05:32 UTC by janbartel

Change `@Disabled` to conditional disable for `ExternalFastCGIServerTest`.

2024-11-06 16:36 UTC, sbordet requested changes

2024-11-06 16:36 UTC, sbordet commented on jetty-core/jetty-fcgi/jetty-fcgi-server/src/test/java/org/eclipse/jetty/fcgi/server/ExternalFastCGIServerTest.java
> +    @EnabledIfSystemProperty(named = "external.fastcgi.port", matches = "[0-9][0-9][0-9][0-9]")
I don't understand this change?

Should not be enough to tag it?
Even if it is supposed to connect to `localhost:9000`, tagging it external would skip it.

```java
@Tag("external")
@Test
public void testExternalFastCGIServer()
```

2024-11-07 02:39 UTC, janbartel commented
@sbordet done, pls rereview

2024-11-07 20:41 UTC, sbordet approved these changes

2024-11-07 22:06 UTC, merged