Fix `HTTP2Test.testLargeRequestHeaders`
eclipse/jetty.project pull request #12536
Opened 2024-11-14 10:56 UTC by lorban

Make sure `ReadOnlyBufferException` is not thrown from read-only methods of `RetainableByteBuffer.Mutable.Wrapper`, even when the buffer is retained.

This fixes such failures: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-12.1.x-ee9-ResponseTest/1/tests/

2024-11-14 11:51 UTC, gregw approved these changes

2024-11-14 18:37 UTC, sbordet requested changes
Both isFull() and space() can be lifted into the non-mutable interface `RetainableByteBuffer`, since they are implemented in terms of methods that exist there.

They are getter methods only that do not mutate.

By doing that, you can call these methods without the need to be mutable, and this problem would go away.

2024-11-14 22:17 UTC, joakime commented
I'd like to see this fixed/merged soon, as it is breaking other 12.1.x PRs

https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-12531/5/tests

2024-11-15 00:55 UTC, janbartel approved these changes

2024-11-15 09:15 UTC, sbordet approved these changes

2024-11-15 09:16 UTC, merged