Improve `HttpOutput.print()`
eclipse/jetty.project pull request #12530
Opened 2024-11-13 10:04 UTC by lorban

This PR improves `HttpOutput.print()` by simplifying it, avoiding copies when needed and fixing a too early buffer release.

2024-11-13 10:05 UTC, lorban commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> -            out.release();
If the above `write()` call is async, `out.release()` may be called before the write is done.

2024-11-13 17:22 UTC, sbordet requested changes

2024-11-13 17:22 UTC, sbordet commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +        IORunnable r = eoln ? () -> write("\r\n".getBytes(StandardCharsets.UTF_8)) : null;
Use `ASCII` for `\r\n`.

The write of this IORunnable could remain pending, so you cannot notify callback until this write is complete.

2024-11-13 20:31 UTC, gregw requested changes

2024-11-13 20:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +            IORunnable copy = onComplete;
is `copy` the right name?  It confused me.    How about just `doOnComplete` or `runOnComplete`?

2024-11-13 20:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +                    IORunnable copy = onComplete;
ditto

2024-11-13 20:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +        IORunnable r = eoln ? () -> write("\r\n".getBytes(StandardCharsets.UTF_8)) : null;
Better yet, use `IO.CRLF_BYTES`

2024-11-13 20:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +        IORunnable r = eoln ? () -> write("\r\n".getBytes(StandardCharsets.UTF_8)) : null;
and call the variable `onComplete`

2025-01-07 21:54 UTC, joakime commented
@lorban might want to merge from base `jetty-12.1.x` on this PR, and then address the changes requested.

2025-01-08 10:48 UTC, lorban commented
@joakime I merged 12.1.x, but I'll resume working on this once the broken tests in https://github.com/jetty/jetty.project/pull/12635 are fixed.

2025-03-13 12:58 UTC, gregw commented
@lorban status report?

2025-03-13 14:16 UTC, lorban commented
@gregw this can now be resumed, so I'm going to refresh my mind then finalize it.

2025-03-19 17:56 UTC, sbordet approved these changes

2025-03-20 09:46 UTC, merged