Enhance HTTP Compliance CRLF modes
eclipse/jetty.project pull request #12564
Opened 2024-11-22 23:20 UTC by gregw

Added modes to allow strict requirement for CRLF termination of headers and/or chunks

2024-11-25 09:54 UTC, sbordet requested changes
1. What happens now if we have a request with mixed EOL, e.g. some are just \n, and some \r\n, still good and we have tests?
2. Please update the documentation about the compliance, defaulting to 9110 where now is 7230 in `programming-guide/server/compliance`.
3. This must be backported to 12.0.x, so I would rather rebase this PR on 12.0.x and then merge forward.

2024-11-25 09:54 UTC, sbordet commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCompliance.java
> +     * with no known violations.
There is 1 violation.

2024-11-25 09:54 UTC, sbordet commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCompliance.java
>       * with no known violations.
There are 2 violations.

2024-11-26 00:54 UTC, gregw commented
> 1. What happens now if we have a request with mixed EOL, e.g. some are just \n, and some \r\n, still good and we have tests?

If configured to accept LF EOL, then we accept a mix of LF and CRLF.    I guess we could have a semi strict mode that once you see a LF then any CRLF is an error... but that's not what the RFC says.   If you want to be strict, then just  accept CRLF only.

> 2. Please update the documentation about the compliance, defaulting to 9110 where now is 7230 in `programming-guide/server/compliance`.

Done.

> 3. This must be backported to 12.0.x, so I would rather rebase this PR on 12.0.x and then merge forward.

I'm not sure we need to backport.   There is no actual issue with jetty here and this is just tightening the compliance as a future proofing exercise.  Let's talk offline.

2024-11-28 21:05 UTC, sbordet approved these changes

2024-11-28 22:16 UTC, merged