Fix #12578 pretty print getParameterMap
eclipse/jetty.project pull request #12585
Opened 2024-11-26 22:58 UTC by gregw

Fix #12578 pretty print getParameterMap
Added test for parameters

2024-11-26 23:14 UTC, joakime submitted a review, later dismissed

2024-11-27 22:00 UTC, joakime requested changes, later dismissed
Can we have a `TypeUtil.toString(Map<String,String> map)` that does this? and have it used in both places?

2024-11-27 22:00 UTC, joakime commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java
> +                return sb.toString();
Can we have a single implementation, a static method somewhere in jetty-util that does this?
That way this location, and MultiMap can use the same one?

2024-11-28 22:57 UTC, janbartel approved these changes
Cool

2024-11-29 00:10 UTC, olamy approved these changes

2024-11-29 09:34 UTC, lorban approved these changes

2024-11-29 20:33 UTC, merged