Port ee9 `BlockingTest` to ee10 and ee11
eclipse/jetty.project pull request #12635
Opened 2024-12-12 15:11 UTC by lorban

Porting [ee9 BlockingTest](https://github.com/jetty/jetty.project/pull/12529) to ee10/11 seems to have uncovered some bugs.

On top of that, some bits of https://github.com/jetty/jetty.project/pull/12557 done in 12.0 are missing from 12.1, hence the changes in `ThreadPool`.

2025-01-09 10:34 UTC, lorban commented
@gregw @sbordet nudge

2025-01-24 06:31 UTC, gregw requested changes
I'm wondering if this should be an integration test rather than a duplicated unit test?

2025-01-24 06:31 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java
> +    public static String toString(Throwable x)
javadoc

2025-01-24 06:31 UTC, gregw commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java
> +        void fail()
This whole class lacks javadoc.

Rather than have n >= 3 copies of it, why not move to jetty-util and document properly

2025-01-24 06:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContentProducer.java
> +        void fail()
ditto ee10 comments

2025-01-24 06:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +                                content = aggregate.getByteBuffer();
Generally getting the ByteBuffer from the aggregate is an anti-pattern as we want to avoid unnecessary copies if the aggregate is internally retaining.

Can't the `content` be a RBB and that way you can use RBB.writeTo below?

2025-01-24 06:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +                                content = aggregate.getByteBuffer();
ditto

2025-01-24 06:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java
> +        catch (IllegalStateException ise)
this kind of conflicts with the comment above? please explain?

2025-01-24 06:31 UTC, gregw commented on jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/BlockingTest.java
Would it make more sense to convert tests like these into integration tests that would written as Servlets written to the Servlet 5.0 API.  We could then deploy them to EE9, EE10 and EE11 without duplicating the code.

2025-01-24 14:09 UTC, lorban commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +                                content = aggregate.getByteBuffer();
That can be done, and looking more closely at that code I think I figured what the problem is in https://github.com/jetty/jetty.project/issues/12721.

Let me change that.

2025-01-24 14:09 UTC, lorban commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java
> +                                content = aggregate.getByteBuffer();
ditto.

2025-01-24 14:11 UTC, lorban commented on jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/BlockingTest.java
That would make sense, much like creating a common code module for EE9/10/11 that we already discussed. But until then, duplicating this code is the only choice.

2025-01-24 14:11 UTC, lorban commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java
> +        catch (IllegalStateException ise)
You are right, the `IllegalStateException` should be ignored.

2025-01-24 14:12 UTC, lorban commented on jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContentProducer.java
> +        void fail()
Added javadoc.

2025-01-24 14:12 UTC, lorban commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java
> +    public static String toString(Throwable x)
Done.

2025-01-24 14:14 UTC, lorban commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java
> +        void fail()
Added javadoc.
Regarding the 3 copies, EE9 is slightly different but EE10/11 are indeed identical. But this class is very specific to the servlet input FSM so I'd rather move it to a module common between EE* versions rather than moving it to jetty-util as I seriously doubt that it can be reused.

2025-01-24 15:07 UTC, gregw approved these changes

2025-01-24 16:19 UTC, merged