Expand CustomRequestLog %u
eclipse/jetty.project pull request #4364
Opened 2019-11-26 16:24 UTC by cstamas

Add argument to invoke `request#getRemoteUser()`.

2019-11-26 16:29 UTC, joakime submitted a review, later dismissed
Seems fine to me.

2019-11-26 20:51 UTC, joakime commented
Your commits do not satisfy the Eclipse Legal requirement for a signed ECA. (See [details of commit checks](https://accounts.eclipse.org/legal/eca/validation/20175))
We are unable to merge without a signed ECA.
See https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md#eclipse-contributor-agreement

2019-11-26 23:23 UTC, lachlan-roberts requested changes
Thanks for your work on this, but it looks to me like `%{d}u` and `%{r}u` are semantically the same thing. So I don't think there is a need for both.

You can follow the implementation of `request.getRemoteUser()`, it gets the `Authentication` and authenticates if instance of `Authentication.Deferred`, it then gets the `UserPrincipal` name from that.

This is exactly the same as what the `CustomRequestLog` method `getAuthentication(request, true)` will do, which you should be able use with `%{d}u`.

2019-11-26 23:23 UTC, lachlan-roberts commented on jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
>                      method = "logRequestAuthentication";
The logic for the pre-existing code seems incorrect.
This should be something like:
```java
if (StringUtil.isEmpty(arg))
    method = "logRequestAuthentication";
else if ("d".equals(arg))
    method = "logRequestAuthenticationWithDeferred";
else
    throw new IllegalArgumentException("Invalid arg for %u: " + arg);
```

2019-12-05 06:06 UTC, lachlan-roberts commented
Closing and addressing these issues with the `%u` code in PR #4397.

2019-12-05 06:06 UTC, closed without merging

2019-12-07 17:23 UTC, cstamas commented
@lachlan-roberts Howdy, sorry for late response.

While I do agree somewhat with your, these were my concerns:
* I assumed (seems wrongly?) this is about a "jetty OOTB" access logger, given one of the most fav logging solution (logback access w/ Jetty support has a long outstanding issue https://jira.qos.ch/browse/LOGBACK-1052)
* Many frameworks (for example Shiro (wraps the request, hence while your code pointers stand for Jetty Request, that is clearly not the case for wrapped ones
* If this access logger is meant to be used is some special manner (ie. jetty-only), then it may need Javadoc update, or, some hint how to be used.

2019-12-09 22:57 UTC, lachlan-roberts commented
@cstamas this access logger will never see the wrapped request, it is given the jetty request directly so sees what goes over the wire and not any wrapped requests.

It is possible to configure to use Logback by using a `RequestLogWriter`, you could try using the `Slf4jRequestLogWriter` with the [Logback Implementation for Slf4j](http://logback.qos.ch/).

2019-12-09 23:03 UTC, cstamas commented
So, then it will see only auth that jetty knows about? Then it will not work for me.

2019-12-09 23:12 UTC, joakime commented
If you can set the authentication via `Request.setAuthentication(Authentication)` on the base Jetty `Request` object you might be able to get what you need.

2019-12-09 23:15 UTC, joakime commented
@lachlan-roberts perhaps the javadoc for `%u` should indicate that it's only for servlet auth.

2019-12-10 00:03 UTC, gregw commented
Perhaps set the custom auth as a request attribute and then that can be logged?