Fixes #3512 - File descriptor is not released after zip file uploaded…
eclipse/jetty.project pull request #4391
Opened 2019-12-03 10:38 UTC by sbordet

… via jetty-client.

In case of multiple parts only the last iterator was closed.
Now, every part's iterator is closed.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2019-12-03 23:07 UTC, gregw requested changes
I find the code rather confusing having to use generic Iterator and then have type checks for Closeable and Callback etc.    This is doubly confusing when the Iterator wraps another Iterator.

Would it be possible to replace the generic:
```java
  Iterator iterator = content.getIterator();
  ...
  if (iterator instanceof Closeable)
    ((Closeable)iterator).close();
``` 
with
```java
  MultipartIterator iterator = content.getMultipartIterator();
  ...
  iterator.close();
```
or something similar?

2019-12-03 23:27 UTC, sbordet commented
@gregw I'm not sure I understand where exactly you suggest to change the code - there is no `getIterator()` method anywhere.

The iterator is to iterate over the chunks of content.

`Closeable` is for those iterator implementations that open resources and must close them.
The close is driven from external code in case of other failures not related to the content itself (e.g. the application aborted).

This is a part of Jetty `HttpClient` that was born simple (too simple) and had to evolve with a few tricks that I don't particularly like but had to exist to maintain API compatibility.

2019-12-03 23:34 UTC, gregw commented
Sorry I meant `Iterator iterator = parts.iterator();` rather than `getIterator()`
So my question is can we used typed iterators rather than `instanceof` checks?   I would have thought so in some places at least as we are getting the iterator from Parts?

2019-12-03 23:37 UTC, sbordet commented
@gregw still not following. `Parts` is not an existing class. I only see `parts.iterator()` on the server.
Line number?

2019-12-03 23:50 UTC, gregw commented
OK then same thing with `ContentProvider`.  I've looked at a few implementation of that and they are pretty much all Closeable and Callbacks and have iterators that are also Closeable and Callbacks, so wouldn't it be better to have a `ContentProviderIterator` interface that was a Closeable Callback Iterator and avoid all the instanceof checks?

I'm not saying this must be done... No is an acceptable answer, but only if it is really the case that you will get arbitrary iterators that are not actually Closeable and/or Callbacks.  If all of them are (or almost all of them), then having a type rather than doing type logic would be a lot clearing.  It's just a bit confusing to follow the weakly typed code when there are so many Closeable/Callbacks that are not explicit.

2019-12-04 15:16 UTC, sbordet commented
@gregw see #3756 and #4400.

To answer your question, of the 8 concrete `ContentProvider` implementations:

* `ByteBufferContentProvider`, `BytesContentProvider` and `StringContentProvider` don't need anything special.
* `PathContentProvider` and `InputStreamContentProvider` need an `Iterator` that implements `Closeable`.
* `DeferredContentProvider` needs an `Iterator` that implements `Callback` and `Synchronizable`.
* `OutputStreamContentProvider` is a wrapper for `DeferredContentProvider`.
* `MultiPartContentProvider` is a composite of all the others, so needs all the features.

So about half needs "special" features, but the other half does not.

To sum up, I think for 9.4.x we need to live with the current status of things and "sniff" whether `Iterator`s implement `Callback` or `Closeable` etc.
For 10.0.x we may review all this and make it better.

2019-12-06 20:36 UTC, gregw approved these changes

2019-12-07 11:38 UTC, merged