Issue #4495 ReservedThreadExecutor optimise
eclipse/jetty.project pull request #4499
Opened 2020-01-20 12:08 UTC by gregw

Use synchronousQueue for task handoff for #4495 

Signed-off-by: Greg Wilkins <gregw@webtide.com>

2020-01-24 13:01 UTC, sbordet reviewed
I would hold this until we have results from the 2 clients that are trying these changes.

2020-01-24 13:14 UTC, gregw commented
it also would need the alternative implementations removed before merging.

2020-01-31 12:22 UTC, gregw commented
@sbordet nudge

2020-01-31 12:36 UTC, sbordet requested changes

2020-01-31 12:36 UTC, sbordet commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
> +            catch (InterruptedException e)
Better catch `Throwable` here.

2020-01-31 12:36 UTC, sbordet commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
> +                    Runnable task = _idleTime == 0 ? _task.take() : _task.poll(_idleTime, _idleTimeUnit);
Should be `_idleTime <= 0`.

2020-01-31 12:36 UTC, sbordet commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/ReservedThreadExecutor.java
> +                    if (task != null)
There was a `LOG.debug()` statement when we had a non-null `task` that I would like to keep.

2020-01-31 17:39 UTC, gregw commented
@sbordet nudge

2020-01-31 18:36 UTC, sbordet approved these changes

2020-01-31 18:54 UTC, merged