Fixes #4577 IPAccessHandler in context
eclipse/jetty.project pull request #4580
Opened 2020-02-17 07:14 UTC by gregw

Fixes and tests #4577 IPAccessHandler in context by using target instead of pathInfo for path matching.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

2020-02-17 07:23 UTC, gregw commented
The behaviour is il defined if this handler is within a context and a named dispatch is done.   As t his is a deprecated handler, I am not inclined to define this behaviour.

2020-02-21 07:30 UTC, sbordet commented
Class `IPAccessHandler` is deprecated, but lacks the `@Deprecated` annotation, can you please add it?

2020-02-21 07:39 UTC, sbordet requested changes
@gregw I'm surprised that the functionality of matching the URI that we have here is missing from `InetAccessHandler`. 
Do we have it elsewhere, also considering this class has been removed from Jetty 10?

2020-02-21 07:39 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/handler/IPAccessHandlerTest.java
> +        try
Use try-with-resources for the Socket.

2020-02-21 07:39 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/handler/IPAccessHandlerTest.java
> +    @BeforeEach
Now that you have changed the test annotation to be per-instance, all fields should not be `static`: `_server`, `_connector`, `_handler`.

2020-02-21 19:38 UTC, gregw commented
Looking at the commit comments for InetAccessHandler, they suggest that URI mapping was intended to be added eventually.   I'll open a new issue to track it.

2020-02-24 09:56 UTC, sbordet approved these changes

2020-02-25 07:46 UTC, merged