Issue #4628 - Ensuring checkEnabledModules is required dependency aware
eclipse/jetty.project pull request #4633
Opened 2020-03-03 19:52 UTC by joakime

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

2020-03-09 09:33 UTC, gregw requested changes
I don't think this is necessary as the required dependency mechanism duplicates the existing `[optional]` mechanism and should be reverted.

2020-03-09 11:14 UTC, gregw commented
As explained in #4628, the issue I have with these PRs is that `Required` is the wrong adjective for this mechanism.   `Conditional` is much better, even if currently the only condition we can apply is existence.  Can this PR be used to fix the naming as well as making checkEnabledModules aware of conditional dependencies.

2020-03-19 09:09 UTC, sbordet commented
@gregw I have addressed your naming concern, can you please re-review?

2020-03-19 10:11 UTC, sbordet approved these changes

2020-03-23 09:15 UTC, gregw approved these changes

2020-03-31 09:10 UTC, merged