Issue #4727 setConfigurationDiscovered true per default
eclipse/jetty.project pull request #4732
Opened 2020-03-31 04:06 UTC by olamy

2020-03-31 12:15 UTC, janbartel requested changes
The jetty documentation on Annotations needs to be updated to include the Configuration.setConfigurationDiscovered(boolean) method, and the fact that it will default to TRUE for even 2.5 webapps.

2020-04-01 08:21 UTC, janbartel approved these changes
LGTM with a slight wording change.

2020-04-01 08:21 UTC, janbartel commented on jetty-documentation/src/main/asciidoc/distribution-guide/annotations/using-annotations.adoc
> +Users wishing to not use `ServletContainerInitializers` from within the webapp with older versions of `web.xml` must call `WebAppContext.setConfigurationDiscovered(false)` either programmatically or
Actually it's not just SCIs, it is also @WebServlet, @WebFilter, @WebListener @MultiPart etc etc. So maybe phrase this as:
"Users wishing not to use annotations from the webapp classpath must call ...."

2020-04-01 11:44 UTC, joakime approved these changes
LGTM, just need to work out why the build failed.

2020-04-02 02:38 UTC, merged