Issue #4770 - Deprecate GzipTester
eclipse/jetty.project pull request #4779
Opened 2020-04-15 17:32 UTC by joakime

+ Renamed TestDirContentServlet to AbstractFileContentServlet
+ Renamed various TestServlet*Write classes to BlockingServlet*Write to better
  represent their purpose.
+ Renamed TestServletBufferTypeLengthWrite to HttpOutputWriteFileContentServlet
+ Cleaned up GzipContentLengthTest to be one big ParameterizedTest
  - now does Internal vs External GzipHandler testing too.
+ Introduced AbstractGzipTest to house simple common methods
+ Cleanup remaining testcases

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

2020-04-20 20:00 UTC, sbordet commented
@joakime a ton of test failures, can you please check?

2020-04-20 21:40 UTC, joakime commented
taking a look

2020-04-22 17:28 UTC, joakime commented
@sbordet the build is clean on this PR now

2020-05-03 20:12 UTC, sbordet requested changes

2020-05-03 20:12 UTC, sbordet commented on jetty-servlets/src/test/java/org/eclipse/jetty/servlets/AbstractGzipTest.java
> +    }
Remove `static`  block -- just do `DEFAULT_OUTPUT_BUFFER_SIZE = new HttpConfiguration().getOutputBufferSize()`

2020-05-03 20:12 UTC, sbordet commented on jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipDefaultServletDeferredContentTypeTest.java
> +     */
Why it's all commented out?

2020-05-03 20:12 UTC, sbordet commented on jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipContentLengthTest.java
> +        // TODO: compare bytes
Fix TODOs?

2020-05-04 14:25 UTC, joakime commented on jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipDefaultServletDeferredContentTypeTest.java
> +     */
I need to fix this one.

2020-05-04 14:26 UTC, joakime commented on jetty-servlets/src/test/java/org/eclipse/jetty/servlets/GzipContentLengthTest.java
> +        // TODO: compare bytes
I'll address these

2020-05-04 17:59 UTC, joakime commented
@sbordet Updated 3 test classes based on your review.
This branch / PR is now green on CI.

2020-05-05 13:48 UTC, sbordet approved these changes

2020-05-05 14:54 UTC, merged