Workarounds for old (pre API 24) Android SDKs
eclipse/jetty.project pull request #4811
Opened 2020-04-24 16:13 UTC by joakime

There's a number of SSL/TLS related API calls that we use in Jetty 9.2.x that are not available in older versions of Android.

These are a set of workarounds to not crash when those APIs are not present in the JVM runtime.

2020-04-24 16:16 UTC, joakime commented
This is strictly for Jetty 9.2.x branch.
If PR is approved, these changes will not be merged into newer versions of Jetty.

2020-04-27 08:16 UTC, sbordet requested changes
Apart the renaming, LGTM, but please do the renaming.

2020-04-27 08:16 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
> +    private SSLSession getOptionalHandshakeSession()
Just call it `getHandshakeSession()`.

2020-04-27 14:03 UTC, joakime commented
@sbordet I made the change, but I also ...

* Created an issue for this: Issue #4819 
* Rebased all 3 commits into one to make tracking of this change easier in git. (and used new Issue number in resulting commit)
* Forced push (with lease) the changes to this branch.

Once I get a confirmed green build from CI It should be ready to merge.

2020-04-28 07:22 UTC, sbordet approved these changes

2020-04-28 16:31 UTC, merged