Fixes #4808 - Review HttpClient Request header APIs.
eclipse/jetty.project pull request #4845
Opened 2020-05-04 21:17 UTC by sbordet

Introduced:
* Request Request.headers(Consumer<HttpFields.Mutable>).
This allows applications to modify the headers, and chain calls.
It also delegates the precise semantic of put/add/remove/clear to HttpFields, so there is no API duplication.
* HttpRequest.header(HttpField) to efficiently add fields while normalizing the request (only used in implementation).

* HttpResponse.header(HttpField) to efficiently add fields while parsing the response (only used in implementation).
This pairs with HttpResponse.trailer(HttpField).
* HttpResponse.headers(Consumer<HttpFields.Mutable>) to modify the fields after they have been populated (only used in tests).

Removed:
* Request.[set,add,put,remove], replaced by headers(Consumer<HttpFields.Mutable>).

Deprecated:
* Request.header(String, String)
* Request.header(HttpHeader, String)
Both replaced by headers(Consumer<HttpFields.Mutable>) with clearer semantic for add/put/remove.

All the rest is code cleanup to remove the usage of the deprecated header() methods.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2020-05-06 08:07 UTC, lorban requested changes
I really like the overall idea of concentrating all the HTTP field modification API into a single class, but it should be pushed to its full extent then: only have one single way to mutate HTTP fields: the lambda-taking mutating method `headers()`.

This would have the extra bonus of making it cheap to extend the API with nice helper method (`addIfAbsent`, `addIfNotNull`...) that would make calling the lambda-taking mutating method very elegant to use.

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
> +            if (!newRequest.getHeaders().contains(field))
My senses tell me that adding a new `HttpFields.Mutable.addIfAbsent()` API and calling it with `newRequest.headers(header -> header.addIfAbsent(field))` would be preferable to the old style `if (!contains) add()`.

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java
> +            request.header(getHttpDestination().getHostField());
Aren't you calling a method that is supposed to be deprecated?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java
> +                    request.header(new HttpField.LongValueHttpField(HttpHeader.CONTENT_LENGTH, contentLength));
Aren't you calling a method that is supposed to be deprecated?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java
> +                request.header(cookieField);
Aren't you calling a method that is supposed to be deprecated?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java
> +            response.header(field);
Aren't you calling a method that is supposed to be deprecated?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
>      public Request header(String name, String value)
Shouldn't this method be marked as `@Deprecated`?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
> +    public HttpRequest header(HttpField header)
Shouldn't this method be marked as `@Deprecated`?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpResponse.java
> +    public HttpResponse header(HttpField header)
Shouldn't this method be marked as `@Deprecated`?

2020-05-06 08:07 UTC, lorban commented on jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java
> +            proxyRequest.headers(headers -> headers.add(HttpHeader.X_FORWARDED_HOST, hostHeader));
I wonder if adding a `HttpFields.Mutable.addIfNotNull()` helper method wouldn't be worth it as there would only be a single call to `proxyRequest.headers()` with all the mutations chained in a single shot.

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put("X-Some-Custom-Header", "some-value")));
Shouldn't you combine the above two calls to `headers()` into a single one?
```
.headers(headers -> headers.put(HttpHeader.CONTENT_TYPE, "application/json")
    .put("X-Some-Custom-Header", "some-value"));
```

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put("X-Some-Other-Custom-Header", "some-other-value")));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.add("x-same-name", "value2")));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put(HttpHeader.CONTENT_TYPE, "application/json")));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put("X-Custom-Header-2", "value2")));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put("Content-Type", "application/json")));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put("X-Custom-Header-2", "value")));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ForwardProxyTLSServerTest.java
> +                .headers(headers -> headers.put(HttpHeader.CONTENT_LENGTH, String.valueOf(contentLength)))
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ForwardProxyTLSServerTest.java
> +                .headers(headers -> headers.put(HttpHeader.CONTENT_LENGTH, String.valueOf(body2.length())))
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java
> +            request.headers(headers -> headers.add("Cookie", "JSESSIONID=4422")); //does exist
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java
> +            request.headers(headers -> headers.add("Cookie", "JSESSIONID=2233")); //is invalid
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:07 UTC, lorban commented on tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java
> +            request.headers(headers -> headers.add("Cookie", "JSESSIONID=5678"));
Shouldn't you combine the above calls to headers() into a single one?

2020-05-06 08:12 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java
> +            request.header(getHttpDestination().getHostField());
No, as this one is only in `HttpRequest` and takes a field, as described in the initial PR comment, to save the lambda allocation.

2020-05-06 08:13 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java
>      public Request header(String name, String value)
No, the interface one is deprecated. I don't think you should deprecate the whole hierarchy.

2020-05-06 08:15 UTC, sbordet commented on jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientTest.java
> +            .headers(headers -> headers.put("X-Some-Custom-Header", "some-value")));
I could, but I also want to chain the calls to `headers(Consumer)` to show that it is possible.
I chain the calls to `HttpFields` elsewhere, so it's not a big deal -- these are only tests.

2020-05-06 15:06 UTC, joakime commented
Is the new `headers()` lambda applied after the `Request.Content` based content-types are applied?
Or in fact after any "default" headers are added?

That would allow someone to remove/change a header that is added by other processes in the request before it's sent.

2020-05-06 15:07 UTC, joakime commented
Will you update the client documentation in a future commit?

2020-05-06 16:25 UTC, sbordet commented
@joakime the lambda is invoke immediately.
What client documentation needs to be updated? The code snippets already are.

2020-05-08 15:35 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java
> +            if (!newRequest.getHeaders().contains(field))
See #4859.

2020-05-08 15:47 UTC, sbordet commented on jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java
> +            proxyRequest.headers(headers -> headers.add(HttpHeader.X_FORWARDED_HOST, hostHeader));
See #4859.

2020-05-08 15:51 UTC, lorban approved these changes
LGTM

2020-05-08 15:52 UTC, merged