Issue #4888 - Request getSession() now returns existing cached session if found
eclipse/jetty.project pull request #4889
Opened 2020-05-19 12:38 UTC by cshannon

Instead of logging and exception and returning null, if an existing
Session is found in the session cache when attempting to add a new
session then the existing session is used instead and returned

2020-05-19 12:44 UTC, cshannon commented
I'm not sure why it's saying I'm not covered by the ECA as I signed it yesterday

2020-07-22 19:57 UTC, joakime commented
Since @janbartel marked this as "do not merge" , i've downgraded this from a formal PR to a draft PR until her questions are answered.

2020-07-22 19:58 UTC, joakime commented
Note: we are close to having a 9.4.31 release (next week or two), so if you want to see this change in 9.4.31, I would advise you to resolve the unresolved questions that @janbartel has.

2020-09-01 07:28 UTC, gregw requested changes
This definitely feels like treating the symptom and not the cause.  Let's put this on hold until we understand the issue more.

2020-09-02 10:09 UTC, janbartel commented
@cshannon I've just committed a change with PR #5220 which I think might resolve your issue also. So I'm going to close this PR for now. If you can retest with HEAD of jetty-9.4 and confirm if that resolves your problem over on issue #4888 that would be great.

2020-09-02 10:09 UTC, closed without merging

2020-09-02 10:24 UTC, cshannon commented
@janbartel - Thanks a lot, I will give it a shot but I think you are right that this will fix the issue. I have been running a custom build for a while now to fix it for myself but I'm glad that some others were able to report back a test case to demonstrate.