Issue #4741 No Servlet Path
eclipse/jetty.project pull request #4898
Opened 2020-05-20 20:47 UTC by gregw

This completes the refactoring started in #4851 for #4741, by using
the HttpServletMapping field to avoid having the servletPath field
in the Request and instead have a pathInContext field.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

2020-05-25 12:59 UTC, gregw commented
@janbartel @sbordet @lachlan-roberts This is ready for review now.  The CI failure was a flaky one.... rebuilding.

The substance of this change is to avoid the request holding:
```java
   Context context;
   String contextPath;
   String servletPath;
   String pathInfo;
   HttpServletMapping mapping;
```

This has been reduced to 
```java
   Context context;
   String contextPath;
   String pathInContext;
   HttpServletMapping mapping;
```

The mapping itself provides the servletPath and pathInfo (with those being pre-computed for exact and root matches).  
Previously, while there was no context set, the pathInfo was equal to the pathInContext.  Now we just return pathInContext
for the pathInfo when there is no context, but we keep the pathInContext as that can be generally useful and reduces the times
we have to do `pathInContext = addPaths(servletPath, pathInfo)`.

It would have been really nice if we could have reduced down to:
```java
   Context context;
   String pathInContext;
   HttpServletMapping mapping;
```
and just got the context path from the Context object.... but with cross context includes possible (0.0000001% of cases), the contextPath can be for the source context and the context the actual context.   I'm wondering if we should just wrap the context in that case????... but that would be another PR.

2020-05-26 08:25 UTC, lachlan-roberts submitted a review, later dismissed
LGTM

2020-05-26 09:08 UTC, janbartel submitted a review, later dismissed
I'm not in love with the method name setContextPaths(String,String) because of the getContextPath() method (ie returns a singular path), but I can't really think of a better one .... setPaths(String,String)??? ... setContextualPaths(String,String)???? They all suck to some degree. Other than that minor quibble, LGTM.

2020-05-26 09:11 UTC, gregw commented
I don't like the `setContextPaths(String,String)` setter either - neither the name nor the double barrelled set.
However, if I go ahead and do the context wrapping to get rid of the contextPath field, then this method will change anyway.... so I'm kind of OK with it as I'm keen to do the next PR anyway.

2020-05-26 12:10 UTC, gregw commented
@janbartel @lachlan-roberts thanks for the reviews... but looking at it I decided I didn't want to merge with the TODOs and contextPath.  I thought of a neat way to support the cross context include 0.000001% without wrapping, so I've done another commit.    I'll dismiss your reviews so you can review the last commit.

2020-05-26 12:54 UTC, gregw commented
Moved back to a draft as Jan suggested offline a more uniform approach.

2020-05-27 09:52 UTC, gregw commented
@janbartel @sbordet @lachlan-roberts more javadoc added

2020-05-27 11:54 UTC, janbartel commented
@gregw you need to merge from jetty-10.0.x

2020-05-27 15:01 UTC, joakime commented
Don't forget to set the Project on PRs

2020-05-28 07:42 UTC, sbordet requested changes
LGTM, but fix the snake_case.

2020-05-28 07:42 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Dispatcher.java
> +        final ServletPathMapping old_mapping = baseRequest.getServletPathMapping();
All these variable names should break CheckStyle, we don't use snake_case.

2020-05-28 07:42 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Dispatcher.java
> +        final ServletPathMapping source_mapping = baseRequest.findServletPathMapping();
Don't use snake_case in variable names.

2020-05-28 07:50 UTC, sbordet approved these changes

2020-05-28 10:17 UTC, merged