Issue #4907 - close websocket suspendState if close frame is received
eclipse/jetty.project pull request #4912
Opened 2020-05-27 00:19 UTC by lachlan-roberts

**Closes #4907**

Fixes flaky test `SuspendResumeTest.testSuspendAfterClose()`.

If a close frame is received we must close the suspend state so any subsequent calls to `suspend()` and `resume()` will throw `IllegalStateException`.

The transition to the close state must be done both when receiving a close frame before the `WebSocketFrameListener` is called, and in the case when we never received a close frame but the connection has been closed.

2020-06-03 01:45 UTC, lachlan-roberts commented
@gregw nudge

2020-06-10 08:18 UTC, gregw requested changes
avoid double lock

2020-06-10 08:18 UTC, gregw commented on jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
> +            synchronized (this)
We have just synchronized above, so can this check and change be done in that block?

2020-07-01 12:32 UTC, lachlan-roberts commented
@gregw nudge

2020-07-01 21:42 UTC, gregw approved these changes

2020-07-06 02:54 UTC, merged