Issue #4572 Implemented TAG_PAD
eclipse/jetty.project pull request #4994
Opened 2020-06-24 12:54 UTC by gregw

Implemented the TAG_PAD configuration for jetty log appender.

There was a half implementation for thread name padding, but that is not sufficient to align the log output.  Tag padding works on the combined thread and logger name.

2020-06-24 14:00 UTC, joakime requested changes
Not quite right.
Naming of this configuration is the big one for me.
The implementation could be simpler too.
And there's no need for `@deprecated` here (we are still in alpha/beta phase)

2020-06-24 14:00 UTC, joakime commented on jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java
> +    static final String TAG_PAD_KEY = "org.eclipse.jetty.logging.appender.TAG_PAD";
This needs a better name.
TAG is meaningless and vague.
THREAD isn't what this is about either.

2020-06-24 14:00 UTC, joakime commented on jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java
> +            this.tagPadding = b.toString();
The entire else branch can be ...
``` java
this.tagPadding = " ".repeat(padding);
```

2020-06-24 14:00 UTC, joakime commented on jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java
> +    static final String TAG_PAD_KEY = "org.eclipse.jetty.logging.appender.TAG_PAD";
If this were instead a name that indicated the tab stop of where the "message" portion of the log output should begin, then the logic below gets simpler.

Example

``` java
package text;

public class TabStopDemo
{
    public static void main(String[] args)
    {
        String padding = " ".repeat(20);
        System.out.printf("[%s]%n", padding);

        int tabStop = 10;
        tabStopTest(tabStop, "hello", "friend");
        tabStopTest(tabStop, "my name is", "inigo montoya");
        tabStopTest(tabStop, "you killed my father", "prepare to die");
    }

    private static void tabStopTest(int tabStop, String start, String message)
    {
        StringBuilder builder = new StringBuilder();
        builder.append(start);
        int padHere = tabStop - builder.length();
        if(padHere > 0)
            builder.append(" ".repeat(padHere));
        else
            builder.append(' ');
        builder.append(message);
        System.out.println(builder);
    }
}
```

2020-06-24 14:00 UTC, joakime commented on jetty-slf4j-impl/src/test/java/org/eclipse/jetty/logging/JettyLoggerTest.java
> +        Properties props = new Properties();
Would have preferred a new test method, not polluting the existing one.
This new mutated test method is testing too many things now.

2020-06-24 15:57 UTC, joakime commented
I created PR #4997 as an alternate approach for this.

2020-06-25 09:59 UTC, gregw commented
Closed in favour of #4997

2020-06-25 09:59 UTC, closed without merging