Issue #5018 - add request timeout onto ClientUpgradeRequest
eclipse/jetty.project pull request #5024
Opened 2020-07-04 02:23 UTC by lachlan-roberts

**Issue #5018** 

Add setter and getter for request timeout on the `ClientUpgradeRequest` in the same style as the methods on`org.eclipse.jetty.client.api.Request`.

2020-07-06 07:45 UTC, sbordet requested changes
@lachlan-roberts please add a test case.

2020-07-07 10:42 UTC, sbordet approved these changes
Please fix what detailed in the comments, but otherwise LGTM.

2020-07-07 10:42 UTC, sbordet commented on jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientTimeoutTest.java
> +        ExecutionException executionException = assertThrows(ExecutionException.class, () -> connect.get(timeout + 200, TimeUnit.MILLISECONDS));
Use `2 * timeout` to wait - if all good we are still waiting just `timeout`, but at least we won't have unexpected failures when 200 ms is too short of a margin.

2020-07-07 10:42 UTC, sbordet commented on jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/client/ClientTimeoutTest.java
> +        ExecutionException executionException = assertThrows(ExecutionException.class, () -> connect.get(timeout + 200, TimeUnit.MILLISECONDS));
Ditto.

2020-07-07 10:42 UTC, sbordet commented on jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java
> +    public ClientUpgradeRequest timeout(long timeout, TimeUnit unit)
To be consistent with other methods of this class, this should be `void setTimeout(long, TimeUnit).

2020-07-07 16:00 UTC, sbordet approved these changes

2020-07-07 16:19 UTC, joakime commented
Tests failed.

```
Parallel Stage / Build / Test - JDK11 / testAsyncRest – org.eclipse.jetty.tests.distribution.DemoBaseTests
org.opentest4j.AssertionFailedError: expected: <200> but was: <500>
	at org.eclipse.jetty.tests.distribution.DemoBaseTests.testAsyncRest(DemoBaseTests.java:106)
```

Probably as a result of the following ...

```
2020-07-07 12:36:31.177:INFO:oejtd.DistributionTester:ConsoleStreamer/STDERR: 2020-07-07 12:36:31.176:WARN:oejs.HttpChannel:qtp373182087-17: 
  handleException /async-rest/testSerial java.io.IOException: Server returned HTTP response code: 400 for URL: 
  http://open.api.ebay.com/shopping?MaxEntries=3&appid=Webtide81-adf4-4f0a-ad58-d91e41bbe85&version=573&siteid=0&callname=FindItems&responseencoding=JSON&QueryKeywords=gnome
```

2020-07-08 06:36 UTC, lachlan-roberts commented
@joakime the failure is unrelated to the changes in this PR, I re-ran and it passed the tests.
Going ahead with the merge.

2020-07-08 06:36 UTC, merged