Issue #4824 - add configuration on RemoteEndpoint for maxOutgoingFrames
eclipse/jetty.project pull request #5059
Opened 2020-07-17 03:53 UTC by lachlan-roberts

Attempt to address issue #4824 at the Jetty WebSocket API level.

If there are more than `maxOutgoingFrames` waiting to send, any additional sends will fail immediately instead of continuing to queue up in the flusher. The callback will be failed immediately but it will not fail the entire ws connection.

This method is called `maxOutgoingFrames` but its not really as the implementation could later on decide to fragment each send from the `WebSocketRemoteEndpoint` into multiple frames.

2020-07-17 03:55 UTC, lachlan-roberts commented
Maybe it would be better if instead we monitor how many frames are queued at a lower level and if this is exceeded we simply just fail the entire connection.

2020-07-30 16:01 UTC, joakime commented
I can see the value in this, and I'm good with this implementation.
But I'm wondering if there's can be a better way to accomplish this.

@gregw @sbordet thoughts?

2020-09-01 11:27 UTC, joakime commented
@lachlan-roberts i think this PR needs a refresh / merge from `jetty-9.4.x`

2020-09-02 09:20 UTC, sbordet requested changes
Please add a test that shows that `maxOutgoingFrames` is respected.

2020-09-02 09:20 UTC, sbordet commented on jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketRemoteEndpoint.java
> +                callback.writeFailed(new IOException("Exceeded max outgoing frames: " + outgoingFrames + ">" + maxNumOutgoingFrames));
Please change the exception from `IOException` to `WritePendingException`.

2020-09-04 07:28 UTC, sbordet approved these changes
LGTM - just improve the javadocs.

2020-09-04 07:28 UTC, sbordet commented on jetty-websocket/websocket-api/src/main/java/org/eclipse/jetty/websocket/api/RemoteEndpoint.java
> +     * queued to be sent by the implementation.
Please add some text that explains what happens if the limit is exceeded.
What operation will get what exception, etc.

2020-09-07 13:32 UTC, sbordet approved these changes

2020-09-10 00:51 UTC, merged