#5150 - Infinite connection timeout support in ManagedSelector
eclipse/jetty.project pull request #5151
Opened 2020-08-13 13:37 UTC by olegmoz

Closes #5150 
`ManagedSelector` never timeouts connection in case connection timeout is set to zero.

2020-08-13 13:46 UTC, joakime commented
Thank you for the pull request.

But we need to satisfy the requirements of Eclipse Legal in order to accept / merge this pull request.

The Eclipse Foundation ECA validation has failed for the commits on this pull request.

See the "Details" link on the `eclipsefdn/eca` check to know what you have failed to do.

See also https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md#eclipse-contributor-agreement

2020-08-13 14:37 UTC, olegmoz commented
@joakime thanks, I have signed-off the commit

2020-08-13 14:46 UTC, joakime approved these changes
LGTM.

@sbordet you should review this too.

2020-08-13 15:40 UTC, sbordet requested changes
Can you please update the javadocs for `HttpClient.setConnectionTimeout()` and `HttpClient.getConnectTimeout()`, adding that the value `0` means infinite timeout?
Other than that looks good.

2020-08-13 15:40 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java
> +            final long timeout = ManagedSelector.this._selectorManager.getConnectTimeout();
Please remove `final`, not necessary.

2020-08-13 18:26 UTC, olegmoz commented
@sbordet thanks, removed `final` and updated the javadocs. Please review

2020-08-14 16:32 UTC, sbordet approved these changes

2020-08-14 16:32 UTC, merged