Backdown default version of asm to 7.
eclipse/jetty.project pull request #5478
Opened 2020-10-19 22:08 UTC by janbartel

Backing down the default version of asm from 9 to 7. This default version value is only used in the case where we cannot determine the actual version of the asm jars at runtime.

2020-10-19 22:13 UTC, gregw approved these changes

2020-10-20 06:11 UTC, gregw requested changes
Actually I think we should just pass 7 as the version of the API we have extended.
I'm not sure why we are doing the dynamics anyway?  @sbordet Do you recall why we wrote this manifest inspection code?

2020-10-20 07:24 UTC, gregw commented
@olamy Were the CI failures on this spurious?

2020-10-20 07:59 UTC, janbartel commented
@sbordet do you know about changes to the proxy stuff that would have caused this CI failure?

2020-10-20 10:29 UTC, olamy commented
sadly spurious... next run should be ok. This test sometimes fail where there is plenty of build in parallel

2020-10-20 11:33 UTC, gregw commented
Replaced by #5479

2020-10-20 11:33 UTC, closed without merging