9.4.x 5603 single page doc
eclipse/jetty.project pull request #5636
Opened 2020-11-10 15:41 UTC by WalkerWatch

Creates single page output for 9.4.x documentation and aligns with 10 and 11 documentation formatting.

2020-11-10 19:43 UTC, jmcc0nn3ll commented
If we are going to wack out the docbook backend entirely we should clear out the xslt files, basically the src/main/docbkx-*  directories.  Might be good to go through and make sure none of that is referenced but I think that stuff was mostly just syntax highlighter and font type stuff.

2020-11-10 19:43 UTC, jmcc0nn3ll requested changes
See prior comment.

2020-11-16 09:36 UTC, sbordet requested changes
I ran the documentation generation, and I get a ton of warnings and errors.

In particular, all source code blocks for XML are broken, so the generated documentation is unreadable.

Remove `subs={sub-order}` from everywhere, it's now broken, it's unnecessary in most cases, and should be explicitly added only in blocks that require it.

The "parts" use level 0 sections, should be using level 1 (see warning during generation).

There is also a number of invalid cross references that should be fixed.

2020-11-16 09:36 UTC, sbordet commented on jetty-documentation/pom.xml
> +        <version>1.5.7.1</version>
No.
The version should be inherited from the root pom, which is already at 2.1.0.

2020-11-16 09:36 UTC, sbordet commented on jetty-documentation/pom.xml
> +        </dependencies>
No. Asciidoctor dependencies should be declared in the root pom, so we keep the versions of those dependencies up-to-date as well.

2020-11-17 15:00 UTC, sbordet requested changes

2020-11-17 15:00 UTC, sbordet commented on jetty-documentation/src/main/asciidoc/administration/alpn/alpn.adoc
> +[source, plain, ]
Ah, no: the last comma must be removed as well. I know it renders without issues, but it's not good as it looks like there is something missing.

2020-11-17 20:14 UTC, WalkerWatch commented on jetty-documentation/src/main/asciidoc/administration/alpn/alpn.adoc
> +[source, plain, ]
Yeah, I thought about this after I committed. Fixing now.

2020-11-18 16:43 UTC, jmcc0nn3ll approved these changes

2020-11-18 16:45 UTC, jmcc0nn3ll commented
As long as this visually looks fine I am good to go with it, it lets us get the updated website leveraging it so we can deploy that going into the 10 and 11 releases.  Any content changes we need to make can be done separately.

2020-11-20 15:59 UTC, WalkerWatch commented
@sbordet Any other changes you'd like to see?

2020-11-20 16:40 UTC, sbordet commented on jetty-documentation/src/main/asciidoc/administration/http2/configuring-haproxy.adoc
> +[source, ,]
Fix this.

2020-11-20 16:40 UTC, sbordet commented on jetty-documentation/src/main/asciidoc/configuring/security/configuring-form-size.adoc
> +[source,shell,]
Fix this.

2020-11-20 16:40 UTC, sbordet commented on jetty-documentation/src/main/asciidoc/configuring/security/configuring-form-size.adoc
> +[source,java,]
Fix this.

2020-11-20 16:40 UTC, sbordet commented on jetty-documentation/src/main/asciidoc/configuring/security/configuring-form-size.adoc
> +[source,java,]
Fix this.

2020-11-20 16:40 UTC, sbordet commented on jetty-documentation/src/main/asciidoc/quick-start/getting-started/jetty-running.adoc
> +[source,screen,]
Fix this.

2020-11-20 16:57 UTC, WalkerWatch commented
@sbordet Done, not sure how I managed to miss those. CI Building now. Good to go when green?

2020-11-20 16:57 UTC, sbordet approved these changes

2020-11-20 18:59 UTC, sbordet approved these changes

2020-11-20 19:05 UTC, merged