Fixes #3080 - Do not create and use jars with "tests" classifier.
eclipse/jetty.project pull request #5729
Opened 2020-11-25 18:19 UTC by sbordet

Removed the jetty-server and jetty-servlet test-jar artifacts.
The only one left is the jetty-maven-plugin test-jar.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2020-11-25 19:06 UTC, joakime requested changes
`ServletTester` is used by many projects, and several open source projects.
We cannot get rid of it.

Move it to another location, don't delete it.

2020-11-26 09:58 UTC, gregw commented on jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletTester.java
> + * <p>ServletTester should not be used.</p>
Perhaps say:
```suggestion
 * <p>ServletTester is not best practise and may be deprecated in future releases.</p>
```

2020-11-26 09:59 UTC, gregw commented on jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletTester.java
> + * // Generate the request.
Perhaps show two examples.  One using LocalConnector directly with strings and then show HttpTester usage.

2020-11-26 10:00 UTC, gregw commented on jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletTester.java
> + * // Generate the request.
actually never mind...

2020-11-26 10:00 UTC, gregw approved these changes
other than slightly better wording. LGTM

2020-11-26 10:22 UTC, merged