Jetty 9.4.x optimize parser warning from logs and add spotbug
eclipse/jetty.project pull request #5735
Opened 2020-11-27 09:09 UTC by olamy

current logs parser are reading multiple time log files so this generate extra load on jenkins server.
this generate aggregated report per jdk as well (more readable)
<img width="1674" alt="Screen Shot 2020-11-27 at 6 57 47 pm" src="https://user-images.githubusercontent.com/19728/100431529-06d17880-30e4-11eb-99b2-4e40c9066dbe.png">

2020-12-10 17:36 UTC, joakime approved these changes
+1

2020-12-10 18:48 UTC, sbordet commented
@olamy why is the `-T2` option back? Did not we agree to disable it and have the build doing its course?

2020-12-10 19:07 UTC, joakime requested changes
Changing my review.
Lets drop the maven `-T#` arguments.

2020-12-10 19:07 UTC, joakime commented on Jenkinsfile
> +                mavenBuild( "jdk8", "-T2 clean install", "maven3")
I agree with @sbordet, lets remove the `-T2` here.

2020-12-10 19:07 UTC, joakime commented on Jenkinsfile
> +                mavenBuild( "jdk11", "-T2 clean install -Djacoco.skip=true -Perrorprone", "maven3")
I agree with @sbordet, lets remove the `-T2` here.

2020-12-10 19:07 UTC, joakime commented on Jenkinsfile
> +                mavenBuild( "jdk15", "-T2 clean install -Djacoco.skip=true", "maven3")
I agree with @sbordet, lets remove the `-T2` here.

2020-12-10 19:07 UTC, joakime commented on Jenkinsfile
> +                mavenBuild( "jdk8", "-T3 -Pcompact3 clean install -DskipTests", "maven3")
I agree with @sbordet, lets remove the `-T3` here.

2020-12-11 01:46 UTC, joakime approved these changes
LGTM.

2020-12-11 01:47 UTC, merged