Implement max duration of objects in pool
eclipse/jetty.project pull request #5800
Opened 2020-12-11 11:20 UTC by lorban

2020-12-11 14:13 UTC, sbordet requested changes
As discussed, let's try to implement expiration at `ConnectionPool` level as suggested by @joakime.

2020-12-11 14:13 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java
> +    protected void setMaxDuration(long timeInMs)
Use `java.time.Duration`.

2020-12-11 14:13 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/DuplexConnectionPool.java
> +    @ManagedAttribute(value = "The maximum duration in milliseconds a connection can be used for before it gets closed")
JMX annotations go in the getter.
Can you verify if JMC is able to convert to/from a `Duration` object?

2020-12-11 14:13 UTC, sbordet commented on jetty-util/src/main/java/org/eclipse/jetty/util/Pool.java
> +    public long getMaxDuration(TimeUnit unit)
Use `Duration`, much simpler to do conversions.

2020-12-11 14:13 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java
> +    @ManagedAttribute(value = "The maximum duration in milliseconds a connection can be used for before it gets closed")
JMX annotation in the getter.

2020-12-11 14:13 UTC, sbordet commented on jetty-util/src/main/java/org/eclipse/jetty/util/Pool.java
> +     * 0 is illegal and a negative value means there is no limit.
Better: "Value {@code 0} is illegal..."

2020-12-12 10:24 UTC, gregw requested changes
This looks to be entirely passive, in that an attempt to acquire has to be made before any duration expired entries are detected.  Even then, only those entries attempted will be detected and if all the activity is happening on valid ThreadLocal cached entries, then the rest of the entries might never be checked.

I think we need an active sweeper to find expired entries, otherwise we are just a little more likely to age them than current implementation of a usage count.

But then, having active behaviour doesn't feel like a core Pool thing.  Maybe we need a `TtlPool` extending Pool?

2020-12-14 08:28 UTC, lorban commented
@gregw We discussed this together with @joakime and @sbordet and we agreed that the pool class looks like the wrong layer to put this feature at.
This is why there is this 2nd PR that is about implementing the feature at the HTTP connection pool layer, leaving the lowest-layer pool code untouched: https://github.com/eclipse/jetty.project/pull/5801
Let's see what we find best, I'm personally in favor of the 2nd PR.

2020-12-14 08:34 UTC, gregw commented
@lorban so this PR is to be closed?  Or is it that the TTL feature is split between layers of abstraction?

2020-12-14 08:58 UTC, lorban commented
@gregw I'm unsure yet. My hope is that the TTL feature can be entirely implemented at the HTTP connection pool layer but this has yet to be proven.

If the work goes as planned, this PR can be completely abandoned. Otherwise, we'll have to see what alternatives we have.

2020-12-14 14:38 UTC, lorban commented
This is going to be done in the HTTP connection pool instead.

2020-12-14 14:38 UTC, closed without merging