Issue #5786 : Revisit Statistics classes
eclipse/jetty.project pull request #5825
Opened 2020-12-18 12:25 UTC by rk1165

Signed-off-by: Ravi Kumar <kumarravi1165@gmail.com>

2020-12-18 12:55 UTC, sbordet requested changes

2020-12-18 12:55 UTC, sbordet commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/MonitoredQueuedThreadPool.java
> +                    taskLatencyStats.record(taskLatency);
I think you missed another call to `set()` few lines above.

2020-12-18 13:11 UTC, sbordet approved these changes

2021-01-11 15:58 UTC, gregw commented
@sbordet can we merge this one?

2021-01-12 16:15 UTC, sbordet approved these changes

2021-01-12 16:15 UTC, merged

2021-01-12 16:17 UTC, sbordet commented
@rk1165 thanks! and sorry for the delay!