Issue #5866 - allow programmatic upgrades with websocket-core
eclipse/jetty.project pull request #5874
Opened 2021-01-12 06:46 UTC by lachlan-roberts

**Closes #5866**

Allow manual programmatic upgrades with websocket-core.

- Expose `Handshaker`, `CreatorNegotiator` from websocket-core-server internal package.
- Allow the `JettyServerFrameHandlerFactory` to be accessible as a bean on the `JettyWebSocketServerContainer` 

The `JettyServerFrameHandlerFactory` can't be accessible through API as we don't want to expose websocket-core through the Jetty WS API, but now you can access the Jetty FrameHandlerFactory, if you do `JettyWebSocketServerContainer.getBean(FrameHandlerFactory.class)`.

2021-01-12 08:34 UTC, gregw approved these changes

2021-01-12 16:11 UTC, sbordet requested changes
As discussed let's add a simple API at Jetty level, and clean up the core APIs.

2021-01-13 14:30 UTC, gregw approved these changes
LGTM

2021-01-19 15:35 UTC, sbordet approved these changes

2021-01-20 05:07 UTC, merged