Fixes #5880 - Move test-simple-webapp to demos.
eclipse/jetty.project pull request #5881
Opened 2021-01-14 15:48 UTC by sbordet

Moved test-simple-webapp to demos.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2021-01-18 16:13 UTC, joakime approved these changes
I'm good with it as is.
But it would be better if index.jsp was just renamed to index.html (as you don't have a JSP dependency declared in your demo-simple.mod

2021-01-19 09:52 UTC, janbartel commented
@sbordet  if this is moved into demos, then as everything else in demos is deployed by the demos.mod file, then shouldn't this be too?  And shouldn't it be linked onto the root/index.html page as well?

2021-01-19 09:53 UTC, janbartel requested changes
See my comment on the PR.

2021-01-19 10:34 UTC, sbordet commented
@janbartel I don't think it's worthwhile to add these 2 additional modules to the main demo, as we already have a "hello world" and there is no point in having 3 of them.

They can be enabled individually and they are mostly useful only for the documentation and for testing, so I think it's fine as is.

2021-01-19 11:27 UTC, janbartel commented
@sbordet well, the hello worlds are actually different: one is a servlet and one is a static page. Also, your simplest webapp isn't the simplest as we don't require you to have a web.xml  if you just have static content :)

2021-01-19 16:21 UTC, joakime approved these changes
LGTM

2021-01-20 10:16 UTC, janbartel requested changes
The reference to the webapp is incorrect in several places in the DistributionTests - looks like a simple global search and replace error.

2021-01-20 10:16 UTC, janbartel commented on tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
> +            File war = distribution.resolveArtifact("org.eclipse.jetty.demos:demo-simple-jsp-webapp:war:" + jettyVersion);
Should this be demo-simple-webapp or the demo-jsp-webapp? There's no demo-simple-jsp-webapp AFAIK.

2021-01-20 10:16 UTC, janbartel commented on tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
> +            File war = distribution.resolveArtifact("org.eclipse.jetty.demos:demo-simple-jsp-webapp:war:" + jettyVersion);
Same as previous comment - think this should be either demo-jsp-webapp or demo-simple-webapp, not sure which.

2021-01-20 10:16 UTC, janbartel commented on tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
> +            File war = distribution.resolveArtifact("org.eclipse.jetty.demos:demo-simple-jsp-webapp:war:" + jettyVersion);
See previous

2021-01-20 10:16 UTC, janbartel commented on tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
> +            File war = distribution.resolveArtifact("org.eclipse.jetty.demos:demo-simple-jsp-webapp:war:" + jettyVersion);
See previous

2021-01-20 10:16 UTC, janbartel commented on tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
> +            File war = distribution.resolveArtifact("org.eclipse.jetty.demos:demo-simple-jsp-webapp:war:" + jettyVersion);
See previous.

2021-01-20 10:16 UTC, janbartel commented on tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java
> +            File war = distribution.resolveArtifact("org.eclipse.jetty.demos:demo-simple-jsp-webapp:war:" + jettyVersion);
See previous.

2021-01-20 12:15 UTC, janbartel approved these changes
LGTM

2021-01-21 14:27 UTC, merged