Issue #6008 - Allow absolute paths to be provided in start.ini for request log directory.
eclipse/jetty.project pull request #6009
Opened 2021-02-25 10:47 UTC by lachlan-roberts

Closes #6008

2021-02-25 11:02 UTC, gregw requested changes
@lachlan-roberts I know this PR is just following other precedent.  But it is SO ugly!  I really don't want this pattern to spread through our code.

Surely there must be a way we can resolve `jetty.requestlog.dir` against a base dir and work out if it is relative or absolute.    Let's hangout about this.

2021-02-25 11:32 UTC, gregw approved these changes

2021-02-25 13:15 UTC, joakime commented
We have too many ways to configure the same thing, a path. (in this case, we have .. absolute, relative-complete, and relative-parent)

If we only supported 2 modes (relative and absolute), AND if we started to expand properties found in XML attributes this could go from ...

``` xml
<Property name="jetty.requestlog.absoluteFilePath">
  <Default>
    <Property name="jetty.base" default="." />/<Property name="jetty.requestlog.filePath">
      <Default><Property name="jetty.requestlog.dir" default="logs"/>/yyyy_mm_dd.request.log</Default>
    </Property>
  </Default>
</Property>
```

to

``` xml
<Property name="jetty.requestlog.absoluteFilePath" default="${jetty.base}/${jetty.requestlog.relativeDir}/yyyy_mm_dd.request.log" />
```

2021-02-26 01:13 UTC, lachlan-roberts commented
@joakime we need to maintain support for the existing properties. If we change to your suggestion of

```xml
<Property name="jetty.requestlog.absoluteFilePath" default="${jetty.base}/${jetty.requestlog.relativeDir}/yyyy_mm_dd.request.log" />
```

then we will break anyone using the existing properties `jetty.requestlog.filePath` and `jetty.requestlog.dir`.

2021-03-02 20:48 UTC, joakime commented
Draft PR #6022 is an alternate way to accomplish this.

2021-03-03 14:04 UTC, sbordet requested changes
@lachlan-roberts let's hold this in favor of #6022.

2021-03-03 20:25 UTC, joakime commented
PR #6022 has been merged.
We can probably close this PR as obsolete.

2021-03-04 00:26 UTC, lachlan-roberts commented
This is replaced by #6022 and #6033.

2021-03-04 00:26 UTC, closed without merging