Fix #5835 Durable filters and servlets
eclipse/jetty.project pull request #6027
Opened 2021-03-03 17:41 UTC by gregw

Fix #5835 Durable filters and servlets with a general ServletHandler cleanup.
This replaces #5837

2021-03-10 08:40 UTC, gregw commented
@janbartel nudge

2021-03-12 13:29 UTC, gregw commented
@janbartel re-nudge

2021-03-22 05:47 UTC, janbartel requested changes

2021-03-22 05:47 UTC, janbartel commented on jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java
> +            // Update indexes for prepending filters
I don't see any code here that removes the non-durable filtermappings, yet we've set the matchBefore and matchAfter index.

2021-03-22 07:02 UTC, janbartel approved these changes
If CI is happy, then ship it!

2021-03-22 10:28 UTC, merged