Added before dependents to Modules
eclipse/jetty.project pull request #6080
Opened 2021-03-22 07:14 UTC by gregw

Allow a module to list modules that it will be ordered before

Signed-off-by: Greg Wilkins <gregw@webtide.com>

2021-03-22 07:15 UTC, gregw commented
@joakime @sbordet regardless of how we name this mod section, it is important to add it soon.  Having the ability to insert a module before another would be very handy for issuing patches to existing releases (eg for CVE fixes).

2021-03-24 04:56 UTC, janbartel commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/modules.adoc
>  Enabling the `https` modules _does not_ enable the `http2` module.
```suggestion
Enabling the `https` module _does not_ enable the `http2` module.
```

2021-03-24 05:33 UTC, janbartel requested changes

2021-03-24 05:33 UTC, janbartel commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/modules.adoc
> +However, if the `http2` module is enabled (explicitly or transitively), then the `https` module is xref:og-modules-directive-depends[sorted] _after_ the `http2` module.
```suggestion
However, if the `http2` module is then subsequently enabled (explicitly or transitively), then the `https` module is xref:og-modules-directive-depends[sorted] _after_ the `http2` module.
```

2021-03-24 05:33 UTC, janbartel commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/modules.adoc
> +For example, in order to create a custom `org.eclipse.jetty.server.Server` subclass instance, to which the standard configuration is applied, without modifying existing module files or XML files, you
```suggestion
One use of this ordering could be to ensure that an xml configuration file is executed before any that are associated with the modules listed in the `before` clause. For example: in order to create a custom `org.eclipse.jetty.server.Server` subclass instance without needing to modify existing module or XML files, and to which the standard configuration is applied,  you can create a `custom-server` xref:og-modules-custom[Jetty custom module]:
```

2021-03-24 05:33 UTC, janbartel commented on jetty-start/src/main/java/org/eclipse/jetty/start/Module.java
> +        return Set.copyOf(_before);
Probably would have been more efficient to return an immutable view of the Set, but as this was previous behaviour to return a copy ....

2021-03-24 06:05 UTC, gregw commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/modules.adoc
> +However, if the `http2` module is enabled (explicitly or transitively), then the `https` module is xref:og-modules-directive-depends[sorted] _after_ the `http2` module.
It is not subsequently.  It may already be enabled.

2021-03-24 06:19 UTC, janbartel commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/modules.adoc
> +However, if the `http2` module is enabled (explicitly or transitively), then the `https` module is xref:og-modules-directive-depends[sorted] _after_ the `http2` module.
OK, yes.

2021-03-24 09:33 UTC, sbordet approved these changes

2021-03-24 11:51 UTC, janbartel approved these changes

2021-03-24 12:31 UTC, merged