Resolve #6132
eclipse/jetty.project pull request #6137
Opened 2021-04-05 22:18 UTC by gregw

This PR reverts the default behaviour to allows URIs that contain `%2F`.     I'm only 80% convinced of this and we need to consider really carefully before changing the default again.

The PR also contains a non-string based way to create custom `UriCompliance` instances.
It also introduces a new `Violation` that will allow ambiguous Uri to be passed to the application without extra normalisation.

2021-04-06 10:30 UTC, sbordet requested changes

2021-04-06 10:30 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +        NON_NORMAL_AMBIGUOUS_PATHS("https://tools.ietf.org/html/rfc3986#section-3.3", "Non normal ambiguous paths");
I think "non normal" is not descriptive enough. I'm not sure you wanted to have `@2f` in the javadocs, did you mean `%2f`?

How about `NON_CANONICAL_AMBIGUOUS_PATHS`?

2021-04-06 10:30 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +                violations = (mode == null) ? noneOf(Violation.class) : copyOf(mode.getAllowed());
Missing `break`.

2021-04-06 10:30 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
> +        String request = "GET /unnormal/.././path/amiguous%2f%2e%2e/%2e;/info HTTP/1.0\r\n" +
Fix typo: "amiguous".

2021-04-06 10:30 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java
> +            containsString("pathInfo=/path/amiguous/.././info")));
Fix typo: "amiguous".

2021-04-06 12:20 UTC, joakime requested changes
Minor changes.

2021-04-06 12:20 UTC, joakime commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +         * Allow Non canonical ambiguous paths. eg <code>/foo/x@2f/%2e%2e%/bar</code> provided to applications as <code>/foo/x/../bar</code>
Typo: `@2f`

2021-04-06 12:20 UTC, joakime commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +     * normalised.
Typo: `normalized` - https://www.merriam-webster.com/dictionary/normalize

yes, I realize your usage is the British spelling, but we should remain consistent with the Java API and also the URI Spec usage of the more common English spelling.

* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URI.html#normalize()
* https://tools.ietf.org/html/rfc3986#section-6

2021-04-06 13:02 UTC, joakime requested changes
Is there a reason that the `private UriCompliance(String name, Set<Violation> violations)` is still private?

Can it be `public` to allow embedded users a better API?

2021-04-06 13:02 UTC, joakime commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
>       * LEGACY compliance mode that disallows only ambiguous path parameters as per Jetty-9.4
This description should probably be clear about which `Violation` types we allow here (like you did with the `DEFAULT` description, which is a good change btw)

2021-04-06 13:02 UTC, joakime commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +     * canonicalized for safety.
This description should probably be clear about which `Violation` types we allow here too.

2021-04-06 13:02 UTC, joakime commented on jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
> +     * to the application in non-normal form.
And this description too should probably be clear about which `Violation` types we allow here.

2021-04-06 13:57 UTC, sbordet requested changes

2021-04-06 13:57 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
> +            // set the NON_NORMAL_AMBIGUOUS_PATHS compliance.
Update comment to `NON_CANONICAL...`.

2021-04-06 20:55 UTC, gregw commented
@joakime with regards to the `from` API, that doesn't allow us to set a name... do you think we should also allow custom mode names?

2021-04-07 07:38 UTC, sbordet approved these changes

2021-04-07 08:02 UTC, gregw commented
@joakime nudge

2021-04-07 11:51 UTC, joakime approved these changes

2021-04-08 02:02 UTC, gregw commented
@joakime something strange is happening.... you've approved the changes, but I'm still seeing a red cross and requested changes from you??? What does this issue look like to you?

2021-04-08 02:02 UTC, gregw commented
Oh... as soon as I commented it went green! strange!!!

2021-04-08 02:03 UTC, merged