Improve testing for temp directories
eclipse/jetty.project pull request #6139
Opened 2021-04-06 05:18 UTC by lachlan-roberts

Merge of PR #5483 to Jetty 10.0.x

2021-04-12 07:15 UTC, lachlan-roberts commented
@janbartel this should be fixed now. The `WebAppProvider` works slightly differently in Jetty 10 as it uses a different thread to do the scan, and this broke the test.

2021-04-13 07:36 UTC, janbartel requested changes

2021-04-13 07:36 UTC, janbartel commented on jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java
> +                throw new IllegalStateException("BASETEMPDIR is not a writable directory");
```suggestion
                throw new IllegalStateException(WebAppContext.BASETEMPDIR + " is not a writable directory");
```

2021-04-13 07:36 UTC, janbartel commented on jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentTempDirTest.java
> +        String deploymentXml = "<!DOCTYPE Configure PUBLIC \"-//Jetty//Configure//EN\" \"https://www.eclipse.org/jetty/configure_9_3.dtd\">\n" +
Should be configure_10_0.dtd?

2021-04-13 07:36 UTC, janbartel commented on jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentTempDirTest.java
> +        String deploymentXml = "<!DOCTYPE Configure PUBLIC \"-//Jetty//Configure//EN\" \"https://www.eclipse.org/jetty/configure_9_3.dtd\">\n" +
Should be configure_10_0.dtd?

2021-04-15 10:15 UTC, lachlan-roberts commented
@janbartel I have made the changes you requested.

2021-04-30 00:50 UTC, lachlan-roberts commented
@janbartel nudge

2021-04-30 01:12 UTC, janbartel approved these changes
ok

2021-04-30 06:05 UTC, merged