Fixes #5306 - Default jetty.*.acceptors should be 1.
eclipse/jetty.project pull request #6236
Opened 2021-05-05 15:46 UTC by sbordet

Changed the acceptor heuristic to default to 1, rather than calculating a value based on the number of cores.
Updated documentation.
Fixed a glitch in ManagedSelector.getMaxSelectedKeys() to return long, not double.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2021-05-06 02:13 UTC, gregw commented
Don't forget to link PR to issue: #5306

2021-05-06 02:15 UTC, gregw requested changes
It is too confusing to have the default set to -1, which is a heuristic that sets it to 1.

Just keep the heuristic logic and change the default to 1

2021-05-19 14:05 UTC, sbordet commented
@gregw nudge

2021-05-20 07:21 UTC, gregw approved these changes

2021-05-20 07:34 UTC, merged