Issue #6287 - fix classloading for WebSocketClient in webapp
eclipse/jetty.project pull request #6293
Opened 2021-05-18 08:13 UTC by lachlan-roberts

Issue #6287

2021-05-18 09:32 UTC, sbordet requested changes
I would like to see a similar test for Jetty's API as well.
I know the fix is in core, but we want to make sure.

2021-05-18 09:32 UTC, sbordet commented on jetty-websocket/websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/WebSocketCoreClient.java
> +        this.classLoader = classLoader;
I think it should be wrapped with `Objects.requireNonNull()`, as I don't see how we ever want this class loader to be `null`.

2021-05-18 09:32 UTC, sbordet commented on jetty-websocket/websocket-javax-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/ClientClassLoaderTest.java
> +        private WebSocketContainer clientContainer;
Allocate the WS container here and make the field `final`, as it's a more typical setup than creating a new container for every HTTP request.

2021-05-19 01:21 UTC, lachlan-roberts commented on jetty-websocket/websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/WebSocketCoreClient.java
> +        this.classLoader = classLoader;
I'm not even sure we really need these methods on `WebSocketCoreClient`, they are not currently used. We always just use the ContextClassLoader at the time the `WebSocketCoreClient` was created.

2021-05-19 10:08 UTC, sbordet commented
@lachlan-roberts apparently the tests you added for this issue fail, can you check?

2021-05-19 20:28 UTC, sbordet approved these changes

2021-05-20 07:55 UTC, merged