Issue #6327 Fix cookie leak test
eclipse/jetty.project pull request #6344
Opened 2021-06-02 00:32 UTC by janbartel

2021-06-02 00:33 UTC, janbartel commented
@gregw as you were the one to initially add the `@Ignore` annotation to this test, can you pls review this?

2021-06-03 12:06 UTC, gregw requested changes
I think this should still do multiple requests on the same connection.  Which can be done with:
```java
        LocalEndPoint endp = _connector.connect();
        endp.addInput(
            "GET /R1 HTTP/1.1\r\n" +
                "Host: localhost\r\n" +
                "\r\n" +
                "GET /R2 HTTP/1.0\r\n\r\n");

        String response1 = endp.getResponse();
        String response2 = endp.getResponse();

```

2021-06-04 01:28 UTC, janbartel commented
@gregw I implemented the suggestion, pls rereview.

2021-06-04 06:32 UTC, gregw approved these changes

2021-06-04 13:08 UTC, merged