Fix #6442
eclipse/jetty.project pull request #6454
Opened 2021-06-21 22:04 UTC by gregw

Removed IRC reference

2021-06-21 23:52 UTC, janbartel submitted a review, later dismissed
LGTM

2021-06-22 00:35 UTC, lachlan-roberts requested changes
I think you need to remove this from the current documentation as well as the `old_docs` directory. There should be another file at `src/main/asciidoc/contribution-guide/2-community.adoc` with the same info.

This also needs to be done in 9.4.x.

2021-06-22 06:48 UTC, lachlan-roberts submitted a review, later dismissed

2021-06-22 12:57 UTC, joakime approved these changes

2021-06-22 22:38 UTC, janbartel approved these changes

2021-06-22 23:14 UTC, merged