Add check for close_notify alerts as those are optional per spec
eclipse/jetty.project pull request #6471
Opened 2021-06-24 09:04 UTC by lorban

Fixes #6443 in branch 9.4.x.

2021-06-24 16:48 UTC, sbordet commented
I don't think this is correct. When the client closes it must produce a close_notify and send it to the server. It's the reply to this close_notify from the server that is optional, although we want to try hard and reply correctly. Also I would double check if this is still true in RFC 8446.

2021-06-25 10:02 UTC, lorban commented
@sbordet you're right; I mis-read the RFC that still says:
```
   Unless some other fatal alert has been transmitted, each party is
   required to send a close_notify alert before closing the write side
   of the connection.
```

Back to the drawing board, I noticed is that the close_notify alert packet is sent twice when the test fails, which I interpreted as a hint that there is some race condition somewhere in the SSL code.

So here's my next theory: the client's socket is closed after the server read the `doneRecord`. But while the SSL packet already traveled through the network and was read by the server, it could be that the client code hasn't yet returned from its blocking write and still needs to set a flag to mark the handshake as done.

Before the thread that performs the handshake has a chance to set this "handshake done" flag, the other thread could call `close` on the `SSLSocket` and interpret that as a close during the handshake, hence not requiring the alert packet to be sent.

I've added a `handshakeFuture.get()` before the call to close and can't reproduce the problem since.

WDYT?

2021-06-29 10:45 UTC, sbordet requested changes

2021-06-29 10:45 UTC, sbordet commented on jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesServerTest.java
> +        handshakeFuture.get();
Don't wait forever.

2021-06-29 10:51 UTC, lorban commented on jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesServerTest.java
> +        handshakeFuture.get();
Sure, I've added a 5 seconds timeout.

2021-06-29 13:54 UTC, sbordet approved these changes, later dismissed

2021-07-07 15:13 UTC, sbordet approved these changes

2021-07-07 15:14 UTC, merged