Fix #6562 last written bytebuffer
eclipse/jetty.project pull request #6563
Opened 2021-07-30 00:31 UTC by gregw

Fixes #6562 the last written bytebuffer calculation.
Also fixed an associated issue with unnecessary flush of an empty when last calculation already signalled last.

The code coverage is not complete, so more tests are needed for this use case. Also strange that `write(ByteBuffer)` does not appear to every commence aggregation?

2021-07-30 05:59 UTC, gregw commented
@lorban @lachlan-roberts In an attempt to get 100% code coverage, I could not find a path to get to the final last emptybuffer write. So I have removed it and I think it is good.  But give me extra good review on that deletion.

2021-07-30 09:03 UTC, lorban requested changes
You should probably add some tests to `HttpOutputTest` to assert that writing 0 length buffers does work.

2021-07-30 09:03 UTC, lorban commented on jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
> -                channelWrite(BufferUtil.EMPTY_BUFFER, true);
Serving a 0 length `byte[]` goes through this branch. This is why `GzipContentLengthTest.testServletTypeLengthStreamWrite()` fails for scenario `empty.txt`.

2021-07-30 09:03 UTC, lorban commented on jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
> -                else if (last)
Serving a 0 length `byte[]` goes through this branch. This is why `GzipContentLengthTest.testHttpOutputWrite()` fails for scenario `empty.txt`.

2021-07-30 23:02 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java
> -                channelWrite(BufferUtil.EMPTY_BUFFER, true);
Ah that's how it can be called!!! Restored it and added test cases in `HttpOutputTest` so it is now covered!

2021-08-02 10:15 UTC, lorban approved these changes

2021-08-03 02:30 UTC, merged