disabled those tests as third parties app are not jakarta ready
eclipse/jetty.project pull request #6589
Opened 2021-08-06 05:57 UTC by olamy

Signed-off-by: Olivier Lamy <oliver.lamy@gmail.com>

2021-08-06 15:20 UTC, joakime requested changes
Do we have an open issue for this we can reference in the @Disabled text?

2021-08-09 06:43 UTC, olamy commented
@joakime where is this file disabled?

2021-08-10 03:53 UTC, janbartel approved these changes

2021-08-10 04:33 UTC, olamy commented
> Do we have an open issue for this we can reference in the @disabled text?


done here https://github.com/eclipse/jetty.project/pull/6589/commits/ab3c518af36234df61d01e62a5e2df9346377196

2021-08-10 05:09 UTC, merged