Jetty 10.0.x 6476 warn on exec
eclipse/jetty.project pull request #6597
Opened 2021-08-10 20:56 UTC by sbordet

2021-08-10 20:58 UTC, sbordet commented
@gregw see if you want to modify `jetty.sh`.

2021-08-10 21:14 UTC, joakime commented
The output from `--list-config` should also indicate if a JVM will be forked or not.

2021-08-10 21:50 UTC, sbordet commented
> The output from `--list-config` should also indicate if a JVM will be forked or not.

You mean that it should be added, or that it is already indicated and should be documented?

2021-08-10 22:04 UTC, joakime commented
> > The output from `--list-config` should also indicate if a JVM will be forked or not.
> 
> You mean that it should be added, or that it is already indicated and should be documented?

I mean that it should be added (if it isn't there already).

2021-08-11 02:51 UTC, gregw requested changes
Doco is good.  But 3 lines of warning is too much.

2021-08-11 02:51 UTC, gregw commented on jetty-start/src/main/java/org/eclipse/jetty/start/Main.java
> +            StartLog.warn("$(java -jar $JETTY_HOME/start.jar --dry-run)");
3 lines of warning is a bit extreme!
```suggestion
            StartLog.warn("Forking JVM due to exec in module(s): %s.  Use --dry-run to generate non forking command line.", execModules);
```

2021-08-11 11:30 UTC, joakime commented
> Doco is good. But 3 lines of warning is too much.

I completely disagree with this statement about the number of lines of warning.

This warning is important, it is more important than a normal warning, but not suitable for the next level of severity (eg: error or fatal).

There's TONS of examples of projects with multiline important warnings for a single topic/concept. (docker, k8s, osgi, testcontainers, dropwizard, spring, apt, log4j startup warnings, slf4j init warnings, logback init warnings, node, groovy, maven, etc)  I'll be happy to demonstrate each of them if you want.

The reason multiline warnings exists, is that single line warnings is on the wrong side of the "is this important or just noise" question that people have.
We want to cross that threshold with this PR and make sure we report this important information.

2021-08-11 11:31 UTC, joakime requested changes, later dismissed
We need a `StartLog.important()` level of information conveyance to the user.

2021-08-11 22:42 UTC, gregw commented
We have certainly had complaints previously about over verbose logging and there is nothing said in the 3 lines that can't be said in 1.

Asking users to ignore multiple warnings is not good.

Better have an INFO level

2021-08-12 08:12 UTC, sbordet commented
@gregw @joakime I have updated the PR with your suggestions, nudge?

2021-08-12 23:17 UTC, gregw approved these changes

2021-08-13 15:32 UTC, merged