Issue #6497 - Replace the Alias checkers with new implementation. (Jetty-10)
eclipse/jetty.project pull request #6668
Opened 2021-08-26 09:00 UTC by lachlan-roberts

## Issue #6497

Deprecate and replace the `SameFileAliasChecker` with the `AllowedResourceAliasChecker` which does some additional safety checks.

This new AliasChecker is extended to also replace the `AllowSymLinkAliasChecker` with `SymlinkAllowedResourceAliasChecker`.

2021-08-30 00:46 UTC, gregw requested changes

2021-08-30 00:46 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java
> +}
EOL

2021-08-30 00:46 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java
> + * is not protected by {@link ContextHandler#isProtectedTarget(String)}.</p>
```suggestion
 * is not protected by {@link #isProtectedTarget(Path, LinkOption[])}.</p>
```

2021-08-30 00:46 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java
> +     * {@link ContextHandler#isProtectedTarget(String)} in which case the alias should not be allowed.
```suggestion
     * <p>The resource path is protected if it, or one of it's parents is in 
      * {@link ContextHandler#getProtectedTargets()} when fetched from {@link #doStart()}.</p>

     
     * {@link ContextHandler#isProtectedTarget(String)} in which case the alias should not be allowed.
```

2021-08-30 00:46 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java
> +        }
Remind me of why we can't walk the parent tree again?

2021-08-30 00:46 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
> +            addAliasCheck(new SymlinkAllowedResourceAliasChecker(this));
I'm wondering if we really still need this by default?   I guesss too late to change in a dot release, but let's put a TODO in to remove if/when we go to 10.1

2021-08-30 00:46 UTC, gregw commented on tests/test-integration/src/test/resources/file
> +This file is outside webroot.
EOL

2021-08-30 00:46 UTC, gregw commented on tests/test-integration/src/test/resources/sibling/file
> +This file is inside a sibling dir to webroot.
EOL

2021-08-30 00:46 UTC, gregw commented on tests/test-integration/src/test/resources/webroot/WEB-INF/web.xml
> +This is the web.xml file.
EOL

2021-08-30 00:46 UTC, gregw commented on tests/test-integration/src/test/resources/webroot/documents/file
> +This file is inside webroot/documents.
EOL

2021-08-30 00:46 UTC, gregw commented on tests/test-integration/src/test/resources/webroot/file
> +This file is inside webroot.
EOL

2021-08-30 00:46 UTC, gregw commented on tests/test-integration/src/test/resources/webroot/index.html
> +</html>
EOL

2021-08-30 01:46 UTC, gregw commented on tests/test-integration/src/test/java/org/eclipse/jetty/test/AliasCheckerSymlinkTest.java
> +public class AliasCheckerSymlinkTest
Can this be combined with or replace `AllowSymlinkAliasCheckerTest`

2021-09-02 00:20 UTC, lachlan-roberts commented
Replaced with PR #6681.

2021-09-02 00:20 UTC, closed without merging