Change dependabot interval to daily
eclipse/jetty.project pull request #6768
Opened 2021-09-10 14:46 UTC by joakime

+ Only chose to change branches 9.4.x and 10.0.x
  to daily.
  Leaving 11.0.x at weekly, so that it's updates
  can trail behind the 10.0.x ones that are
  merged forward to 11.0.x

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

2021-09-10 14:50 UTC, sbordet approved these changes, later dismissed

2021-09-11 03:00 UTC, olamy requested changes

2021-09-11 03:00 UTC, olamy commented on .github/dependabot.yml
>    - package-ecosystem: "github-actions"
we should remove this as we do not use any `github-actions`

2021-09-12 20:36 UTC, olamy approved these changes

2021-09-13 11:10 UTC, merged