Cleanup redundant transitive dependency usage/declarations
eclipse/jetty.project pull request #6867
Opened 2021-09-17 22:08 UTC by joakime

Revert the `maven-enforcer-plugin` to `3.0.0-M3`

Disabled `<requireUpperBoundDeps>` configuration.

Eliminate redundant transitive dependency declarations.

2021-09-18 00:08 UTC, janbartel requested changes
I am definitely in favour of reverting to `3.0.0-M3` for the `enforcer` plugin.

I don't think we need to remove the `enforceUpperBound` rule, _unless_ that too was added at the same time as the upgrade to `3.0.0`.

I'm not convinced about adding in all these other changes because a) some of them seem to go against the convention of moving every dependency into the `dependencyManagement` section of the pom that I thought we were supposed to be striving for and b) the build of this branch doesn't work and it will be difficult to work out why.

I think we should just do a simple PR to change back the version of the `enforcer` plugin, so we are back to a known working configuration,  then do a subsequent PR with a cleanup of the dependencies.

2021-09-19 05:50 UTC, olamy requested changes

2021-09-19 05:50 UTC, olamy commented on jetty-jspc-maven-plugin/pom.xml
> +      <version>${maven.version}</version>
no need of this as it's already declared in dptMngt in top level

2021-09-19 05:50 UTC, olamy commented on jetty-maven-plugin/pom.xml
> +      <version>${maven.version}</version>
not needed

2021-09-19 05:50 UTC, olamy commented on pom.xml
> -        <version>${asm.version}</version>
we use it directly and having this here in dptMngt will insure coherence between modules

2021-09-19 05:50 UTC, olamy commented on pom.xml
> -      <!-- maven deps -->
we use it directly and having this here in dptMngt will insure coherence between modules

2021-09-19 06:11 UTC, olamy requested changes

2021-09-19 06:11 UTC, olamy commented on jetty-unixsocket/pom.xml
> +    <jnr-unixsocket.version>0.38.10</jnr-unixsocket.version>
I would prefer having this in single place (i.e top pom)

2021-09-19 06:11 UTC, olamy commented on pom.xml
> +    <maven.enforcer.plugin.version>3.0.0-M3</maven.enforcer.plugin.version>
:(

2021-09-19 06:11 UTC, olamy commented on pom.xml
> +                <!--<requireUpperBoundDeps>
:(

2021-09-19 06:11 UTC, olamy commented on pom.xml
> +        <spotbugs.plugin.version>4.3.0</spotbugs.plugin.version>
I would prefer having this in single place (top of the pom)

2021-09-19 06:11 UTC, olamy commented on tests/test-sessions/test-infinispan-sessions/pom.xml
> -    <dependency>
some part of the code use so must be declare

2021-09-20 09:47 UTC, olamy commented on pom.xml
> -      <!-- maven deps -->
part of documentation here https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management 
```
The dependency management section is a mechanism for centralizing dependency information. 
When you have a set of projects that inherit from a common parent, 
it's possible to put all information about the dependency in the common POM and have simpler references 
to the artifacts in the child POMs.
```

2021-09-21 18:02 UTC, closed without merging