Issue #1087 - add module for a .well-known handler
eclipse/jetty.project pull request #7000
Opened 2021-10-15 03:28 UTC by lachlan-roberts

## Closes #1087

Adds a `well-known.mod` module which can add a handler to serve files on the `/.well-known` context path.
By default it serves files from`${jetty.base}/.well-known` directory.

2021-10-16 02:08 UTC, joakime submitted a review, later dismissed

2021-10-20 06:34 UTC, olamy submitted a review, later dismissed

2021-10-21 09:31 UTC, sbordet requested changes
Please also write a distribution test case, we want to be sure that it works (e.g. no typos in XML, etc.).

2021-10-21 09:31 UTC, sbordet commented on jetty-server/src/main/config/etc/well-known.xml
> +  <New id="WellKnownHandler" class="org.eclipse.jetty.server.handler.ContextHandler">
Seems to me that most `id` attribute names start with lowercase letter.

2021-10-21 09:31 UTC, sbordet commented on jetty-server/src/main/config/modules/well-known.mod
> +jetty.wellknown.dir?=.well-known
Why this section? I don't think it's needed since the XML has a `default` attribute, no?

2021-10-21 09:34 UTC, sbordet commented
@lachlan-roberts also, I would not mind documentation about this.
Please add an entry in `modules-standard.adoc` and a correspondent file `module-well-known.adoc`.

2021-10-21 11:44 UTC, joakime commented on jetty-server/src/main/config/etc/well-known.xml
> +  <New id="WellKnownHandler" class="org.eclipse.jetty.server.handler.ContextHandler">
I was curious, as I thought it was uppercase mostly.
So ...

``` shell
$ cd jetty-home-10.0.7/etc
# lowercase as "id" declaration
$ grep -ERh ' id="[a-z]' * | wc -l
71
# lowercase as "refid" declaration
$ grep -ERh ' refid="[a-z]' * | wc -l
43
# uppercase as "id" declaration
$ grep -ERh ' id="[A-Z]' * | wc -l
74
# uppercase as "refid" declaration
$ grep -ERh ' refid="[A-Z]' * | wc -l
26
```

So uppercase wins by 3 on "id", but is less used in "refid".
It's pretty much an even split in our XML.

This is the breakdown, of both "id" and "refid" usage.

``` shell
$ cd jetty-home-10.0.7/etc
$ grep -Rh "id=" * | sed -e 's/^.*\(id="[^"]*"\).*/\1/' | sort | uniq -c | sort -rn
     64 id="Server"
     11 id="sessionDataStoreFactory"
      8 id="httpConfig"
      6 id="properties"
      6 id="config"
      6 id="cache"
      5 id="unixSocketHttpConfig"
      5 id="sslContextFactory"
      5 id="sslConnector"
      5 id="queryMgrFactory"
      4 id="unixSocketConnector"
      4 id="DeploymentManager"
      3 id="sslHttpConfig"
      3 id="ServerLog"
      3 id="Rewrite"
      3 id="httpConnector"
      3 id="DebugListener"
      3 id="databaseAdaptor"
      3 id="cacheMgr"
      2 id="webappprovider"
      2 id="ThreadPool"
      2 id="threadPool"
      2 id="sessionDataMapFactory"
      2 id="ServerLogName"
      2 id="remoteCacheManager"
      2 id="queryManager"
      2 id="pkixSoftFail"
      2 id="pkixRevocationChecker"
      2 id="pkixPreferCrls"
      2 id="pkixNoFallback"
      2 id="OpenIdConfiguration"
      2 id="MBeanServer"
      2 id="mapping"
      2 id="jaspiAuthConfigFactory"
      2 id="HttpClient"
      2 id="hotrodMgr"
      2 id="defaultConfig"
      2 id="decoratorAttribute"
      2 id="Contexts"
      2 id="context"
      2 id="byteBufferPool"
      1 id="unixDomainConnector"
      1 id="ThreadLimitHandler"
      1 id="Stop"
      1 id="StatsHandler"
      1 id="RequestLog"
      1 id="proxyHolder"
      1 id="MBeanContainer"
      1 id="lowResourceMonitor"
      1 id="logging"
      1 id="keyStoreScanner"
      1 id="jsp"
      1 id="JMXConnectorServer"
      1 id="idMgr"
      1 id="homeBaseWarning"
      1 id="Handlers"
      1 id="GzipHandler"
      1 id="DefaultHandler"
      1 id="DebugHandler"
      1 id="BaseLoginService"
      1 id="alpn"
      1         <Arg name="server"><Ref refid='Server'/></Arg>
```

2021-10-22 05:19 UTC, lachlan-roberts commented on jetty-server/src/main/config/etc/well-known.xml
> +  <New id="WellKnownHandler" class="org.eclipse.jetty.server.handler.ContextHandler">
The convention for Handlers seems to be capital we have `GzipHandler`, `DefaultHandler`, `DebugHandler`, `StatsHandler`. So I will leave it as `WellKnownHandler`.

2021-10-22 05:43 UTC, lachlan-roberts commented on jetty-server/src/main/config/modules/well-known.mod
> +jetty.wellknown.dir?=.well-known
Yeah I don't think it is necessary I will remove.

2021-10-22 07:47 UTC, sbordet requested changes

2021-10-22 07:47 UTC, sbordet commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +This `Handler` serves files from a directory created at `${jetty.base}/.well-known`, note that this may be seen as a hidden directory by the filesystem.
Please specify that the default is `$JETTY_BASE/.well-known` (note use of env variable style, rather than ${jetty.base}, but it can be configured to be anywhere in the file system.

2021-10-22 07:47 UTC, sbordet commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +The concept of well-known URIs has been defined in RFC5785.
Link the RFC using `link:`

2021-10-22 07:47 UTC, sbordet commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +It may be used for things like automation of the renewal for Let's Encrypt certificates.
"It" at beginning of sentence seems to refer to the RFC. Specify again "This module".
Link `Let's Encrypt`.
Does the RFC specify another example? I think there is one for HTTP/2.

2021-10-22 07:47 UTC, sbordet commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +The module file is `$JETTY_HOME/modules/well-known.mod`:
Don't link the whole module, just its properties, which should be commented as if it was documentation, see the `alpn` module.

2021-10-22 10:08 UTC, joakime commented
Out of curiosity, why did we choose `${jetty.base}/.well-known` instead of ...

* `${jetty.base}/webapps/.well-known` or
* `${jetty.base}/webapps/well-known`

This entire concept could also have been done with an injected `${jetty.base}/webapps/well-known.xml` (like we do for the demo modules)

2021-10-22 11:30 UTC, sbordet commented
@joakime injecting `${jetty.base}/webapps/well-known.xml` would require to customize the XML with the actual directory, right, as I don't think it can be referenced from the XML as a module variable?

As for the location inside webapps or not, usages of `.well-known` are probably mostly done outside, as there is a collaboration with some other process that writes in the `.well-known` directory.

2021-10-22 13:57 UTC, joakime commented
Wish we had modules that can be added/installed without creating a `start.d/<name>.ini`
We could use them directly with `demo` now, and in the future with this `well-known` module.

It just has to create the `${jetty.base}/webapps/well-known.xml` and if anyone wants to customize it, they just customize the XML directly.

I wish we had separated webapps (or webapp-templates?) out from the module system properly.
Having the module system do webapps is awkward and getting more awkward. (`--add-webapp=<name>`?)
Eg: you cannot upgrade the webapp once installed, going from Jetty 10.0.x `demo` module and then upgrading to Jetty 11.0.x is broken, as webapps are not part of the module system logic.

2021-10-25 03:29 UTC, gregw requested changes

2021-10-25 03:29 UTC, gregw commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +Note that the `.well-known` directory may be seen as a hidden directory by the filesystem.
Wouldn't it be better to make the default `$JETTY_BASE/well-known` so that it is not hidden?

2021-10-25 03:29 UTC, gregw commented on jetty-server/src/main/config/modules/well-known.mod
> +Serve static files from a directory for the "/.well-known" context path.
```suggestion
Serve static files from a directory for the "/.well-known" context path from the "$JETTY_HOME/.well-known" directory.
```

2021-10-25 03:44 UTC, lachlan-roberts commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +Note that the `.well-known` directory may be seen as a hidden directory by the filesystem.
@gregw the problem with that is that the most common use case for this will probably be lets encrypt, and when you use that you need to specify the "webroot" directory and then it creates its files in the `$WEBROOT/.well-known` directory.

So if you made this by default `$JETTY_BASE/well-known` then it wouldn't work without changing the configuration.

2021-10-28 05:00 UTC, gregw commented on jetty-server/src/main/config/modules/well-known.mod
> +Serve static files from a directory for the "/.well-known" context path.
@lachlan-roberts ?

2021-10-28 05:04 UTC, lachlan-roberts commented on jetty-server/src/main/config/modules/well-known.mod
> +Serve static files from a directory for the "/.well-known" context path.
The directory can be configured below so its not always served from the `$JETTY_HOME/.well-known` directory.

2021-10-28 05:22 UTC, gregw submitted a review, later dismissed

2021-11-11 10:27 UTC, sbordet requested changes

2021-11-11 10:27 UTC, sbordet commented on documentation/jetty-documentation/src/main/asciidoc/operations-guide/modules/module-well-known.adoc
> +The `well-known` creates a `ResourceHandler` deployed at the `/.well-known` context path which serves files from a directory.
```suggestion
The `well-known` Jetty module creates a `ResourceHandler` deployed at the `/.well-known` context path which serves files from a directory.
```

2021-11-11 10:27 UTC, sbordet commented on jetty-server/src/main/config/modules/well-known.mod
> +## Well Known Directory (relative to $jetty.base)
Please specify here that if it's a relative path then it is relative to `$JETTY_BASE`, otherwise it's an absolute path.

2021-11-12 08:45 UTC, sbordet approved these changes

2021-11-16 22:51 UTC, merged