Issue #7012 Replace geronimo spec jars with jakarta equivalents
eclipse/jetty.project pull request #7013
Opened 2021-10-19 06:17 UTC by janbartel

Closes #7012 

Replace all geronimo spec jars by their jakarta equivalents (using the `javax` namespace for jetty-10)

2021-10-19 10:04 UTC, joakime requested changes
The older `jspDependencies()` made it easier to understand what was being done and why in the various places it was being used.

The new boolean technique is awkward.
Please either restore `jspDependencies()` or make the parameter something else.

``` java
enum JettyFeatureEnum {
  JSP, CDI
}

public static List<Option> coreJettyDependencies(JettyFeatureEnum ... feature) {
```

and then used like ...

``` java
options.addAll(TestOSGiUtil.coreJettyDependencies(JSP));
```

2021-10-19 10:04 UTC, joakime commented on jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
> +    public static List<Option> coreJettyDependencies(boolean withJsp)
Can we just have a `coreJspDependencies()` instead of this boolean?

2021-10-19 11:28 UTC, olamy requested changes

2021-10-19 11:28 UTC, olamy commented on pom.xml
> +    <jakarta.inject.api.version>1.0.4</jakarta.inject.api.version>
1.0.5 looks to be available now see #7016

2021-10-19 22:35 UTC, janbartel commented on pom.xml
> +    <jakarta.inject.api.version>1.0.4</jakarta.inject.api.version>
No fair, I'm in a race with dependabot ;)

2021-10-20 00:12 UTC, janbartel commented on jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestOSGiUtil.java
> +    public static List<Option> coreJettyDependencies(boolean withJsp)
OK, I've implemented it a different way. The problem is that the jakarta.transaction-api jar wants to use the javax.el* package, so we must deploy the jakarta.el-api jar to satisfy it, even though it won't be used. However, if we then subsequently configure the JSP bundles, we want to use the org.mortbay.jasper.apache-el jar instead because it provides both the api and impl. So in the latest solution I've removed the prior configuration of the jakarta.el-api jar.

2021-10-20 01:03 UTC, olamy approved these changes

2021-10-28 04:37 UTC, janbartel commented
@joakime nudge

2021-11-01 02:29 UTC, janbartel commented
@joakime nudge

2021-11-01 22:38 UTC, joakime approved these changes

2021-11-01 23:37 UTC, merged