Issue #6974 - improvements & fixes to ByteBufferPool implementations
eclipse/jetty.project pull request #7017
Opened 2021-10-20 04:51 UTC by lachlan-roberts

## Issue #6974 - improvements to ByteBufferPool implementations

**ByteBufferPool Changes**

- Fixes bugs and raceconditions related to use of `ArrayByteBufferPool` and `MappedByteBufferPool` with non zero settings for `maxHeapMemory` and `maxDirectMemory`.
- Make a constructor argument of zero for `maxHeapMemory` and `maxDirectMemory` mean that a default is calculated based on the total max memory of the JVM.
- Make the `ArrayByteBufferPool` and `MappedByteBufferPool` extensible to change the bucket scaling.
- Implement the `LogArrayByteBufferPool` which doubles the size of each consecutive bucket instead of scaling linearly.
- Implement `Dumpable` for the ByteBufferPool implementations.

**WebSocket Changes**

- `WebSocketUpgradeFilter` always waits until it is started before it gets the `NativeWebSocketConfiguration` so it can be created when the `ByteBufferPool` is ready.
- WebSocket now uses the servers `ByteBufferPool` instead of creating its own `MappedByteBufferPool` every time.

2021-10-20 11:14 UTC, lorban requested changes
I think the changes are good, except for the concurrency model which feels broken and should be reviewed.

2021-10-20 11:14 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +        Bucket bucket = buckets[index];
The way you arranged for thread-safety is incorrect, this pattern is called the _double-checked locking_ and can only be made correct by marking the initialized variable as `volatile`.

I don't think you can easily make an array's entries `volatile` so you may want to have a look at `AtomicReferenceArray` instead.

2021-10-20 11:14 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
> +        private AtomicLong _poolSize;
You have to mark this variable as `volatile` to get the memory fencing you need between the thread that's going to write it and the threads that are going to read it.

This seems to indicate a weakness in your concurrency model, you should always try to avoid having to access non-final variables from concurrent code.

2021-10-20 11:14 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/MappedByteBufferPool.java
> +        Bucket bucket = (_newBucket != null) ? _newBucket.apply(key) : new Bucket(this, key * getCapacityFactor(), getMaxQueueLength());
The call to the `_newBucket` function seems to be the only reason why you need `setPoolSizeAtomic()`. AFAICT this mechanism isn't used anywhere but in a test so I'd refactor the code so that the `Bucket` constructor takes the `AtomicLong`

2021-10-20 11:14 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +    protected int getBucketNumber(int capacity)
FYI, I personally have a preference for only using the `get` prefix for plain simple getters, unlike here where you do some calculation.

It's your call, but at least you know why the method was named `bucketFor` instead of `getBucketFor`.

2021-10-20 11:14 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +    public AtomicLong getSizeAtomic(boolean direct)
You definitely don't want this method to be public at the very least. This getter's existence (even if protected / package-private) even makes me question the idea of referencing the `AtomicLong` from the buckets.

2021-10-21 06:20 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +        Bucket bucket = buckets[index];
I have changed this to initialize all buckets in the constructor and never change the values in the array.

2021-10-21 06:20 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
> +        private AtomicLong _poolSize;
I have now made this final and deprecated previous constructor, as bucket is public class as it is defined in an interface.

2021-10-21 06:20 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/MappedByteBufferPool.java
> +        Bucket bucket = (_newBucket != null) ? _newBucket.apply(key) : new Bucket(this, key * getCapacityFactor(), getMaxQueueLength());
The `setPoolSizeAtomic()` has been removed and replaced with new constructor on `Bucket`.

2021-10-21 06:20 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +    protected int getBucketNumber(int capacity)
Changed these methods to `bucketFor` and `capacityFor`.

2021-10-21 06:20 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +    public AtomicLong getSizeAtomic(boolean direct)
Changed this method to `protected`.

2021-10-21 07:52 UTC, gregw commented on jetty-server/src/main/config/etc/jetty-bytebufferpool.xml
>      <Arg type="int"><Property name="jetty.byteBufferPool.factor" default="1024"/></Arg>
Perhaps we should make the class in the `<New>` element a parameter, so the log version can easily be put in.  Not sure how simple it would be to do... but perhaps something like:
```xml
  <New id="byteBufferPool">
    <Class><Property name="jetty.byteBufferPool.class" default="org.eclipse.jetty.io.ArrayByteBufferPool"/></Class>
    <Arg type="int"><Property name="jetty.byteBufferPool.minCapacity" default="0"/></Arg>
    ...
```

2021-10-21 08:47 UTC, lorban submitted a review, later dismissed
LGTM

2021-10-21 08:47 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +            if (bucket == null || bucket.isEmpty())
This null check is now useless, isn't it?

2021-10-21 08:47 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +        // Initialize all buckets in constructor and never modify the array again.
:+1: This is more in line with what `ArrayRetainableByteBufferPool` does in 10.0.x.

2021-10-21 08:47 UTC, lorban commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
FYI in 10.0.x `ArrayRetainableByteBufferPool` has a more sophisticated memory release algorithm (the method is named `releaseExcessMemory`). I'd like your opinion about it, and it would be good that you'd familiarize with it too as your changes will have to be ported to 10.0.x and we certainly want to keep the code aligned everywhere we can.

2021-10-21 10:00 UTC, sbordet requested changes

2021-10-21 10:00 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +    }
Uhm, no. Can you have in this base class a function that updates the atomics, called from the buckets? The idea is "tell, don't ask". 
The functions are there, but have been deprecated?

2021-10-21 10:00 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +public class LogArrayByteBufferPool extends ArrayByteBufferPool
Uh, not "Log", but "Logarithmic" -- we don't want to confuse it with a pool that logs to SLF4J.

2021-10-21 10:00 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +        _maxDirectMemory = (maxDirectMemory != 0) ? maxDirectMemory : Runtime.getRuntime().maxMemory() / 4;
Old default was unlimited, I would keep that.

2021-10-21 10:00 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +        if (_detailedDump)
Use the getter method rather than the field here.

2021-10-21 10:00 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
This is a total duplicate of the base class.

2021-10-21 10:00 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java
> +        private final AtomicLong _poolSize;
Don't like this, see previous comment.

2021-10-21 10:05 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +    }
They need to be updated from Bucket which is a class contained in the ByteBufferPool interface which doesn't have access to methods from AbstractByteBufferPool.

2021-10-21 10:07 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +        _maxDirectMemory = (maxDirectMemory != 0) ? maxDirectMemory : Runtime.getRuntime().maxMemory() / 4;
The whole point of this is to avoid an unbounded memory commitment, we want a default which will not cause the JVM to run out of memory.

2021-10-21 10:08 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
It actually does a different strategy for releasing the memory. The super method actually clears the whole bucket while this one only clears one buffer from the bucket.

2021-10-21 13:46 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +    }
Pass the functions, not the fields, then.

2021-10-21 13:47 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +        _maxDirectMemory = (maxDirectMemory != 0) ? maxDirectMemory : Runtime.getRuntime().maxMemory() / 4;
Sure but a change in behavior is what we can do in 10, no?

2021-10-21 13:51 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
I don't like that the whole bucket is cleared.
If you have a steady 100 acquires/s, you have 100 buffers in that bucket; a small spike would clear the whole bucket, causing a subsequent allocation spike, when the memory was only exceeded by 1 buffer, not all of them.

2021-10-21 14:02 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +        _maxDirectMemory = (maxDirectMemory != 0) ? maxDirectMemory : Runtime.getRuntime().maxMemory() / 4;
This change is prompted by 9.4 WebSocket using the ByteBufferPool to allocate buffers of variable size and eventually running out of memory. So we do need to do something about this in 9.4 and not just 10.

2021-10-21 14:04 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
Clearing a whole bucket is the previous behaviour for ArrayByteBufferPool that I haven't changed. 

But for the log buckets there will be a lot less buckets so clearing a whole bucket is probably far too aggressive.

2021-10-21 15:08 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
You are correct that the the bucket was cleared before as well, I misread that.
However, it was removed from the array, becoming a "free floating" object that no other thread could access, so clearing it was guaranteed to be thread safe.
Now the bucket is kept, so a concurrent allocation may add buffers to it, while another thread is trying to clear it, possibly making the clearing longer.

2021-10-21 15:09 UTC, sbordet commented
@gregw @lachlan-roberts overall I feel that these changes are too much for 9.4.x.
If the problem is in WebSocket, I don't think we need such massive changes in the buffer pools.
I'm sure I'm missing something, so let's sync on this.

2021-10-22 01:36 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +    protected void releaseMemory(boolean direct)
We have the same method `releaseExcessMemory()` here in 9.4 but its on the base class `AbstractByteBufferPool`, this method just keeps looping calling a `Consumer<Boolean>` until the pool has less memory than the maxMemorySize. The `ArrayByteBufferPool` uses this new `releaseMemory()` method as its release strategy which it passes to the `releaseExcessMemory()` method. I don't think we can easily change this contract as people may be extending `AbstractByteBufferPool` themselves. But we could make our `releaseMemory()` smarter to avoid things like over releasing too much memory.

The `ArrayRetainableByteBufferPool` release strategy is based on oldest entry which we cannot do in `ByteBufferPool`. And I'm not sure I understand it, why do we bother finding the oldest entry? shouldn't all entries in a specific bucket have the same capacity so it won't matter which one is evicted?

2021-10-22 01:49 UTC, lachlan-roberts commented on jetty-server/src/main/config/etc/jetty-bytebufferpool.xml
>      <Arg type="int"><Property name="jetty.byteBufferPool.factor" default="1024"/></Arg>
I can try this, only problem is that `factor` is a constructor argument for `ArrayByteBufferPool` but is kind of meaningless for the `LogarithmicByteBufferPool`. But I could add a dummy constructor in `LogarithmicByteBufferPool` for factor so it can be used in this way.

2021-10-22 01:58 UTC, lachlan-roberts commented on jetty-server/src/main/config/etc/jetty-bytebufferpool.xml
>      <Arg type="int"><Property name="jetty.byteBufferPool.factor" default="1024"/></Arg>
`MappedByteBufferPool` does not have a matching constructor either, so I'm not sure how useful this will be.

2021-10-22 02:06 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java
> +            if (bucket == null || bucket.isEmpty())
Yep, fixed.

2021-10-22 02:06 UTC, lachlan-roberts commented on jetty-io/src/main/java/org/eclipse/jetty/io/LogArrayByteBufferPool.java
> +public class LogArrayByteBufferPool extends ArrayByteBufferPool
done

2021-11-10 00:35 UTC, gregw commented
@sbordet @lachlan-roberts let's hangout tonight(tomorrow morning)

2021-11-10 00:36 UTC, gregw commented
... but note that whilst I don't like changes in 9.4, I also don't like the unlimited memory commitment that we currently allow with the default pool with no easy way to change it.

2021-11-12 10:06 UTC, sbordet approved these changes, later dismissed

2021-11-16 05:34 UTC, gregw requested changes
Can you provide a `bytebufferpool-log` modules that provides `bytebufferpool` and uses an alternative xml that configures the log byte buffers

2021-11-16 05:34 UTC, gregw commented on jetty-io/src/main/java/org/eclipse/jetty/io/AbstractByteBufferPool.java
> +
Perhaps:
```suggestion
    IntConsumer updateMemory(boolean direct)
    {
        return (direct) ? _directMemory::addAndGet : _heapMemory::addAndGet;
    }

```

2021-11-23 06:27 UTC, gregw approved these changes

2021-11-24 23:09 UTC, merged