Issue #2504 - expose more WebSocket details in jetty server dump
eclipse/jetty.project pull request #7058
Opened 2021-10-29 04:14 UTC by lachlan-roberts

closes #2504

2021-10-29 11:45 UTC, joakime requested changes
Please fix the format type.
Do we have an existing unit test that can trigger the new code in this PR?

2021-10-29 11:45 UTC, joakime commented on jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/Configuration.java
> +                    "inputBufferSize=%s, outputBufferSize=%s, maxBinaryMessageSize=%s, maxTextMessageSize=%s, maxOutgoingFrames=%s}",
Why are these numbers formatted with `%s` and not `%d` ?

2021-11-01 04:10 UTC, lachlan-roberts commented
> Do we have an existing unit test that can trigger the new code in this PR?

@joakime I don't think there are currently any websocket tests for the output of the dump, I could write some if you want.

2021-11-01 04:23 UTC, lachlan-roberts commented on jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/Configuration.java
> +                    "inputBufferSize=%s, outputBufferSize=%s, maxBinaryMessageSize=%s, maxTextMessageSize=%s, maxOutgoingFrames=%s}",
I don't think there's any major difference between `%d` and `%s` for integers unless you want some special formatting.
 
These are also class types and not the primitive ones, so I thought `%s` might be better, they are `Duration`,  `Boolean`, `Long`, `Integer` and the values are null if no configuration is set for them.

2021-12-01 23:21 UTC, joakime approved these changes

2021-12-02 08:55 UTC, merged