Issue #7266 - fix ALPN module selection based on runtime.feature.alpn property
eclipse/jetty.project pull request #7267
Opened 2021-12-13 12:00 UTC by lachlan-roberts

closes #7266

2021-12-13 13:38 UTC, joakime requested changes
I don't like this.

What's the scenario to reproduce with the old code?

2021-12-13 13:38 UTC, joakime commented on jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java
> +                properties.setProperty("runtime.feature.alpn", Boolean.toString(ver.getPlatform() >= 9), source);
This is wrong.
Java 8 has support too.
The previous version checked for the existence of a specific class to know if the ALPN support was backported.

2021-12-13 14:17 UTC, joakime commented
We have 3 states to worry about in Jetty 8.

1. Old Java 8, needs `-XBootclasspath`
2. New Java 8, needs `jetty-alpn-openjdk8-server-<jetty.version>.jar`
3. Java 9+, needs `jetty-alpn-java-server-<jetty.version>.jar`

The `runtime.feature.alpn` property was created to address 2 and 3 above, but not 1.
Since `runtime.feature.alpn` was created, the `alpn-agent` was integrated.
So now 1 and 2 above are handled by the `alpn-agent`, and 3 is handled by direct use of `jetty-alpn-java-server-<jetty.version>.jar`

There is no longer a purpose for `runtime.feature.alpn` for the shipped `jetty-home` modules.

Don't change the existing `runtime.feature.alpn` however, as there are still cases with embedded systems and custom jetty.base distributions with different software where we need this as it stood before (eg: Product Foo is attempting to be installed on a Java 9+ but with limited featureset that lacks alpn featureset).

What this PR should do.

* Delete `alpn-16.mod` that's just noise and is detritus from an old merge, and is no longer referenced AFAICT.
* Introduce a new detection of java.version is 9 or above, perhaps call it `java.version.modern` with a value of `old` (java 8) or `modern` (java 9).

As for how to detect Java 9+, some ideas:
* Does `java.lang.Runtime.Version` exist? (You are on Java 9+)
* Does `java.lang.Module` exist? (You are on Java 9+)
* A simple Version check like you are currently doing in this this PR.  (We historically didn't do this as we came across some wacky JVMs that had version strings that broke the version check, but I think those were all limited to Java 8 or older, and the versioning rules in Java 9+ became far more strict)

So you will wind up with ...

JVM | ALPN Support | Module
---- | ----- | ----
8u201 (needs `xbootclasspath`) | `alpn-agent` | `alpn-java-old`
8u282 (needs `jetty-alpn-openjdk8-server.jar`) | `alpn-agent` | `alpn-java-old`
9+ | lib=`jetty-alpn-java-server-<jetty.version>.jar` | `alpn-java-modern`

What needs to also be tested: The existing `alpn-available-false.mod` automatically includes the `jetty-alpn-openjdk8-server` which needs to be tested on an old pre-backport-of-alpn version of Java 8 to know if that's still a sane setup.

2021-12-14 01:56 UTC, lachlan-roberts commented
Tested and working with `8u201`, `8u281`, and `11.0.10`.

2021-12-14 12:36 UTC, joakime approved these changes
:+1:

2021-12-14 23:11 UTC, merged