Jetty 9.4.x : fix tries mistakenly throwing ArrayIndexOutOfBoundsException
eclipse/jetty.project pull request #7503
Opened 2022-01-31 09:53 UTC by lorban

2022-01-31 21:38 UTC, gregw requested changes

2022-01-31 21:38 UTC, gregw commented on jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTrie.java
> +                    t = big[c] = _rows;
Can we make the small index logic exactly the same as this.

2022-02-01 00:08 UTC, gregw commented on jetty-util/src/main/java/org/eclipse/jetty/util/ArrayTrie.java
> +                    t = big[c] = _rows;
I pushed this change.

2022-02-01 11:58 UTC, sbordet approved these changes

2022-02-01 12:33 UTC, merged

2022-02-02 00:15 UTC, gregw reviewed
LGTM (I know too late if it didn't :)