Fixes #7514 - Adding InheritedListeners to already-started components…
eclipse/jetty.project pull request #7522
Opened 2022-02-02 16:10 UTC by sbordet

… can cause IllegalStateException

Removed the unnecessary check-and-throw statements from SelectorManager.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2022-02-02 21:22 UTC, gregw requested changes
We need to protect against concurrent modifications whilst iterating over the listeners.  Maybe a CoW list?

2022-02-02 21:22 UTC, gregw commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> -        if (isRunning())
I think this theoretically exposes us to `ConcurrentModificationException`s

2022-02-02 21:22 UTC, gregw commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> -        if (isRunning())
I think this definitely exposes us to `ConcurrentModificationException`s if the selector is iterating over events when this is called.

2022-02-03 08:51 UTC, merged

2022-10-10 13:51 UTC, sbordet commented
Merged to `jetty-12.0.x` on 3 Feb 2022, commit 40378616681e8b8664b4fcdab7cc4efe1ce64244.