Jetty 9.4.x 7517 trie stack overflow
eclipse/jetty.project pull request #7528
Opened 2022-02-03 05:50 UTC by gregw

avoid recursion

2022-02-03 05:51 UTC, gregw commented
Ooops this also includes the fix to #7518

2022-02-03 08:25 UTC, lorban requested changes
You broke `HttpParserTest` which means there's a lack of test coverage in `TrieTest`.

2022-02-03 10:54 UTC, gregw commented
@lorban Added extra test. The problem was a bug with the return if the first non matching character was a big index one.

2022-02-03 13:29 UTC, lorban submitted a review, later dismissed
I would slightly improve a couple of assertions, otherwise LGTM.

2022-02-03 13:29 UTC, lorban commented on jetty-util/src/test/java/org/eclipse/jetty/util/TrieTest.java
> +        assertNotNull(trie.keySet());
Maybe assert that keyset contains `huge`?

2022-02-03 13:29 UTC, lorban commented on jetty-util/src/test/java/org/eclipse/jetty/util/TrieTest.java
> +        assertNotNull(trie.toString());
Maybe assert that `toString()` contains the `huge` substring?

2022-02-03 22:46 UTC, merged

2022-02-15 22:06 UTC, yunussemreeee commented
7528