Add option to allow well-known directories to be listed.
eclipse/jetty.project pull request #7544
Opened 2022-02-08 00:31 UTC by lachlan-roberts

Signed-off-by: Lachlan Roberts <lachlan@webtide.com>

2022-02-17 21:16 UTC, joakime approved these changes, later dismissed

2022-02-20 11:20 UTC, olamy approved these changes, later dismissed

2022-02-21 07:29 UTC, sbordet requested changes

2022-02-21 07:29 UTC, sbordet commented on jetty-server/src/main/config/etc/well-known.xml
> +        <Set name="directoriesListed"><Property name="jetty.wellknown.directoriesListed" default="false"/></Set>
I'd rename this to `listDirectories`.

2022-02-22 09:09 UTC, sbordet approved these changes

2022-02-22 23:25 UTC, merged