Issue #7531 Reinstate ClassLoaderServlet test class
eclipse/jetty.project pull request #7565
Opened 2022-02-11 04:34 UTC by janbartel

Re-instates the ClassLoaderSerlvet test class from `test-spec-webapp`, which had been throwing exceptions. The intention is for the ClassLoaderServlet class to be able to load a class from `jetty-util` at a _different_ version level than the server.

2022-02-11 11:45 UTC, joakime requested changes
This simple change is not enough to isolate the issues with this.

The entire tree, and everything that uses it must be isolated as well.
It cannot spill out into demos, or other modules, or jetty-home.

My last proposal was that we create a /tests/test-classloader/ tree and keep this isolated within there, and add enforcer rules to reject the use of those test modules anywhere else in the project tree.

2022-02-11 11:47 UTC, joakime commented
This change has effectively broken the release, as now the jetty-util version is indeterminate from here, to demos, into jetty-home, and jetty-runner.

Another choice is to NOT use jetty-util as this (one of our own modules in this multi-module setup), but something else, that doesn't exist in our own tree.

2022-02-11 22:23 UTC, janbartel commented
@joakime can you please explain that? I can't see how a dependency from a single `war` module can leak into any other module? I've just built jetty-9 and 10 and I don't see the older `jetty-util` jar in `jetty-home`?

2022-02-14 14:34 UTC, joakime commented
That war is referenced in demos, and test-distribution, and jetty-home, it's rather interconnected.
This change breaks the release 100% of the time.
It also breaks IDE usage as you now have 2 versions of the jetty-util present in your IDE. (which breaks compile/testing in the IDE as well).

If you insist on this being jetty-util, and ONLY jetty-util, and only in this war, then the changes in #4332 is the proper way to test this.
Frankly, this test should NOT exist in the demos, it should be isolated in its own war, a war that is not referenced by the rest of the reactor.
This is better accomplished by having a non-jetty artifact (that we don't use anywhere else in jetty) on the server classpath and war classpath and verifying that we handle this situation properly.

2022-03-01 22:58 UTC, joakime requested changes
Just drop PR, not going to happen this simply in 9.4.x

2022-03-21 14:41 UTC, joakime commented
Moving this from project 9.4.46 to 9.4.47

2022-04-04 09:12 UTC, janbartel commented
Dropping PR, it seems its too hard to solve this right now.

2022-04-04 09:12 UTC, closed without merging