Issue #5965 - fixing invalid dot output from start.jar
eclipse/jetty.project pull request #7606
Opened 2022-02-16 16:50 UTC by joakime

Fixes #5965

2022-02-16 17:17 UTC, sbordet requested changes, later dismissed
@joakime possible to write a test case, running `dot` as in the issue to see if it can process the file?

`dot` is required to build Jetty (because of the documentation) so it should not be a problem?

2022-02-16 18:01 UTC, joakime commented
@sbordet done, added testcase that uses `dot` if it exists

2022-02-17 21:49 UTC, joakime commented
> `dot` is required to build Jetty (because of the documentation) so it should not be a problem?

Actually, it's not required, the documentation will still build and produce output, but without diagrams if `dot` is missing.

2022-02-18 07:16 UTC, olamy approved these changes

2022-02-21 18:54 UTC, sbordet approved these changes

2022-02-21 19:12 UTC, merged