Issue #7615 HttpServletResponse.encodeURL() should support relative paths
eclipse/jetty.project pull request #7616
Opened 2022-02-17 17:14 UTC by joakime

Fixing `Response.encodeURL(String)` to work with relative paths like `encodeURL("../foo/bar.txt")`

2022-03-01 22:50 UTC, joakime commented
@gregw bump, review please.

2022-03-21 11:21 UTC, gregw requested changes

2022-03-21 11:21 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +                uri = new URI(url);
I'm very much against introducing the jdk URI class here.   
I'm going to have a little bit of a play to see what our alternatives are. Standby....

2022-03-21 11:25 UTC, gregw commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +                uri = new URI(url);
Also it is not needed at this point as a URI starting with .. will never have a scheme

2022-03-21 11:40 UTC, gregw commented
see #7763 for a simpler alternative

2022-03-21 12:38 UTC, joakime commented
Closing in favor of #7763

2022-03-21 12:38 UTC, closed without merging