Jetty Core APIs review and javadocs.
eclipse/jetty.project pull request #7644
Opened 2022-02-23 16:38 UTC by sbordet

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2022-02-23 17:19 UTC, gregw requested changes
Mostly OK.... a few quibbles..... but I really preferred the `asProcessor` style.   It will prevent bugs like the one you made in the javadoc!

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Handler.java
> + * wants to process the HTTP request, and subsequent sibling or children {@code Handler}s
```suggestion
 * will process the HTTP request, and subsequent sibling or children {@code Handler}s
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Handler.java
> +        <T extends Handler> List<T> getDescendantsByClass(Class<T> type);
```suggestion
        <T extends Handler> List<T> getDescendants(Class<T> type);
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Handler.java
> +        <T extends Handler> T getDescendantByClass(Class<T> type);
```suggestion
        <T extends Handler> T getDescendant(Class<T> type);
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Handler.java
> +        default <T extends Handler.Container> T getContainerByClass(Handler handler, Class<T> type)
```suggestion
        default <T extends Handler.Container> T getContainer(Handler handler, Class<T> type)
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Handler.java
> +     */
```suggestion
    /**
     * <p>A {@link Handler} that itself implements {@link Request.Processor}
     * and that returns itself from a call to {@link Handler#handle(Request)}.
     * Subclasses only need to implement 
     * {@link #process(Request, Response, Callback)}.</p>
     */
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> + * class YourHandler
```suggestion
 * class YourHandler extends Handler.Processor
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> + *                 return;
You need to generate response and succeed callback here.

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> + * class YourHandler
I'm not sure `Request` is the place for the full handler example.
It should link to the `Handler` which can document how a request is handled.  And also link to `Content.Provider` which can have an example of processing content like you have below

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> +    class WrapperProcessor extends Wrapper implements Processor
I don't hate this name, but I preferred ProcessingWrapper, because it is primarily is-a wrapper.

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> +     *         return wrapped;
This code is wrong if the processor is null.

I think I preferred `asProcessor` as it avoids this easily made mistake.

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/handler/ProxiedRequestHandler.java
> +        return wrapper;
So much nicer as:
```suggestion
        return wraper.asProcessor(super.handle(wrapper));
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/handler/RewriteHandler.java
> +        return rewritten;
simpler as:
```suggestion
        Request.WrapperProcessor rewritten = rewrite(request);
        return rewritten.asProcessor(super.handle(rewritten));
```

2022-02-23 17:19 UTC, gregw commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/handler/ContextHandler.java
> +        return scoped;
I preferred:
```suggestion
        return scoped.asProcessor(_context.get(scoped));
```

2022-02-24 08:44 UTC, sbordet commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> +     *         return wrapped;
Agreed.

2022-02-24 08:46 UTC, sbordet commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> +    class WrapperProcessor extends Wrapper implements Processor
I see it's mostly used as a `Processor`. In fact, the only reason to use this class is to wrap another `Processor` via `asProcessor()`, so it's all about `Processor`s.

2022-02-24 08:46 UTC, sbordet commented on jetty-core/jetty-core-server/src/main/java/org/eclipse/jetty/core/server/Request.java
> + *                 return;
Done.

2022-02-24 09:22 UTC, gregw approved these changes
LGTM

2022-02-24 11:12 UTC, merged