jetty 9.4.x remove non used maven plugin
eclipse/jetty.project pull request #7690
Opened 2022-03-04 10:23 UTC by olamy

- remove some site configuration, non used checkstyle profile and turn skip xml into one line property
- do not skip execution of ITs as well
- bad idea
- fix that

2022-03-04 10:43 UTC, joakime requested changes
our 2 maven plugins have some oddities (inconsistencies?) between them with surefire/skip

2022-03-04 10:43 UTC, joakime commented on jetty-maven-plugin/pom.xml
> +    <maven.test.skip.exec>true</maven.test.skip.exec>
Why do we have this for `jetty-maven-plugin` at all?
And we had a similar maven-surefire-plugin/config/skip=true on `jetty-jspc-maven-plugin` and you didn't include this `maven.test.skip.exec` property there.

2022-03-04 22:56 UTC, olamy commented
> our 2 maven plugins have some oddities (inconsistencies?) between them with surefire/skip

because there is a difference between the 2 plugins:
- `jetty-jspc-maven-plugin` doesn't have any src/test/java source code so no test are compiled and surefire doesn't need to be skipped as there is not classes to scan  (target/test-classes is just empty)
- `jetty-maven-plugin` have code in src/test/java which is technically a class (TestGetContent) only here to be included as a common test for most of the ITs test. But this test cannot be runned apart from the maven-invoker-plugin tests (if we do not skip it simply fail as it need the context of our IT tests). That's why `maven-invoker-plugin` have the following configuration `<addTestClassPath>true</addTestClassPath>`  and most of the IT test have this 
```          
          <dependenciesToScan>
            <dependency>org.eclipse.jetty:jetty-maven-plugin</dependency>
          </dependenciesToScan>
```

2022-03-05 00:34 UTC, joakime approved these changes
Sounds good to me. 👍

2022-03-05 09:48 UTC, merged