port stats handler responsesThrown changes to 12.0.x
eclipse/jetty.project pull request #7980
Opened 2022-05-12 00:51 UTC by lachlan-roberts

## Issue #7979
 port stats handler responsesThrown changes to `12.0.x`

Also made some other changes:
- do wrapping of stream in process method not handle
- `_processTimeStats` now records only time in process method
- request stats is only modified if request is accepted and processed by the wrapped handler

2022-05-12 03:22 UTC, lachlan-roberts commented
test failures seem to be unrelated

2022-05-12 08:06 UTC, sbordet requested changes

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +            _handleTimeStats.record(System.nanoTime() - beginTimeStamp);
Should you not call `_handleStats.decrement()` here?

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +            _responsesThrown.increment();
This should be `_handleThrows` and you may want to differentiate from `_processThrows`.

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +                _responsesThrown.increment();
This should be `_processThrows`, see above.

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +                return "SomeConnectionStatsObject";
Can this be a `Set`? If not, use better constant like `static final Object PRESENT = new Object()`.

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +                            default ->
Is this necessary?

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +                    super.succeeded();
Move the call to `super` as last statement in the method.

2022-05-12 08:06 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/StatisticsHandler.java
> +                    super.failed(x);
Move the call to `super` as last statement in the method.

2022-05-16 08:38 UTC, lorban approved these changes
LGTM

2022-05-18 05:23 UTC, merged