Implement #8057 103 Early Hint
eclipse/jetty.project pull request #8058
Opened 2022-05-26 00:03 UTC by gregw

Implementing #8057 Early hints

2022-05-26 03:29 UTC, gregw commented
@lorban can you look at why h3 is failing.

2022-05-26 06:34 UTC, lorban commented
@gregw I see no H3 test failure in the PR's build, only a checkstyle error. What am I overlooking?

2022-05-26 06:44 UTC, gregw commented
@lorban have you run org.eclipse.jetty.http.client.IntermediateResponseTest#test103EarlyHint ?

2022-05-26 14:22 UTC, lorban commented
@gregw I've added the missing support in H3 for 103 status code and pushed the change to this branch.

While your test now passes and I'm reasonably confident my changes are correct, it would still be wise to have @sbordet review this bit eventually.

2022-05-26 17:05 UTC, sbordet requested changes

2022-05-26 17:05 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java
>                      if (status >= 100 && status < 200)
There is `HttpStatus.isInformational()` that we should use here.

2022-05-26 17:05 UTC, sbordet commented on jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java
> +        boolean interimResponse = status >= HttpStatus.CONTINUE_100 && status < HttpStatus.OK_200 && status != HttpStatus.SWITCHING_PROTOCOLS_101;
Replace with `HttpStatus.isInformational() && !101`.

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +    public void test100Continue(Transport transport) throws Exception
There are a lot of 100-Continue tests elsewhere, so I don't think we need to duplicate this here.
I'd remove this test.

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +                            System.err.println("onSuccess\n" + response.getHeaders());
Remove `System.err`

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +                            throw new IllegalStateException("should not have accepted");
This exception will only be logged, better call `response.abort(new ISE(...))`, so the test will fail.

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +                            throw new IllegalStateException("should not have accepted");
Use `response.abort(new ISE(...))`.

2022-05-26 17:05 UTC, sbordet commented on jetty-http3/http3-common/src/main/java/org/eclipse/jetty/http3/internal/HTTP3StreamConnection.java
> +                if (response.getStatus() != HttpStatus.CONTINUE_100 && response.getStatus() != HttpStatus.EARLY_HINT_103)
This should be `HttpStatus.isInformational()`.

2022-05-26 17:05 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java
> +        EARLY_HINT(EARLY_HINT_103, "Early Hint"),
Let's add also `HttpHeader.Link` from RFC 8288.

2022-05-26 17:05 UTC, sbordet commented on jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3StreamClient.java
> +            valid = validateAndUpdate(EnumSet.of(FrameState.INITIAL, FrameState.HEADER, FrameState.CONTINUE), FrameState.CONTINUE);
I would rename `FrameState.CONTINUE` to `INFORMATIONAL`.

State HEADER is the state used to validate data frames (i.e. we can only receive a DATA frame if we are in HEADER state).
So I think the "from" states can only be INITIAL and CONTINUE(INFORMATIONAL).

2022-05-26 17:05 UTC, sbordet commented on jetty-http3/http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpTransportOverHTTP3.java
> +        boolean interimResponse = status >= HttpStatus.CONTINUE_100 && status < HttpStatus.OK_200 && status != HttpStatus.SWITCHING_PROTOCOLS_101;
Replace with `HttpStatus.isInformational() && !101`.

2022-05-26 17:05 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +     */
Javadoc is wrong.

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +public class IntermediateResponseTest extends AbstractTest<TransportScenario>
Rename to `InformationalResponseTest`.

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +                        org.eclipse.jetty.client.api.Request request = response.getRequest();
Use `var request = ...`.

2022-05-26 17:05 UTC, sbordet commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +                        org.eclipse.jetty.client.api.Request request = response.getRequest();
Use `var request = ...`.

2022-05-26 23:34 UTC, gregw commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +    public void test100Continue(Transport transport) throws Exception
I'm not sure the other tests made sending the content actually conditional on receiving the 100, as I certainly could not find the magic needed in the HttpClient elsewhere.    So I'd be more inclined to delete the other tests and keep this one.  I'll look for any other differences

2022-05-26 23:48 UTC, gregw commented on tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/IntermediateResponseTest.java
> +    public void test100Continue(Transport transport) throws Exception
OK now I find the good 100 test!

2022-05-26 23:50 UTC, gregw commented
@lorban @sbordet I've updated for review feedback.
However, there is still something racy either in the tests or the impl.   UNIX_DOMAIN frequently fails for me if run with other tests (the second 103 is skipped).  I have once seen H2 fail by the 103 being reported as the final response instead of the 200, but I can't reproduce.     Something is not quiet right :(

2022-05-26 23:52 UTC, gregw commented
Hmmm and I've just had a flake of the 102 test for UNIX_DOMAIN as well... also not reproducible :(

2022-05-26 23:58 UTC, gregw commented
@sbordet what does the client do if it is still processing the 102/103 response and the final (or next) response turns up?    On the server, we don't wait for anything from the client before sending the next response, but if I put in a 10ms sleep between the responses then I don't get any flakes.      Either we are writing over the responses or the client is processing the next one before the last is finished?

2022-05-27 00:01 UTC, gregw commented
@sbordet I think the race is in the client.  If I put the 10ms sleeps in the server I pass every time. However, if I put a 100ms sleep in the onSuccess handling for the 1xx responses, then I fail more often than not, even for HTTP.

2022-05-27 07:07 UTC, lorban commented on jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3StreamClient.java
> +            valid = validateAndUpdate(EnumSet.of(FrameState.INITIAL, FrameState.HEADER, FrameState.CONTINUE), FrameState.CONTINUE);
I agree that `FrameState.CONTINUE` should be renamed to `FrameState.INFORMATIONAL`.

I'm wondering if this code could be generalized or if we have no choice but to stick to a `if (status == 103)` special case.

2022-05-27 07:10 UTC, lorban commented on jetty-server/src/main/java/org/eclipse/jetty/server/Response.java
> +     * @throws IOException if unable to send the 102 response
```diff
- if unable to send the 102 response
+ if unable to send the 103 response
```

2022-05-27 07:13 UTC, lorban commented
All tests in `IntermediateResponseTest` eventually fail when ran enough times, even if the H3 and UNIX_DOMAIN ones are more sensible.

2022-05-30 00:41 UTC, gregw commented on jetty-http3/http3-common/src/main/java/org/eclipse/jetty/http3/internal/HTTP3StreamConnection.java
> +                if (response.getStatus() != HttpStatus.CONTINUE_100 && response.getStatus() != HttpStatus.EARLY_HINT_103)
Is that OK for a 101 switching protocols?

2022-05-30 00:41 UTC, gregw commented on jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java
> +        EARLY_HINT(EARLY_HINT_103, "Early Hint"),
Added in javadoc

2022-05-30 00:48 UTC, gregw commented on jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3StreamClient.java
> +            valid = validateAndUpdate(EnumSet.of(FrameState.INITIAL, FrameState.HEADER, FrameState.CONTINUE), FrameState.CONTINUE);
There is no special case for 102???  Let's hangout and walk through this logic.

2022-05-30 01:15 UTC, gregw commented
@sbordet @lorban The flaky issue is somewhere below the generation of the response in the server and the parsing of it in the client.   I added some println's and for a good run I see:
```
generateResponseLine HTTP/1.1{s=103,h=2,cl=-1}
startResponse 103 Early Hint
generateResponseLine HTTP/1.1{s=103,h=2,cl=-1}
startResponse 103 Early Hint
generateResponseLine HTTP/1.1{s=200,h=2,cl=-1}
startResponse 200 OK
```
So each generated response is parsed (startResponse) in the client.

But for a bad run I see:
```
generateResponseLine HTTP/1.1{s=103,h=2,cl=-1}
generateResponseLine HTTP/1.1{s=103,h=2,cl=-1}
startResponse 103 Early Hint
generateResponseLine HTTP/1.1{s=200,h=2,cl=-1}
startResponse 200 OK
```
So all the responses are generated, but one of them is not received.     It feels like something might be clearing a buffer when it should not?     

@lorban can you focus on the H2/H3 flakes and I'll keep looking at h1

2022-05-30 01:27 UTC, gregw commented
oops sorry forced pushed after a rebase

2022-05-30 02:18 UTC, gregw commented on jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java
>                  networkBuffer.clear();
@sbordet @lorban this is the cause of the UNIX_DOMAIN flake.  A pipelined response can be discarded after a 1xx response.    I'm not sure of the fix.

2022-05-30 03:15 UTC, gregw commented
@sbordet I found and maybe fixed the flake in the HttpClient (discarding content after a 1xx), but would appreciate very careful review.
@lorban I can't get any flaky fails in h2 or h3? How about you?

2022-05-30 10:05 UTC, lorban commented
@gregw I did not manage to get any of the tests in `InformationalResponseTest` to fail for H2 or H3. But I can make `HttpClientStreamTest.testFileUpload` on H3 fail about once every couple dozen runs. I'm aware of that failure and I already started investigating it.

2022-05-30 10:32 UTC, sbordet commented
@gregw looking

2022-05-31 07:28 UTC, lorban approved these changes

2022-05-31 08:08 UTC, sbordet approved these changes

2022-06-01 01:56 UTC, merged