Issue #8151 - make websocket close non-blocking
eclipse/jetty.project pull request #8164
Opened 2022-06-14 06:48 UTC by lachlan-roberts

Proposed fix to #8151 by making the close non-blocking so it can be called from within the send callback.

2022-06-14 06:53 UTC, sbordet commented
I don't think changing the semantic of `close()` is a good idea. It has, and always had, a blocking semantic.

2022-06-14 06:58 UTC, sbordet commented
@lachlan-roberts I don't think making `close()` async is right, but I'm worried that the problem is a different one, i.e. sends are not reentrant.

What if you do another send() from a callback? Does it block?

2022-06-14 11:57 UTC, lachlan-roberts commented
@sbordet yes the problem with sends still exists if you do a blockingSend inside the callback for an asyncSend then the blockingSend will be stuck until connection times out. This is because we're using an iterating callback for the writes.

2022-06-14 12:19 UTC, sbordet commented
@lachlan-roberts then perhaps it's only a problem of ordering of when the callback is called... first we must complete the `IteratingCallback` and then succeeding the external callback.

2022-06-17 07:48 UTC, sbordet commented
After discussion, I think there is no other way other than making `close()` async. The use case in #8151 is legit and unfortunately the API does not give applications a choice of using blocking vs non-blocking `close()` (like it does with `send()`, so the only option is to make `close()` async.

2022-06-17 07:49 UTC, sbordet requested changes
Can you please add if possible a `close(int, String, Callback)` to the Jetty WS APIs?

2022-06-17 09:32 UTC, sbordet approved these changes

2022-06-29 06:30 UTC, merged