Issue #8211 - fix ISE from HttpChannelState if failure during process
eclipse/jetty.project pull request #8215
Opened 2022-06-28 06:39 UTC by lachlan-roberts

If a timeout or stream reset occurs during process, the `HttpChannelState` will be failed, this causes `callback.succeeded()` to throw ISE. This ISE is then caught in `HandlerInvoker` and the callback is failed, and because the callback was failed twice we get the `java.lang.IllegalStateException: already completed` seen in #8211.

This PR fixes this by 
- only failing the callback in `HandlerInvoker` if `HttpChannel` has not been completed.
- Do not throw from `callback.failed()` if the callback is failed with same cause as why the `HttpChannel` was failed.

2022-06-29 04:27 UTC, gregw approved these changes
I think this LG, but as I'm kind of a co-author, we should get @sbordet's thoughts as well.

2022-06-29 04:27 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +            }
Potentially it would be neater to put this logic into a method:
```suggestion
            request._callback.ensureCompleted(failure);
```

2022-06-29 04:27 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                    return;
Need a comment here about the fact we are being forgiving of lazy applications that doubly report a failure.
```suggestion
                // Be forgiving of applications that report a failure that is already known by treating as a noop.
                if (request._httpChannel != null && request._httpChannel._error != null && TypeUtil.isAssociated(request._httpChannel._error.getCause(), failure))
                    return;
```

2022-06-29 04:28 UTC, gregw submitted a review, later dismissed
oops I approved when I wanted to request some small changes.

2022-08-04 11:50 UTC, sbordet requested changes

2022-08-04 11:50 UTC, sbordet commented on jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/IdleTimeoutTest.java
> +        final int idleTimeout = 1000;
No need for `final`, here and below.

2022-08-04 11:50 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                _completed = true;
I would not do this check here.
The call below `lockedOnComplete()` is the one responsible for setting `_completed` to `true`, and throwing if it's already set.
I would: A) make `lockedOnComplete()` return a `boolean`, and if it is `false` return; and B) remove the code in `lockedOnComplete()` that throws, which is now never executed.

2022-08-04 11:50 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                _completed = true;
Ditto.

2022-08-04 11:50 UTC, sbordet commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
> +                _request._callback.ensureCompleted(failure);
I am not sure I understand this. With the current modifications, the original code calling `failed()` is already doing the check on `_completed`, so this method does nothing different, and certainly does not "ensure" and it only fails the callback, while the name "ensureCompleted" seems to hint that it either succeeds or fails it.
I would restore the old code.

2022-08-04 11:51 UTC, sbordet commented
@lachlan-roberts I have pushed changes that align to my comments, so I'll merge this PR once build passes.

2022-08-04 15:06 UTC, merged