Issue #8216 - make processing of metadata in OpenIdConfiguration extensible
eclipse/jetty.project pull request #8221
Opened 2022-06-29 09:13 UTC by lachlan-roberts

## Issue #8216

Make `processMetadata()` and `fetchOpenIdConnectMetadata()` protected inside `OpenIdConfiguration` to make it easier to extend.

2022-06-29 12:07 UTC, joakime submitted a review, later dismissed

2022-07-04 00:33 UTC, gregw requested changes

2022-07-04 00:33 UTC, gregw commented on jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdConfiguration.java
> +        authEndpoint = (String)discoveryDocument.get("authorization_endpoint");
Make "authorization_endpoint" and "token_endpoint" be constant Strings

2022-07-04 00:33 UTC, gregw commented on jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdConfiguration.java
> +    protected void processMetadata(Map<String, Object> discoveryDocument)
javadoc

2022-07-04 00:33 UTC, gregw commented on jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdConfiguration.java
> +    protected Map<String, Object> fetchOpenIdConnectMetadata()
javadoc

2022-07-04 02:53 UTC, gregw requested changes

2022-07-04 02:53 UTC, gregw commented on jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdConfiguration.java
> +     * Process the OpenID Connect metadata discovered by {@link #fetchOpenIdConnectMetadata()}.
I was kind of hoping that you'd explain what processing can be done and what is done by default.
Currently it looks like you are just validating some parameters exist or are a certain value, but not much else.

So you need to at leaset explain that IAE can be  thrown, perhaps even add it to the signature

2022-07-04 05:28 UTC, gregw approved these changes

2022-07-04 07:10 UTC, merged