Re-enabled jetty-ee9-proxy and jetty-ee10-proxy modules.
eclipse/jetty.project pull request #8289
Opened 2022-07-12 20:43 UTC by sbordet

Introduced TunnelSupport to abstract out the tunnelling capabilities.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2022-07-12 20:50 UTC, sbordet commented
@gregw here's the work on the proxy modules.

Note that I left 4 tests disabled as idle timeout in core still does not work as intended, but the majority of the work for the proxy modules is done.

Also note that I had to modify `ServletApiRequest.getRequestURL()` to comply with the spec (was returning the query string but it should not).
Also implemented `ServletApiRequest.getCookies()`, but can be optimized.

Moved `ConnectHandler` to core.

In ee10's `ServletChannel.handle()`, case `SEND_ERROR` I had to use `resetContent()` instead of `reset()` as we want to retain any header that has been set by the application before writing the error response. This is in line with Jetty 11.

2022-07-12 23:18 UTC, gregw requested changes
currently not compiling in CI.
I'll have a look today if I get time.

2022-07-20 15:15 UTC, joakime commented on jetty-ee10/jetty-ee10-proxy/src/test/java/org/eclipse/jetty/ee10/proxy/ForwardProxyTLSServerTest.java
> +                else if (MimeTypes.Type.FORM_ENCODED.is(request.getHeaders().get(HttpHeader.CONTENT_TYPE)))
Not required, but could be useful (in the future).

``` java
Request.hasFormEncoded(request)
Request.hasQuery(request)
Request.hasMultipartForm(request)
```

2022-07-20 15:19 UTC, joakime commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
> +            // TODO: inbound (client-to-server) cookies don't have all these parameters.
I think this is right for the Request side.

2022-07-20 15:21 UTC, joakime commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
> +            return new StringBuffer(HttpURI.build(ServletContextRequest.this.getHttpURI()).query(null).asString());
Makes sense.

2022-07-20 15:36 UTC, joakime approved these changes
LGTM

2022-07-22 06:24 UTC, olamy approved these changes

2022-07-22 11:36 UTC, merged