Review MultiException in light of addSuppressed options
eclipse/jetty.project pull request #8338
Opened 2022-07-25 18:12 UTC by joakime

After a conversation with @lorban it was pointed out that `MultiException` should be removed in favor of just using `addSuppressed(Throwable)` instead.

* Cleanup of `MultiException` to be easier to follow/understand by using Suppressed Throwables internally.
* Improved `MultiExceptionTest`
* Add `TypeUtil.withSuppressed(Throwable, List<Throwable> suppressed)` to make working with error lists easier.
* Converted `HandlerCollection` and `XmlConfiguration` to show how to use Error Lists instead.

2022-07-25 18:14 UTC, joakime commented on jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java
> +            throw TypeUtil.withSuppressed(new NoSuchMethodException(message), errors);
There's no test for `errors.isEmpty()` here as at this point we must throw an exception.

2022-07-26 00:13 UTC, gregw requested changes
Rather than deprecate and remove, I think there is value is just making the a class with a few static utility methods that work more or less how the old lazy list did (ie starts with a null value).
For example, one of the destroy usages of MultiException could be changed to:
```java

    @Override
    public void destroy()
    {
        Throwable multi = null;
        if (_configurations != null)
        {
            for (Configuration configuration : _configurations)
            {
                try
                {
                    configuration.destroy(this);
                }
                catch (Exception e)
                {
                    multi = MultiException.add(multi, e);
                }
            }
        }
        _configurations = null;
        super.destroy();
        MultiException.ifExceptionalThrowRuntime(multi);
    }
```

Eitherway, let's not do an intermediary step. Let's decide the final form and go straight to it. If we step halfway, then we'll get stuck there for sure!

If we are really worried about backwards compatibility, perhaps we keep the old API as deprecated but use the new static version ourselves.

2022-07-26 00:13 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/MultiException.java
> +        if (e instanceof MultiException mex)
Before adding suppress we should check org.eclipse.jetty.util.TypeUtil#isAssociated.   Perhaps this entire method can just be:
```suggestion
        if (!TypeUtil#isAssociated(this,e))
            addSuppressed(e);
```

2022-07-26 00:16 UTC, joakime commented on jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/MultiExceptionTest.java
>      private MultiException multiExceptionWithRtIo()
Should remove this unused method.

2022-07-26 00:38 UTC, gregw requested changes

2022-07-26 00:38 UTC, gregw commented on jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java
> +        errors.forEach(t::addSuppressed);
This needs to check if the errors are associated with `TypeUtil.isAssociated`.

2022-07-27 02:44 UTC, joakime commented
Closing in favor of rework in PR #8340

2022-07-27 02:44 UTC, closed without merging