Issue #8354 - Reduce usages of Locks contention in Logging in AdaptiveExecutionStrategy
eclipse/jetty.project pull request #8358
Opened 2022-07-29 12:51 UTC by joakime

Fixes: 

* #8354

This is a speculative fix, as I cannot replicate the deadlock reported in the issue.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

2022-07-29 13:23 UTC, sbordet requested changes
No, logging libraries are supposed to receive objects and _they_ call `toString()` that the whole point.
I think this PR should be closed and not merged.

2022-08-07 11:22 UTC, gregw requested changes
I don't think this change is the right way to go... essentially calling toString without a lock.

Instead, I think we could try to call the toString of the `_producer` and perhaps also the `_tryExecutor` without the lock held (their state will not be blocked by the lock anyway), then grab the lock and combine those strings with the other state of this class.

2022-08-07 11:22 UTC, gregw commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java
> +            LOG.debug("{} dispatch {}", toStringLocked(), execute);
Lock is not held here?

2022-08-07 11:22 UTC, gregw commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java
> +            LOG.debug("{} tryProduce {}", toStringLocked(), wasPending);
Lock is not held here?

2022-08-07 11:22 UTC, gregw commented on jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java
> +            LOG.debug("ss={} t={}/{} {}", subStrategy, task, Invocable.getInvocationType(task), toStringLocked());
Nor here.

2022-09-24 15:22 UTC, closed without merging