Strengthen WebSocket upgrade contract and other improvements
eclipse/jetty.project pull request #8413
Opened 2022-08-04 09:08 UTC by lachlan-roberts

- Strengthen contract of WebSocket upgrade methods by defining in javadoc that an error response needs to be generated by them if they are not returning a WebSocket Object.
- Remove `WebSocketNegotiation` from the public API, use (req, resp, cb) style method in `WebSocketNegotiator` instead.
- Factor out a `isWebSocketUpgradeRequest` method for the `Handshaker` so that the Upgrade Servlet/Filters can check it is really an upgrade attempt before allocating the Blocking Callback and other resources.
- Add `Attachment` interface onto the Servlet Request objects so the wrapped `HttpServletRequest` and `HttpServletResponse` can be stored there and retrieved once `websocket-core` calls back the API layer.

2022-08-10 10:01 UTC, sbordet requested changes

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/module-info.java
> +    exports org.eclipse.jetty.websocket.core.server.internal;
No, we can't export internal classes, that's why they are internal.

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/CreatorNegotiator.java
> +package org.eclipse.jetty.websocket.core.server;
This class should be an implementation detail... why was moved out of internal?

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/Handshaker.java
> +    boolean isWebSocketUpgradeRequest(Request request);
Javadocs for this too.

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/Handshaker.java
> +     * This will attempt to upgrade a request to WebSocket.
```suggestion
     * <p>Attempts to upgrade a request to WebSocket.</p>
```

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/Handshaker.java
> +     * for completing the callback and generating a response.</p>
```suggestion
     * <p>Returns {@code true} if the WebSocket upgrade is successful and a successful response is generated and the callback eventually completed,
     * or if the WebSocket upgrade failed and a failure response is generated and the callback eventually completed.
     * Returns {@code false} if a response is not generated and the caller is responsible for generating a response and completing the callback.</p>
```

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/Handshaker.java
> +     * @return true if the WebSocket upgrade was attempted
```suggestion
     * @return true if a response was generated, false if a response is not generated
```

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketCreator.java
>   * Abstract WebSocket creator interface.
All javadocs paragraphs must be wrapped with `<p>...</p>`.

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketCreator.java
> +     * complete the {@link Callback}.</p>
Can it modify the response headers?

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketMappings.java
> +     * This will attempt to find a WebSocket mapping and upgrade a request to WebSocket.
Javadoc guidelines suggest to use 3rd person to write javadocs, so rather than "This will do something" use "Does something".
Here in particular, "Attempts to upgrade a request to WebSocket, etc.".

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketMappings.java
> +     * This will attempt to upgrade a request to WebSocket.
Ditto.

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/WebSocketNegotiator.java
> +     * Create a {@link FrameHandler} from the incoming request.
Use 3rd person and wrap with `<p>`.

Is it worthwhile mentioning when this method is called with respect to upgrade methods and creation methods?

2022-08-10 10:01 UTC, sbordet commented on jetty-core/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/RFC6455Handshaker.java
> +        if (!HttpMethod.GET.is(request.getMethod()))
As this method is tested for every request, I think the test for GET was first because it is the cheapest.

2022-08-10 10:01 UTC, sbordet commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
> +    final AtomicReference<Object> _attachment = new AtomicReference<>();
`private` !!!

2022-08-10 10:01 UTC, sbordet commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
> +    final AtomicReference<Object> _attachment = new AtomicReference<>();
`private` !!!

But, if you use attributes, do you need attachments?

2022-08-10 10:01 UTC, sbordet commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
> +    public static final String WEBSOCKET_WRAPPED_RESPONSE_ATTRIBUTE = "org.eclipse.jetty.websocket.wrappedResponse";
I don't think we want to have "websocket"-named constant in this class, feels like the wrong place.
If they are used by the `Handshaker` implementation, they should be a constant there.

2022-08-10 10:01 UTC, sbordet commented on jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketCreator.java
>       * Create a websocket from the incoming request.
Use 3rd person and wrap with `<p>`.

2022-08-10 10:01 UTC, sbordet commented on jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/SimpleEchoTest.java
> +public class SimpleEchoTest
Don't we have a million of these already? Why do we need this one?

2022-08-10 10:01 UTC, sbordet commented on jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
> +
I would not taint with "WebSocket" anything in this module.
Can these constants be moved in some class in the websocket modules?

2022-08-17 06:29 UTC, lachlan-roberts commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java
> +    public static final String WEBSOCKET_WRAPPED_RESPONSE_ATTRIBUTE = "org.eclipse.jetty.websocket.wrappedResponse";
They are not used in `Handshaker`, and is not used at all by websocket-core.

This is a replacement for the use of the `Attachment` interface which greg didn't like.

This is used from the `JakartaWebSocketServerContainer`, `JettyWebSocketServerContainer`, `JettyWebSocketServlet` and `WebSocketUpgradeFilter`.

2022-08-17 06:33 UTC, lachlan-roberts commented on jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/SimpleEchoTest.java
> +public class SimpleEchoTest
We didn't have a single test which is just a simple echo, and its useful to have this for debugging things, or just for using it as a base for other tests.

2022-08-17 06:42 UTC, lachlan-roberts commented on jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java
> +
I have moved these into `WebSocketConstants` for now, still seems a weird place to put them because websocket-core doesn't use them ever.

2022-09-21 08:09 UTC, sbordet approved these changes

2022-09-21 08:14 UTC, merged