Jetty 12 : Simplify favicon.ico and jetty-dir.css behaviors
eclipse/jetty.project pull request #8470
Opened 2022-08-16 20:07 UTC by joakime

* Remove Server.getDefaultFavicon()
* Remove Server.getDefaultStylesheet()

2022-08-16 20:14 UTC, joakime commented on jetty-core/jetty-server/src/main/java/module-info.java
> +    opens org.eclipse.jetty.server to
This can be removed once ee9/ee8 uses the core ResourceService.

2022-08-16 20:14 UTC, joakime commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
> +            LOG.warn("Unable to find resource: %s/jetty-dir.css".formatted(TypeUtil.toClassReference(ResourceService.class.getPackageName())));
This can happen with badly uber-jar'd projects.

2022-08-16 20:16 UTC, joakime commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
> +        _resourceService.loadDefaultStylesheetIfNotPresent();
If `ResourceService` was a LifeCycle, this could be done in the `doStart()` method instead.

2022-08-18 02:14 UTC, lachlan-roberts reviewed
I don't like how the serving of the stylesheet is sometimes handled within `ResourceService` and sometimes outside of it.

But if it works it that's fine, just a few questions.

2022-08-18 02:14 UTC, lachlan-roberts commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
> +    public void loadDefaultStylesheetIfNotPresent()
Could this just call the other `loadStyleSheet` method?

```java
if (_stylesheetBuffer != null)
    return;

try
{
    URL url = ResourceService.class.getResource("jetty-dir.css");
    if (url == null)
    {
        LOG.warn("Unable to find resource: %s/jetty-dir.css".formatted(TypeUtil.toClassReference(ResourceService.class.getPackageName())));
        return;
    }
    
    loadStylesheet(ResourceFactory.root().newResource(url));
}
catch (IOException e)
{
    LOG.warn("Unable to load default stylesheet", e);
}
```

2022-08-18 02:14 UTC, lachlan-roberts commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java
> +                    if (_resourceService.sendStylesheet(pathInContext, servletContextRequest, servletContextResponse, callback))
Why are we sending the stylesheet here?

2022-10-02 03:10 UTC, gregw requested changes

2022-10-02 03:10 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
> +    public void loadStylesheet(Resource stylesheet) throws IOException
I this `setStyleSheet` is a better name.  The fact that it needs to be loaded to be used, is implementation detail.

2022-10-02 03:10 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
> +    public void loadDefaultStylesheetIfNotPresent()
why is this needed as a public API?

2022-10-02 03:10 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
> +            if (isStylesheetRequest(pathInContext))
Is this the right place for this? Perhaps we should first look for the real resource and only check if it is a stylesheet request if it misses.  This has better performance for other resource hits and allows the stylesheet to be overriden is specific directories.

2022-10-02 03:10 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java
> +                if (sendStylesheet(pathInContext, request, response, callback))
why is this a boolean return?  Do we expect failure to be frequent? Can't it just throw and let normal exception handling deal with it?

2022-10-02 03:10 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/DefaultHandler.java
> +            try (InputStream in = url.openStream();
Isn't using URL going to use the internal URL cache that will load the jar into memory again and then not use it?
Can't we use getResourceAsStream instead?

2022-10-03 19:19 UTC, joakime commented
I'm closing this.

The recent proposed work for the HttpContent.Factory hierarchy would make this effort far easier.

I can see a `StaticHttpContentFactory` that sits after `ResourceContentFactory` and just returns a pre-configured `StaticHttpContent` for requests ending in `/jetty-dir.css`.
A similar process to how it works currently in `ResourceService`.

https://github.com/eclipse/jetty.project/blob/a3f226876669e31fd990a18db83452de09c86f6e/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java#L109-L124

2022-10-03 19:19 UTC, closed without merging