Fixes #8723: Provide a thread-safe way to modify HttpClient proxies
eclipse/jetty.project pull request #8731
Opened 2022-10-18 20:38 UTC by cowwoc

…at runtime.

2022-10-18 20:47 UTC, cowwoc commented
Moving from `ArrayList` to `CopyOnWriteList` adds thread-safety while retaining backwards compatibility.

2022-10-18 23:38 UTC, cowwoc commented
I'm not sure what's causing `continuous-integration` to fail. Can someone help?

2022-10-20 08:16 UTC, sbordet requested changes
Would you mind to update this PR by replacing the calls to `getProxies().add()` with the new `addProxy()` like you have done in 12? In this way the 2 codebases have less differences.

Also, I won't mind you fixing the `ProxyServletTest` here too (see my comment in the other PR).

2022-10-20 08:16 UTC, sbordet commented on jetty-client/src/main/java/org/eclipse/jetty/client/ProxyConfiguration.java
> +        proxies.add(proxy);
```suggestion
        proxies.add(Objects.requireNonNull(proxy));
```

2022-10-24 17:45 UTC, cowwoc commented
@sbordet How about this?

I couldn't update the v12 branch because the main branch has broken the build.

2022-10-25 07:54 UTC, merged

2022-10-25 08:00 UTC, sbordet commented
@cowwoc thanks!
This PR has been merged to Jetty 10, 11 and 12.