Issue #8721 fix jetty:effective-web-xml goal
eclipse/jetty.project pull request #8745
Opened 2022-10-20 05:27 UTC by janbartel

Closes #8721

2022-11-14 17:48 UTC, joakime commented
@olamy @janbartel bump

2022-11-15 06:58 UTC, olamy requested changes

2022-11-15 06:58 UTC, olamy commented on jetty-maven-plugin/src/it/jetty-effective-web-xml-it/postbuild.groovy
> +assert effectiveWebXml.text.contains('<param-name>org.eclipse.jetty.resources</param-name>\n    <param-value><![CDATA[\n    "${user.dir.uri}/resources/target/classes/META-INF/resources"]]></param-val
this comparaison with EOL being system dependent looks a bit fragile to me.
Maybe you could use groovy `XmlSlurper`
with something such
```
def effectiveWebXml = new XmlSlurper().parse( new File( basedir, 'webapp-war/target/effective-web.xml') )
```
then make some assert navigating the xml tree (doc here https://groovy-lang.org/processing-xml.html)

2022-11-17 03:05 UTC, olamy approved these changes

2022-11-20 22:02 UTC, merged