Fixes #8975 - Rename getBaseResponse() to getServletContextResponse().
eclipse/jetty.project pull request #8976
Opened 2022-11-29 13:52 UTC by sbordet

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

2022-11-29 13:56 UTC, lorban requested changes

2022-11-29 13:56 UTC, lorban commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
> +        throw new IllegalStateException("could not find %s for %s".formatted(ServletContextResponse.class.getSimpleName(), response));
If that doesn't break anything, we're missing a test.

2022-11-29 13:59 UTC, sbordet commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
> +        throw new IllegalStateException("could not find %s for %s".formatted(ServletContextResponse.class.getSimpleName(), response));
@lorban it's the kind of "should never happen" and matches with the corresponding `ServletContextRequest.getServletRequest(...)` implementation, which I doubt has a test.

2022-12-06 09:52 UTC, lorban approved these changes

2022-12-06 14:08 UTC, merged