TCK: Named dispatch includes must not have include attributes set.
eclipse/jetty.project pull request #9074
Opened 2022-12-19 23:12 UTC by janbartel

According to the spec, section 9.3.1 the target of a named dispatcher that is an include must _not_ have the `jakarta.servlet.include.*` attributes set.

2022-12-20 06:33 UTC, janbartel commented
@lachlan-roberts need your review on this. Pay particular attention to the changes to solve point 3 (ie reporting the values from the original request) - is there a better solution here?

2022-12-20 08:57 UTC, gregw commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java
> +            }
I'm a bit worried that this approach will get confused if the value is meant to be null (eg a null pathInfo).
So perhaps use the attribute technique to fetch the original request, each `ForwardRequest` asks it's wrapped request for the original request attribute. When it get's null, it knows it is the first forward and returns it's wrapper.

2022-12-20 11:10 UTC, lachlan-roberts requested changes

2022-12-20 11:10 UTC, lachlan-roberts commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java
>              switch (name)
If `name` is null this could throw NPE.
I know this was the case before but now you have the `name != null` check intellij is warning me about it.

Maybe we should have some code like this at the start of these methods
```java
if (name == null)
    return super.getAttribute(name);
```
or 
```java
if (name == null)
    return null;
```

2022-12-20 11:10 UTC, lachlan-roberts commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java
> +            if (name != null && name.startsWith(__FORWARD_PREFIX))
I don't think this always works.

If we did a forward -> named forward -> forward, then I think this breaks. 

Then the last forward would see the null from the named dispatch wrapper and assume that it is the first forward dispatch.

2022-12-22 03:19 UTC, gregw approved these changes

2022-12-22 03:19 UTC, gregw commented on jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java
> +    public static final String __ORIGINAL_REQUEST = "org.eclipse.jetty.originalRequest";
maybe put ee10 in the name to protect against future cross context dispatches between ee10, ee11 and then back to ee10.

2022-12-23 11:38 UTC, lachlan-roberts reviewed
Where do you set the `__ORIGINAL_REQUEST` attribute?

I would have thought it would be made available by `ServletApiRequest#getAttribute` or something similar.

2022-12-24 00:12 UTC, gregw commented
> Where do you set the `__ORIGINAL_REQUEST` attribute?
> 
> I would have thought it would be made available by `ServletApiRequest#getAttribute` or something similar.

@lachlan-roberts 
It is in the code:
```java
                case __ORIGINAL_REQUEST:
                    HttpServletRequest originalRequest = (HttpServletRequest)super.getAttribute(name);
                    return originalRequest == null ? _httpServletRequest : originalRequest;
```

So the inner most forwarded wrapper works out that it is the innermost by getting a null value for the super.getAttribute, thus it returns it's wrapped request as the original.
All outer forward wrappers will see this non null value and pass it up.

2022-12-24 00:31 UTC, lachlan-roberts commented
@gregw ok, so its not really the original request but the first forwarded request.

2022-12-24 03:03 UTC, gregw commented
> @gregw ok, so its not really the original request but the first forwarded request.

It's the request wrapped by the first forwarded request, so that is either the original request or something that wraps the original request in a non consequential way.

2022-12-25 08:44 UTC, lachlan-roberts approved these changes

2023-01-12 01:37 UTC, merged