Jetty 12.0.x reenable jetty ee10 tests
eclipse/jetty.project pull request #9214
Opened 2023-01-27 03:11 UTC by janbartel

Uncomments and mostly fixes the `jetty-ee10/jetty-ee10-test` subprojects that were commented out. Other issues have been opened for the tests that have been `@Disabled`.

2023-02-01 00:43 UTC, janbartel commented
@lachlan-roberts can you look at this failing test? https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-9214/7/tests

2023-02-09 08:57 UTC, janbartel commented
@lachlan-roberts it would be good if we could get this committed before the next release, can you take a look at the org.eclipse.jetty.http.ByteRangeTest.testBadRangeSetPartiallyBad test.

2023-02-09 09:51 UTC, lachlan-roberts commented
@janbartel I removed the test, as we discussed before the test incorrect. It conflicts with other test cases and the RFC says that  

>  "A valid [ranges-specifier](https://www.rfc-editor.org/rfc/rfc9110#rule.ranges-specifier) is "satisfiable" if it contains at least one [range-spec](https://www.rfc-editor.org/rfc/rfc9110#rule.ranges-specifier) that is satisfiable, as defined by the indicated [range-unit](https://www.rfc-editor.org/rfc/rfc9110#range.units). Otherwise, the [ranges-specifier](https://www.rfc-editor.org/rfc/rfc9110#rule.ranges-specifier) is "unsatisfiable"."

so if we have one range-spec which is satisfiable so we should still be able to parse the satisfiable range.

2023-02-14 03:06 UTC, gregw requested changes
Only change needed is that the ID is uppercase "Contexts" not "context", so it can match  the `jetty.xml` file.

Other comments are just niggles/questions.

2023-02-14 03:06 UTC, gregw commented on jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/EchoHandler.java
> +    }
should be necessary?

2023-02-14 03:06 UTC, gregw commented on jetty-ee10/jetty-ee10-tests/jetty-ee10-test-http2-webapp/src/main/java/org/eclipse/jetty/test/webapp/HTTP1Servlet.java
> +        http2Client.connect(sslContextFactory, new InetSocketAddress(host, port), new Session.Listener() {}, new Promise<Session>()
strange that a Http1 servlet is using h2?   But it did before so ???

2023-02-14 03:06 UTC, gregw commented on jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/deploy.xml
> +          <Ref refid="contexts" />
It should be capital C Contexts

2023-02-14 03:06 UTC, gregw commented on jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/basic-server.xml
> +    <New id="contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection" />
```suggestion
    <New id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection" />
```

2023-02-14 03:06 UTC, gregw commented on jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/resources/add-jetty-test-webapp.xml
> +<Configure id="contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
```suggestion
<Configure id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
```

2023-02-14 04:11 UTC, gregw approved these changes

2023-02-15 03:24 UTC, merged