Fix/jetty 10.0.x/uri host mismatch alt
eclipse/jetty.project pull request #9343
Opened 2023-02-12 22:41 UTC by gregw

This is an alternative PR for #9312. This avoids changing the HttpParser and instead checks for a mismatched host only in the `Request.setMetaData` method.

2023-02-12 22:52 UTC, gregw commented
Actually 12 already has this well supported in HttpConnection, other than no compliance mode to allow for a miss-match.

2023-02-13 09:36 UTC, sbordet requested changes

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
> +                    }
Please introduce variables for `HttpChannel`, `HttpCompliance` to make the code more readable?

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: 1.2.3.4:2222"
Uhm. The point of this test was to make sure the authority was extracted from the URI, not the `Host` header.
Perhaps it should be moved to a different test that allows `MISMATCHED_AUTHORITY`.

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: [::1]:2222"
Ditto.

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: alt.example.org",
Ditto

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: alt.example.org",
Ditto

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: alt.example.org",
Ditto.

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: alt.example.org",
Ditto.

2023-02-13 09:36 UTC, sbordet commented on jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
> +                        "Host: alt.example.org",
Ditto.

2023-02-13 16:54 UTC, sbordet approved these changes

2023-02-13 20:43 UTC, merged