Fix #9468 Space in Cookie name
eclipse/jetty.project pull request #9471
Opened 2023-03-07 10:50 UTC by gregw

Added a violation to allow unquoted spaces in cookie values to fix #9468

2023-03-07 16:29 UTC, joakime requested changes
One more test case please.

2023-03-07 16:29 UTC, joakime commented on jetty-http/src/test/java/org/eclipse/jetty/http/RFC6265CookieParserLenientTest.java
> +            Arguments.of("abc = x  y  z ", "abc", "x  y  z"),
Can you add a test case that also uses a value with `token` separators?

``` java
Arguments.of("abc=a:x b:y c:z", "abc", "a:x b:y c:z")
```

2023-03-07 18:58 UTC, joakime commented on jetty-http/src/test/java/org/eclipse/jetty/http/RFC6265CookieParserLenientTest.java
> +            Arguments.of("abc = x  y  z ", "abc", "x  y  z"),
What would happen if the input was `abc=a;x b;y c;z` as well? (semi-colon)

2023-03-08 10:01 UTC, sbordet requested changes

2023-03-08 10:01 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/CookieCompliance.java
> +        SPACE_IN_VALUES("https://www.rfc-editor.org/rfc/rfc6265#section-5.2", "Space in value");
Rename to singular, `SPACE_IN_VALUE`.

2023-03-08 10:01 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
> +                    if (c == ' ' && _complianceMode.allows(SPACE_IN_VALUES))
Do we want to cover also `\t`?
If so, rename the Violation to be `WHITESPACE_IN_VALUE`.
Maybe not such a good idea, it would be almost impossible to restore the correct sequence of spaces and tabs if they are interleaved.

2023-03-08 10:01 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
> +                    else if (c == ';' || c == ',' || c == '\t')
Regardless of the comment above, I don't think we can treat `\t` as a separator between cookies, can we?!?

2023-03-08 10:01 UTC, sbordet commented on jetty-http/src/test/java/org/eclipse/jetty/http/RFC6265CookieParserLenientTest.java
> +            Arguments.of("abc=a:x b:y c:z", new String[]{"abc", "a:x b:y c:z"}),
Add also:

`abc=x y;def=w z`
`abc="x y";def=w z`
`abc=x y;def="w z"`

2023-03-08 10:56 UTC, gregw commented on jetty-http/src/main/java/org/eclipse/jetty/http/CookieCompliance.java
> +        SPACE_IN_VALUES("https://www.rfc-editor.org/rfc/rfc6265#section-5.2", "Space in value");
@sbordet Most of the violations are in the plural.  It is more natural to say you allow the plural than to allow the singular.

2023-03-08 10:57 UTC, gregw commented on jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
> +                    if (c == ' ' && _complianceMode.allows(SPACE_IN_VALUES))
I'm torn.  Easy to add if somebody asks, so let's wait until somebody asks.

2023-03-08 10:58 UTC, gregw commented on jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
> +                    else if (c == ';' || c == ',' || c == '\t')
We don't.  This just changes state to END, which can accept a tab as optional white space around a value, but not as a separator.

2023-03-08 11:17 UTC, gregw commented on jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
> +                    if (c == ' ' && _complianceMode.allows(SPACE_IN_VALUES))
I've decided not to add `\t` support unless somebody asks for it.

2023-03-08 11:19 UTC, gregw commented on jetty-http/src/main/java/org/eclipse/jetty/http/CookieCompliance.java
> +        SPACE_IN_VALUES("https://www.rfc-editor.org/rfc/rfc6265#section-5.2", "Space in value");
maybe should be `SPACES_IN_VALUES`?

2023-03-08 15:21 UTC, joakime approved these changes

2023-03-08 16:11 UTC, sbordet approved these changes
Just a glitch on how `\t` is treated specially (which is orthogonal to this issue, but it has highlighted this special treatment), otherwise LGTM.

2023-03-08 16:11 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java
> +                    else if (c == ';' || c == ',' || c == '\t')
Not sure I follow. If we encounter `\t` the value ends, so it is a terminator char for the value, hence a separator between cookies, like the other chars in the `if` statement.

`\t` is a control char, so it's forbidden in every RFC, isn't it? 
Why do we treat it specially? Historical reasons?

2023-03-08 20:07 UTC, merged

2023-03-09 08:45 UTC, gregw commented
@sbordet tab is treated specially as we have a violation that allows optional white space before/after a value.  RFC6265 defines OWS in terms of WSP, which in RFC5234 is space or tab.    Hence when we extended where OWS could be in the violation, we also included tab.

In this PR, we are allowing a space to be in the value, which is different to OWS, hence the decision to not include tab.