Fixing #9517 - bad url-pattern prefix match behavior
eclipse/jetty.project pull request #9518
Opened 2023-03-17 19:32 UTC by joakime

New testcase to ensure we don't have a reversion on this behavior.
Restore a prefix matching loop that we previously had in Jetty 10.0.13

2023-03-17 19:33 UTC, joakime commented on jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
> +                MappedResource<E> suffix = _suffixMap.get(path, i + 1, path.length() - i - 1);
Just renamed "prefix" here to "suffix" to be more clear about usage.

2023-03-18 14:24 UTC, gregw commented
@joakime I pushed an update to the loop that uses the length of the last match to improve the search for a shorter match.  Much better than searching on every string length.

However, I don't like the magic number 3 (which is the "/*" minus 1 more), but I think it works.  Could perhaps have more testing of 1 char patterns?

Also there was another optimized prefix match that needs same fix.

2023-03-19 06:08 UTC, gregw approved these changes, later dismissed

2023-03-20 15:17 UTC, sbordet requested changes

2023-03-20 15:17 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
> +            int specLength = prefix.getPathSpec().getSpecLength();
Put `prefix.getPathSpec()` in a local variable.

2023-03-20 15:17 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
> +            prefix = specLength > 3 ? _prefixMap.getBest(path, 0, specLength - 3) : null;
What's the magic `3`?

2023-03-20 15:17 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
> +                                prefix = specLength > 3 ? _prefixMap.getBest(path, 0, specLength - 3) : null;
Magic `3`?

2023-03-20 15:17 UTC, sbordet commented on jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java
> +                                int specLength = prefix.getPathSpec().getSpecLength();
Put `prefix.getPathSpec()` in a local variable.

2023-03-20 15:17 UTC, sbordet commented on jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
> +        assertMatch(p, "/foobar", "any");
Can you add here `/fo` and `/foob`?

2023-03-20 15:17 UTC, sbordet commented on jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java
> +        assertMatch(p, "/foobar", "any");
Ditto

2023-03-20 15:49 UTC, sbordet approved these changes

2023-03-20 16:53 UTC, merged