parameterize MultiPartServletTest for complianceModes and add extra test
eclipse/jetty.project pull request #9531
Opened 2023-03-24 03:32 UTC by lachlan-roberts

No behaviour changes just improving the test.

- add test to check that maximum number of parts is allowed.
- parameterise tests over RFC7578 and LEGACY compliance modes.

2023-03-28 08:31 UTC, sbordet requested changes

2023-03-28 08:31 UTC, sbordet commented on jetty-servlet/src/test/java/org/eclipse/jetty/servlet/MultiPartServletTest.java
> +        for (int i = 0; i < 1000; i++)
IIUC, this is the default value of `maxFormKeys`. If so, make the `ServletContextHandler` in `start()` a field, and here call `contextHandler.getMaxFormKeys()` so this is not a "magic" number.

2023-03-28 08:31 UTC, sbordet commented on jetty-servlet/src/test/java/org/eclipse/jetty/servlet/MultiPartServletTest.java
> +        for (int i = 0; i < 1001; i++)
Ditto.
Number `1001` seems a typo, so use `contextHandler.getMaxFormKeys() + 1` instead.

2023-03-28 10:33 UTC, lachlan-roberts commented on jetty-servlet/src/test/java/org/eclipse/jetty/servlet/MultiPartServletTest.java
> +        for (int i = 0; i < 1000; i++)
Yes, but I also wanted to test that the default value was reasonable as the typical usage of Jetty doesn't have someone explicitly setting `maxFormKeys`.

2023-03-28 11:52 UTC, sbordet commented on jetty-servlet/src/test/java/org/eclipse/jetty/servlet/MultiPartServletTest.java
> +        for (int i = 0; i < 1000; i++)
Sure, you can assert that separately, something like `context.getMaxFormKeys() > 500 && < 1500`.

2023-03-30 08:59 UTC, sbordet approved these changes

2023-04-03 14:48 UTC, joakime approved these changes

2023-04-03 14:48 UTC, joakime commented
@lachlan-roberts you can merge this one now

2023-04-05 23:34 UTC, merged