Fix flakey test `QueuedThreadPoolTest.testThreadPool`
eclipse/jetty.project pull request #9623
Opened 2023-04-04 08:48 UTC by lorban

See #9622

2023-04-04 16:15 UTC, sbordet requested changes

2023-04-04 16:15 UTC, sbordet commented on jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java
> +                LOG.info(timeoutEvent.getDescription() + " " + tp);
Please use "{}" not concatenation.
Also, maybe `tp.dump()`?

2023-04-05 07:10 UTC, gregw submitted a review, later dismissed

2023-04-05 08:08 UTC, lorban commented on jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java
> +                LOG.info(timeoutEvent.getDescription() + " " + tp);
This doesn't apply anymore.

2023-04-05 16:50 UTC, sbordet approved these changes

2023-04-05 16:52 UTC, merged