Fixes #9438 - Jetty 12: Review JakartaWebSocketClientContainer use of…
eclipse/jetty.project pull request #9626
Opened 2023-04-04 17:38 UTC by sbordet

… reflection

* Removed the use of reflection as it was unnecessary.
* Improved `setShutdownContainer()` to take into account multiple web applications, so it is now a `Map<ClassLoader, ContainerLifeCycle>` so that each web application has its own container to register `JakartaWebSocketClientContainer` instances.

2023-04-05 04:24 UTC, lachlan-roberts requested changes

2023-04-05 04:24 UTC, lachlan-roberts commented on jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-client/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/client/JakartaWebSocketClientContainer.java
> +    private static final AtomicReference<Map<ClassLoader, ContainerLifeCycle>> SHUTDOWN_MAP = new AtomicReference<>(new ConcurrentHashMap<>());
Do we need this `AtomicReference`? Doesn't look the value is ever modified.

Can't we just have the 
```java
private static final Map<ClassLoader, ContainerLifeCycle> SHUTDOWN_MAP = new ConcurrentHashMap<>();
```

2023-04-05 04:29 UTC, lachlan-roberts commented
@sbordet there is now failing tests that are expecting the container to be a bean contained in the contextHandler. So this expectation will need to be changed.

I think the reflection was just an optimisation to be able to be used in embedded Jetty without having to manually add the Shutdown SCI.

2023-04-05 17:29 UTC, sbordet commented
> I think the reflection was just an optimisation to be able to be used in embedded Jetty without having to manually add the Shutdown SCI.

Can you expand on this?
IIUC, even when used in embedded Jetty, in a server scenario, the SCI will run because it is in the jar that you must put in the class-path, so the shutdown SCI will always be there and run.
So I don't see the "optimization"?

2023-04-05 23:32 UTC, lachlan-roberts commented
> Can you expand on this?
> IIUC, even when used in embedded Jetty, in a server scenario, the SCI will run because it is in the jar that you must put in the class-path, so the shutdown SCI will always be there and run.
> So I don't see the "optimization"?

The SCI is not automatically discovered and run in embedded Jetty using `ServletContextHandler`. You need to manually add it with `contextHandler.addServletContainerInitializer(shutdownContainer)`. To discover the SCIs you need to properly configure a `WebAppContext`.

And so in this case, the container is added to a bean on the context handler and nothing is done with the shutdown container. The websocket client container is then shutdown when the contextHandler stops and no SCI is required.

2023-04-06 08:43 UTC, gregw reviewed
Looks reasonable to me. But will defer to @lachlan-roberts to give the green tick.

2023-04-07 07:50 UTC, lachlan-roberts commented
@sbordet @gregw I found a case which worked previously but is now broken after this PR.

If you have two servers using `ServletContextHandler` then stopping one server will stop the ClientContainer from the other server. Previously this did not happen because we were adding to a bean on the ContextHandler and not using the static map on shutdown container.

So this PR actually breaks the use case of using embedded Jetty without classloader isolation. And this was the reason that we introduced this reflection in the first case.

I have a test case for this which passes on Jetty 12.0.x branch and fails on this branch.

2023-04-07 08:10 UTC, gregw commented
@lachlan-roberts So is your use-case not using different classloaders for each context, so that the key used in the map is just the system classloader?

At the time the ServletContextListener is called to tell us to context is stopping, we know the context and we know that we might be using jakarta websocket clients.  Surely we can iterate through the map (should it be a list) and just find the containers that are within a specific context to shutdown?

I guess the problem is on the other end... when we start a container, how does it know which context it is in... without using reflection?

2023-04-07 11:22 UTC, sbordet commented
@lachlan-roberts @gregw I restored (but simplified) the use of reflection.
Also put in the code the comments about the 3 mechanisms.

2023-04-12 12:54 UTC, gregw approved these changes
Good comments!

2023-04-12 22:29 UTC, lachlan-roberts approved these changes
LGTM

2023-04-13 07:50 UTC, merged