deprecate PushSessionCacheFilter (9.4)
eclipse/jetty.project pull request #9716
Opened 2023-05-01 04:41 UTC by lachlan-roberts

deprecate PushSessionCacheFilter in 9.4.x

2023-05-01 11:55 UTC, joakime approved these changes

2023-05-01 11:56 UTC, joakime requested changes, later dismissed

2023-05-01 11:56 UTC, joakime commented on jetty-servlets/src/main/java/org/eclipse/jetty/servlets/PushSessionCacheFilter.java
> +@Deprecated
Should really have a javadoc also ...

``` java
/**
 * @deprecated no replacement for this deprecated http feature
 */
```

2023-05-03 21:39 UTC, gregw approved these changes

2023-05-03 23:43 UTC, merged