Issue #9731 infinite loop in role refs
eclipse/jetty.project pull request #9732
Opened 2023-05-04 12:55 UTC by janbartel

2023-05-04 12:57 UTC, gregw requested changes

2023-05-04 12:57 UTC, gregw commented on jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/UserIdentityScope.java
> +        return roleRefMap.get(role);
```suggestion
        String deref = roleRefMap.get(role);
        return deref == null ? role : deref;
```

2023-05-04 15:15 UTC, gregw approved these changes
This looks good for ee9. But did i make a similar error in ee10?

2023-05-05 08:53 UTC, janbartel commented
> This looks good for ee9. But did i make a similar error in ee10?

Nope. I checked.

2023-05-05 14:58 UTC, merged