Issue #9682 - fix RetainableByteBuffer release bug in WebSocket
eclipse/jetty.project pull request #9759
Opened 2023-05-11 01:26 UTC by lachlan-roberts

## Issue #9682

I suspect this is the cause for issue #9682, but not enough information to confirm.

The test `SuspendResumeTest.timeoutWhileSuspended()` reproduces a the leak where the buffer from the RetainableByteBufferPool is not released after the websocket connection is closed.

This could happen in two cases.
1. The application does not demand another frame and there is still data in the network buffer, then an idleTimeout happens and the connection is closed and the network buffer still contains data and is never released from WebSocketConnection.
2. The application suspends with the Jetty WebSocket API, the frame+callback are stored away until resume is called, then the idleTimeout fires and the connection is closed, the delayed callback is never completed so the network buffer is never released.

2023-05-11 15:16 UTC, sbordet requested changes

2023-05-11 15:16 UTC, sbordet commented on jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
> +                    callback = delayedCallback;
Should not you null out the fields, like you did before?

2023-05-11 15:16 UTC, sbordet commented on jetty-websocket/websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/SuspendResumeTest.java
> +    public void timeoutWhileSuspended() throws Exception
Rename to `testTimeoutWhileSuspended()` following the pattern we use elsewhere.

2023-05-12 07:11 UTC, gregw submitted a review, later dismissed
Fix looks good, but some niggles.

2023-05-12 07:11 UTC, gregw commented on jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
> +                    delayedFrame = frame;
I'm so glad we are getting rid of suspend/resume!
Can you add an `assert delayedFrame==null` here just to show that we know that there can only be 1 delayed frame.

2023-05-12 07:11 UTC, gregw commented on jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java
> +            suspendedCallback = delayedCallback;
Not a big fan of mixing the `suspended` and `delayed` naming here.   How about calling the local variable `theDelayedCallback`.  (Note that is why I like the underscore prefix!)

2023-05-15 13:57 UTC, gregw approved these changes

2023-05-15 18:02 UTC, sbordet approved these changes

2023-05-22 07:52 UTC, merged