Jetty 12 http field processor for #9173
eclipse/jetty.project pull request #9789
Opened 2023-05-20 21:35 UTC by gregw

Address #9173 with a HttpField processor

2023-05-24 14:31 UTC, gregw commented
@sbordet @joakime would be good to get some feedback this week.

2023-05-25 14:17 UTC, sbordet requested changes
A couple of bits here, but mostly see the comments I made in general about this approach.

2023-05-25 14:17 UTC, sbordet commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
> +        }
This method does not cover the removal of the attribute? Also other methods don't do it.
I think that it is necessary when you do:

```java
HttpCookie.build(someOtherCookie)
    .sameSite(null) // clear whatever the other cookie had
    .build();
```

2023-05-25 14:17 UTC, sbordet commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
This is only used in 1 place, and it's the equivalent of `field.getHeader() == header` so I'd remove it.

2023-05-25 14:41 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java
> +        }
fixed

2023-05-25 14:43 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
I know it is not strictly necessary, but it is symmetric with the existing `is(String)` method.
Using `HttpHeader`s should be at least as convenient as using header names, so I'd prefer to keep it.

2023-05-25 14:49 UTC, sbordet commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
I think it's confusing. Why having a method to replace `==`?

2023-05-25 14:52 UTC, sbordet commented
@gregw see my comment, I don't particularly like this approach -- I think using a channel event is better.

2023-05-26 06:02 UTC, gregw commented
@sbordet i agree that a channel listener approach would be better. But i think we should merge the changes i made in this PR that cache the cookie and help reposting it if necessary.   I'll try to rebase on top of event PR.

2023-05-26 06:02 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
As i said. Symmetry

2023-05-27 18:56 UTC, gregw commented
@sbordet actually we don't need the listener for this (and it doesn't support response mutation anyway (see discussion in #9754)).
I've just pushed an alternative implementation that uses the existing `HttpStream` wrapper, which works OK.

thoughts?

2023-06-05 07:42 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
more reasons:
 + I think the code reads better with it.   
 + As I'm used to using `field.is(String)` I instinctively try to use `field.is(HttpHeader)` and am always surprised when it is not there. 
 + I have found and fixed inefficient code that does `field.is(HttpHeader.SOME_HEADER.asString())`
 + it avoids the need to worry about null returns from `field.getHeader()`

But I'm not going to die in a ditch for this.  If you really don't like it, I'll remove it.

2023-06-05 07:43 UTC, gregw commented
@joakime @sbordet ready for re-review

2023-06-05 14:31 UTC, sbordet requested changes

2023-06-05 14:31 UTC, sbordet commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
Yes, I'd prefer it to be removed.

2023-06-06 05:57 UTC, gregw commented on jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java
> +    }
sigh!

2023-06-06 16:30 UTC, sbordet approved these changes

2023-06-07 11:50 UTC, merged