JMX total number of keys in SelectorManager
eclipse/jetty.project pull request #9869
Opened 2023-06-05 05:42 UTC by strogiyotec

Added a new JMX property in SelectorManager that reports the total number of keys from all ManagedSelectors
How it was tested? 
Run embedded Jetty
```
        final Server server = new Server(9090);
        final MBeanContainer mbeanContainer = new MBeanContainer(ManagementFactory.getPlatformMBeanServer());
        server.addBeanToAllConnectors(mbeanContainer);
        server.start();
        server.join();

```
Open VisualVM and check a new JMX property exists 
![image](https://github.com/eclipse/jetty.project/assets/20584185/0c2346b0-35c7-4a61-b227-6f1fe96229fa)

2023-06-07 22:44 UTC, strogiyotec commented
@sbordet  can you take a look

2023-06-08 07:29 UTC, sbordet requested changes
Please also override `toString()` as:

`String.format("%s@%x[keys=%d]", getClass().getSimpleName(), hashCode(), getTotalKeys())`

2023-06-08 07:29 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> +    @ManagedAttribute(value = "Total number of keys in all Managed Selectors", readonly = true)
```suggestion
    @ManagedAttribute(value = "Total number of keys in all selectors", readonly = true)
```

2023-06-08 07:29 UTC, sbordet commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> +    public int getTotalNumberOfSelectorKeys()
```suggestion
    public int getTotalKeys()
```

2023-06-09 22:06 UTC, strogiyotec commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> +    @ManagedAttribute(value = "Total number of keys in all Managed Selectors", readonly = true)
thanks will do

2023-06-10 18:51 UTC, strogiyotec commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> +    @ManagedAttribute(value = "Total number of keys in all Managed Selectors", readonly = true)
done

2023-06-10 18:51 UTC, strogiyotec commented on jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java
> +    public int getTotalNumberOfSelectorKeys()
done

2023-06-10 18:52 UTC, strogiyotec commented
@sbordet  I addressed all the comments please take a look

2023-06-10 19:47 UTC, sbordet approved these changes

2023-06-11 17:07 UTC, merged

2023-06-11 17:51 UTC, sbordet commented
@strogiyotec Thanks!