Fix `QueuedPool`'s performance
eclipse/jetty.project pull request #9884
Opened 2023-06-07 12:38 UTC by lorban

Manually maintain `QueuedPool`'s size to avoid calling the super-slow `ConcurrentLinkedQueue.size()`. When `QueuedPool` is hammered with a massive concurrent load, the perf difference can be two orders of magnitude.

Fixes #9881

2023-06-07 13:41 UTC, gregw reviewed
If we are locking and we know the max size, then why use ConcurrentLinkedQueue?   Surely ArrayList would work fine (perhaps as a stack)?

2023-06-07 13:50 UTC, lorban commented
@gregw we use a `ReadWriteLock` to mutually exclude `terminate()` from everything else, so all methods take the read lock before accessing the queue, and `terminate()` is the only one taking the write lock. This lock isn't used for thread safety; all queue access can happen concurrently.

2023-06-07 13:59 UTC, gregw requested changes
This class needs a lot more javadoc about how/why the lock works.   It is very confusing to see all the logic inside the read/write lock blocks, yet it is only protecting 1 field and other fields are modified within the write lock.

2023-06-07 14:10 UTC, sbordet requested changes

2023-06-07 14:10 UTC, sbordet commented on jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java
> +            queueSize.incrementAndGet();
Can you turn this into a `while(true)` with a CAS to be precise in updating the size?

2023-06-07 14:32 UTC, sbordet approved these changes

2023-06-07 14:57 UTC, lorban commented on jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java
> +            queueSize.incrementAndGet();
Done.

2023-06-07 15:01 UTC, lorban commented
@gregw If you look at the fields, there are the unprotected ones:

```java
    private final int maxSize;
    private final Queue<Entry<P>> queue = new ConcurrentLinkedQueue<>();
    private final AtomicInteger queueSize = new AtomicInteger();
```
and the only one protected by the lock, together with a comment:
```java
    // This lock protects the 'terminated' field.
    private final ReadWriteLock rwLock = new ReentrantReadWriteLock();
    private boolean terminated;
```

Isn't that clear enough? If not, would you happen to have some suggestions on how I can make that clearer?

2023-06-07 15:37 UTC, gregw commented
@lorban I can't say how to improve the comments as I don't really understand the synchronisation.   Why are the atomics being updated holding the read/write lock that protects just one field?  Don't answer here. answer in comments!

2023-06-08 16:50 UTC, gregw approved these changes
I'm not sure "fully threadsafe" is the right expression.   Perhaps "racy but of no consequence" would be a better description for any code that relies on 2 atomics.   But OK.

2023-06-08 21:55 UTC, merged