Issue #9682 - notify WebSocket message sinks of connection close
eclipse/jetty.project pull request #9891
Opened 2023-06-08 03:17 UTC by lachlan-roberts

Notify the websocket MessageSinks of connection close so they can release resources.

2023-06-08 03:51 UTC, lachlan-roberts commented
@sbordet I opened a separate issue for #9892 so it can be addressed in a separate PR.

I think just putting the `activeMessageSink` in a lock doesn't really fix the entire problem, probably should be fixed at the websocket-core level.

And the race would be extremely rare, because being in `FrameHandler.onMessage` means you have just read data so idleTimeout is not about to expire. But I think the fix is out of scope of this PR.

2023-06-08 17:06 UTC, gregw requested changes

2023-06-08 17:06 UTC, gregw commented on jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferCallbackAccumulator.java
> +        for (Entry entry : entries)
What if `addEntry` is called simultaneously? 
Perhaps a comment is needed saying this class is not threadsafe and callers must do mutual exclusion.

2023-06-08 17:06 UTC, gregw commented on jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/MessageInputStream.java
> +        }
use `IO.close(super::close)` as it does the try catch for you.

2023-06-14 08:12 UTC, gregw approved these changes

2023-06-15 03:18 UTC, merged