Jetty 12.0.x custom request log  #8819
eclipse/jetty.project pull request #9896
Opened 2023-06-09 11:31 UTC by gregw

Resolves #8819 CustomRequestLog improvements:
 + only add extra detail if the log is a CustomRequestLog
 + add extra detail as a record
 + get authentication state directly from request attribute

2023-06-10 00:15 UTC, mkvl77 approved these changes

2023-06-10 00:19 UTC, mkvl77 approved these changes

2023-06-13 07:11 UTC, gregw commented
@lachlan-roberts @lorban nudge!

2023-06-13 07:40 UTC, lorban requested changes

2023-06-13 07:40 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
> +        default Principal getUserPrincipal()
This method is always overridden, which makes me feel it shouldn't have a default implementation.

2023-06-13 07:40 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java
While you're at it, could you please fix `logLatency()` so that it doesn't use `System.currentTimeMillis()` but rather something like `unit.convert(NanoTime.since(request.getNanoTime()), TimeUnit.NANOSECONDS)`?

2023-06-13 07:40 UTC, lorban commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
> +    interface AuthenticationState
I do not like this name, but I cannot come up with anything better...

2023-06-13 07:43 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
> +    interface AuthenticationState
I went through several different names.... but ultimately called it what the security layer calls it, as that also went through similar name doubts.

2023-06-13 07:47 UTC, gregw commented on jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java
> +        default Principal getUserPrincipal()
There are 5 static usages in ee9 that use this default implementation.  I could introduce an intermediary interface, but this seams simpler.

2023-06-13 08:07 UTC, gregw commented
@lorban Using nanotime now for logged latency.

2023-06-13 08:08 UTC, lorban approved these changes

2023-06-13 09:12 UTC, merged